### ISSUE TITLE
NHML shows 0 balance since today 12:00 CET

### ISSUE THREAD

**Issue by adem4ik** [nicehash/NiceHashMiner#1012]
NHML v1.8.1.8
Location: EU
Windows 10 x64
Intel i5 2320 + GTX 1060 6 GB

Since today 20.02.2018 12:00 CET NHML has stopped to show my BTC balance. I've mined some more than 1 mBTC, so I've got payment on my internal nicehash wallet. After that NHML shows 0 BTC, even thought I'm still mining. I have some BTCs on my nicehash.com statistics for sure, also NHM2 shows the same amount too.

My log: [log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1741053/log.txt)
![image](https://user-images.githubusercontent.com/4707112/36437926-d39266f2-1681-11e8-8b33-cb874f5d9f5a.png)

**Comment by mves001** [comment]
It happened to me once I installed nicehash miner 2. Solution was to overwrite nhml files from rar (didn't touched downloaded miners and config). Restarted pc of course. After that it worked normal again.

And btw, 180 h/s on cryptonight on nicehash? I don't believe it's enough. I gave up on 350 h/s since i had 1 share per 10 minutes at best. Check bytecoin.uk and point your cpu there. You can mine directly to cryptonator bytecoin wallet.

**Comment by adem4ik** [comment]
@mves001 thanks for tip! unfortunately it didn't help. I have installed NHML and NHM2 for a long time, but the issue appeared only yesterday. So I don't think there are any interferences between those 2 clients.

About hashrate, 180-190 is the max i can get on this CPU. There is no surprise, since it is an old sandy bridge CPU from 2011 with only 1/6 MB L2/L3 caches.

**Comment by adem4ik** [comment]
Somehow the problem is fixed by itself.
