### ISSUE TITLE
temp ban - help

### ISSUE THREAD

**Issue by Osher12** [nicehash/NiceHashMiner#1019]
Hello,

After the return of the service, I have received a lot of these messages:

SOCKET ERROR : SOCKET ERROR
SOCKET ERROR : TEMP BANED

**Comment by professor-jonny** [comment]
It is because of the difficulty I believe ant you not returning shares within the time out period, so you get banned.

you need to upgrade your hardware or hope nicehash increase the server bandwidth so they can drop the difficulty.

it would be nice if they set the difficulty based on the hardware to avoid this.

**Comment by S74nk0** [comment]
Issue not related to nhm/nhml client. Write to support@nicehash.com
