### ISSUE TITLE
V 1.8.1.8 Has Stopped Downloading Miners 

### ISSUE THREAD

**Issue by Tweest** [nicehash/NiceHashMiner#1020]
Windows 10 automatically updated today, could have something to do with it. 

Version 1.8.1.8 keeps freezing at "DOWNLOADING MINERS" Not able to close the window

Tried restarting PC, re-downloading the Version to no success. Please help. Thank you 
![capture](https://user-images.githubusercontent.com/36751265/36574436-aa87451e-17fa-11e8-8fc9-2769bf8cf74e.JPG)

**Comment by davlun** [comment]
FIXED FOR ME:  Edited to add my solution on my system.

Have the same issue on the newest NHLM but also on an older version i was running 18.1.5.

Did some troubleshooting, here is what I did to get mine working:
1) needed vc_redist.x64.exe which was in older miner versions folders.  Copied to 1.8.1.8 folder
2) downloaded the bin and 3rdpartybin folders manually and put them in 1.8.18 folder
Note that when you download bin folders, make sure when you unzip that you put contents of the zip and not extract the whole zip, otherwise you get /bin-1.8.1.7/bin when you just need /bin

If this helps you, mine some for me: 3AgeM2mZ6xsXSmM1ei15fAuonfMWtuYaj4

**Comment by oancea** [comment]
I have the same problem: when I start the program it blocks when reaches to download miners.
Where can I find the older versions you are talking about?
Also, past days after installing beside the old geforce GTX 1060 3GB another graphic card AMD RX 570 4gb, when I reached to benchmark the new AMD graphic card, the program crashes and only let me benchmark Cryptonight and Kecad.
Anticipate tranks !!!

**Comment by Snailie** [comment]
I have the exactly same problem as user Tweest.

**Comment by yuripavlov2** [comment]
I cant find vc_redist.x64.exe anywhere. Is anybody knows where I can get it from?

**Comment by oancea** [comment]
I've copy the BIN and BIN_3RDPARTY forlders from another computer who also has version 1.8.1.8 and it looks like it skipped the download miners phase; now it's banchmarking and I'll see what's happening.
The vc_redist.64.exe file is in BIN folder
I'll be back with more info.

**Comment by oancea** [comment]
Yes, it worked just fine; banchmacked 90% of miners on standard search (not precise), and now is mining dual on each of the 2 graphic cards - on Nicehash.com page it shows me 4 miners on the same computer with 2 graphic cards.
The  speeds are not that great like Bios Modded and Afterburn but at least it's stable.

**Comment by yuripavlov2** [comment]
I find the solution too. I found good worked miner on the one of my rigs and zipped it with all included folders. After that I copied that file to another machine, unzipped it and run. I just changed name of worker and pressed "start". That's all.

**Comment by smeep0** [comment]
I can't find a copy of the BIN and BIN_3RDPARTY folders.

**Comment by ghost** [comment]
@Tweest 
I have spent hours and hours trying to figure out the issue, I reformatted my rig and went back to install any version of legacy with issues getting past the downloading miners. I ended up doing anything and everything I could think of. Anyways I dont have a fix and glad I came across your post. I was led to believe it was only me!

I would like to know if you found a way to fix the issue.

**Comment by corroro** [comment]
I resolved my issue by following step 2 of davlun's solution. Don't need Step 1 since vc_redist.x64.exe is already inside latest bin. Note his note part (LOL).

Quoting his post: 
"2. downloaded the bin and 3rdpartybin folders manually and put them in 1.8.18 folder
Note that when you download bin folders, make sure when you unzip that you put contents of the zip and not extract the whole zip, otherwise you get /bin-1.8.1.7/bin when you just need /bin"

**Comment by damperl** [comment]
Same issue ill try the downloading the bins

**Comment by ghost** [comment]
@corroro 

I was able to try this and get it to work on just 1.8.1.7 with the bins and 3rdpartybins from that release.

I could not get it to work for 1.8.1.8 / 1.8.2.0 

I followed the exact same procedure as I did in 1.8.1.7 but no luck.

I couldnt find 1.8.2.0 3rdpartybins?

**Comment by corroro** [comment]
I only tried it in 1.8.1.8. Does your directory look like this?

![capture](https://user-images.githubusercontent.com/34698047/36618974-0ced83b6-1928-11e8-9f30-d7c7c43fc3db.PNG)

**Comment by ghost** [comment]
Correction,

I was able to get 1.8.1.7 & 1.8.1.8 to both work using the exact same method. For some reason 1.8.2.0 just will not work.

**Comment by luongk** [comment]
Additionally, disable your antivirus (including MS Security Essentials) and/or whitelist the nicehash directory.

**Comment by DillonN** [comment]
This is a result of GitHub updating how files can be downloaded

I've updated the release page to note this and yes the correct workaround is to manually download bin.zip and bin_3rdparty.zip and extract them to the folder. @corroro has the correct folder structure, with folders bin and bin_3rdparty in the root NHML folder. The proper zip files are linked on the release page. Note there are no 1.8.1.8 specific bins since 1.8.1.7 is the last time they were changed (1.8.1.7 zips work for both versions)

You do not need to run vc_redist every time. After it is installed once on the PC it should be there for good (unless you uninstall it). If you get missing dll errors then try installing it

Will work on a fix and hopefully have it up soon

EDIT: ~~1.8.2.0 does not have bin zips linked on the release page, I will update that~~ Fixed

**Comment by ghost** [comment]
@DillonN 
Hey,
I was able to do the work around as mentioned above for only two versions of legacy: 1.8.1.7 and 1.8.1.8, I tried both of these because I could not get 1.8.2.0 to work after doing the suggested method. 

After running 1.8.1.7 and completing all the benchmarks I find I am still having issues, right of the get-go it went to equihash but I kept getting a error of: Cudamemcpy ( I have searched around but can not seem to find anything related.) 

Thanks again

**Comment by jgvinstl** [comment]
Ok, so I am trying the manual workaround (download and extract bin to 1.8.1.8 folder) but when I run 1.8.1.8, the bin folder keeps disappearing. I am not sure what I am doing wrong. It is still getting hung up on the miner download

**Comment by ghost** [comment]
@jgvinstl 
I used 7zip and did the following:

Downloaded nicehash 1.8.1.8 and extracted the file
Right clicked on 3rd party bins and selected 7zip
In 7zip I selected the bin folder and clicked Extract to:
Selected the nicehash 1.8.1.8 folder and hit ok

This than would put the contents of the folder into the nicehash folder.

Do this for both bins and 3rdpartybins.

All of this will allow you to open nicehash 1.8.1.8 and get to the benchmarking

Beyond that I still have issues with nhlm after the benching, errors, restarts, freezing. Forced to go back to NHM 2.0

**Comment by Peskov** [comment]
при загрузке майнеров прога стоит на месте и не закрывается ,приходится закрывать через диспетчер задач 
![screenshot_1](https://user-images.githubusercontent.com/20244694/36633187-bbd7106a-1999-11e8-99ee-661ec24dca4c.png)

**Comment by volunteers82** [comment]
Hi im a newbie miner and i have been working for two days trying to get ANY mining program to work, everything either freezes or crashes. Nicehash is the miner i really would like to use but im having the same problem, legacy freezes on downloading miners. I tried downloading the bins and manually putting them in the folder but it didnt work. Why can't I get ANY miner to run, what am i missing?

**Comment by serh39** [comment]
@Peskov  тут пишут свои проблемы ТОЛЬКО на русском, используйте пожалуйста переводчик

**Comment by serh39** [comment]
@Peskov выше фикс данной проблемы
Используйте переводчик

**Comment by Peskov** [comment]
Nicehash  working ! 
uploaded version of NHML-1.8.1.7
downloaded archive bin_1_8_1_7
archiph bin_3rdparty_1_8_1_7
Then moved this folder to the root folder in the same folder as NikeHashMiner Legacy.exe
I started the miner and everything worked fine

**Comment by Peskov** [comment]
![screenshot_4](https://user-images.githubusercontent.com/20244694/36717957-bc1733e6-1ba8-11e8-9110-44e7433cf987.png)

**Comment by DillonN** [comment]
Problem is fixed with 1.8.1.9

For those of you using 1.8.2.0-pre2, there will (finally) be a new prerelease-3 after 1.8.1.10 is released. Pre-3 is top priority after 1.8.1.10 (barring any emergency updates). It will include all additions to the main branch (including this download issue) and some new goodies. This will also likely be the last 1.8.2.0 prerelease version before a final release, where the new features are merged to the stable branch.

I know lots of you have been patiently awaiting an updated version of 1.8.2.0, but with the delays from the hack and other high-priority efforts, lately the main focus has been on the stable branch. However, soon I will be putting all effort into making it a stable release.
