### ISSUE TITLE
Skeeyah.h Virus in NHLM v1.8.1.9 zip

### ISSUE THREAD

**Issue by TRON-N** [nicehash/NiceHashMiner#1074]
Windows defender is picking up a virus in the zip file of Nicehash legacy miner version 1.8.1.9, It does not pick up the virus in the zip file of 1.8.1.8.

The virus it warns about is skeeyah.h which it recons is a trojan.

**Comment by nerdatwork** [comment]
windows defender is a terrible option. Go with Avast or AVG.

**Comment by TRON-N** [comment]
Alright thanks

**Comment by nerdatwork** [comment]
Close this thread if your issue is resolved/answered.

**Comment by Gotitalready** [comment]
Windows defender detected Trojan:Win32/Skeeyah.G in 1.8.1.10 also but not in 1.8.1.8  It is classified as severe.  Rather than change your virus scanner, go back to using 1.8.1.8   I plan on doing that. nerdatwork's suggestion is like saying if a CT scan detected a canerous growth inside of you then change test to something like a blood test so that you won't get a warning that you have cancer.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

All miners software closed or open source is marked flagged by AV software. Malware authors frequently bundle miner software. Use it at your own risk.
