### ISSUE TITLE
Unzip

### ISSUE THREAD

**Issue by rickyapp31** [nicehash/NiceHashMiner#1103]
Anytime I unzip the any of the NHML files ex. 1.8.2.0 the option to open nicehash miner legacy goes away, I literally can not run the program, every time I try to do so it asks me to unzip all the files again which I've already done like 7 times. Please help

**Comment by professor-jonny** [comment]
That is a dev build of nicehash legacy that offers multi threaded benchmarking Download NHML-1.8.1.10 it is the current version.

**Comment by Boricuatec** [comment]
Your antivirus is capturing it or if you're on Windows it's probably Windows Defender you have to exclude that folder from scanning


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: rickyapp31 <notifications@github.com> Date: 3/24/18  4:56 AM  (GMT-08:00) To: nicehash/NiceHashMinerLegacy <NiceHashMinerLegacy@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [nicehash/NiceHashMinerLegacy] Unzip (#1103) 
Anytime I unzip the any of the NHML files ex. 1.8.2.0 the option to open nicehash miner legacy goes away, I literally can not run the program, every time I try to do so it asks me to unzip all the files again which I've already done like 7 times. Please help

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nicehash/NiceHashMinerLegacy","title":"nicehash/NiceHashMinerLegacy","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/nicehash/NiceHashMinerLegacy"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Unzip (#1103)"}],"action":{"name":"View Issue","url":"https://github.com/nicehash/NiceHashMinerLegacy/issues/1103"}}}

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for any bugs or feature requests.

All miners software closed or open source is marked flagged by AV software. Malware authors frequently bundle miner software. Use it at your own risk.
