### ISSUE TITLE
NHML overwrites CPU miner config - xmr-stak-cpu

### ISSUE THREAD

**Issue by utc99** [nicehash/NiceHashMiner#112]
Cannot change parameters for cpu miner in config file, also couldn't find a way to do it trough nicehash. NHML overwrites it every time, read-only mode on config file config_0.txt doest look like a good solution.
Issue is the same as https://github.com/nicehash/NiceHashMiner/issues/950
Aperantly it's is not solved.

**Comment by DillonN** [comment]
@utc99, instead of setting the location/wallet etc through command line as in most miners, NHML sets it for XmrStackCPU through the config file. This means every time the miner is run, NHML prepares a config file with up-to-date location/wallet/miner, writes it to the directory, then runs the miner with the option `config_0.txt` (which tells the miner to use that config rather than the default `config.txt`). If you want to run XmrStackCPU with a manual config, you can edit the `config.txt` file then run `xmr-stack-cpu.exe` directly from the directory. This will run the default config file.

I understand you mean to edit the settings that you cannot change through NHML (some you can change, e.g. num of threads etc), but this is currently not supported when running XmrStackCPU from NHML

**Comment by utc99** [comment]
Well there could be two not terribly difficult solutions maybe:
to edit the default NHML values for that miner trough some other NHML file, 
or maybe make NHML miner to update/overwrite only certain lines of the config, leaving the rest to possible configuration.
That's still the only cpu miner in NHML
