### ISSUE TITLE
CPU miner interupts - XSOCKET ERROR - RECEIVE error: socket closed

### ISSUE THREAD

**Issue by utc99** [nicehash/NiceHashMiner#113]
CPU miner interupts using xmr-stak-cpu. Cpu cryptonight results on nicehash web does't look continuous, it gets interupted every 5-10 minutes. I got the same results by testing separatly few of my workers with NHML and NHM:
![pc3](https://user-images.githubusercontent.com/26816096/28931623-5c4e4052-787f-11e7-806f-74ef2b967755.JPG)

Don't know if it's related but I notices that I get this error every 15-60 minutes (not as often as interupts on the web) on all 50 workers. 
It reconnects in 10 seconds and repeats after some time.
![cpu1](https://user-images.githubusercontent.com/26816096/28931486-f19c8250-787e-11e7-880f-b8ee9c400c31.JPG)

Tried to change api ports - the same.

Tried looking into the miner configs, at least reduce reconection timeout, but this led to another bug: https://github.com/nicehash/NiceHashMinerLegacy/issues/112

**Comment by ChriscomIT** [comment]
Same here. Maybe server inconsistencies?

**Comment by lmlim** [comment]
ditto for me... "socket closed" thing cost me double digit percentage block rejection, in the end i stopped mining xmr altogether.

i have tried pointing to various server location, but no dice.

**Comment by DillonN** [comment]
This is because Cryptonight takes a long time to submit shares (> 10 min sometimes), especially when mining on a CPU. The NiceHash display has gaps because during those periods no shares were submitted, but be assured that you are getting paid for the mining you've done during that period (once the share is submitted, you can see the spikes). 

As for the socket disconnections, this is because NH will timeout the connection if a share isn't received in 10 min. Since CN on CPU can take longer than this to submit the share, the connection timeouts. The miner reconnects in 10 seconds though so there is not much lost.

**Comment by ChriscomIT** [comment]
@DillonN Thanks for the detailed clarification! The pps explanation sounds logic. Much appreciate it!

**Comment by utc99** [comment]
Perfect explanaition, so it's an expected behavior and no need to worry about it, thanks. Issue closed.

**Comment by twocs** [comment]
Given the explanation above, surely it should be a 'warning' rather than an 'error'.
