### ISSUE TITLE
AMD card is not foundt in miner 

### ISSUE THREAD

**Issue by sotmail** [nicehash/NiceHashMiner#1147]
AMD card is found in Bios, Device Manager and MSI Afterburner. 
But not in miner NiceHash Miner Legacy v1.8.1.11

AMD option in miner is NOT disabled.
Nvidia card is found.
This is the cards:
Nvidia - Asus 1070 ti Strix 8GB
AMD - Asus RX580 Strix 8GB

AMD driver is reinstalled (11.40.2011)
Miner is installed several times.
GPU Tweak 2 installed.
Nvidia driver was first installed before AMD driver.
Windows 10 Pro.

**Comment by Crypto-Lord** [comment]
Is your AMD driver the latest?

**Comment by sotmail** [comment]
I have a similar rig with the same version of driver and that is working.
But also tried the newest driver.

**Comment by rpgallan** [comment]
I had the same problem, just ended when i downloaded the last version os adrenaline+drivers on amd support page (win10-64bit-radeon-software-adrenalin-edition-18.3.4-march23) 337MB
But now i cant benchmark, because it dont shows any algorithm, had reinstaled 3 times, redownloaded miners, all stuff, and it just dont shows nothing

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
