### ISSUE TITLE
Trojan:Win32/Spursint.F!cl

### ISSUE THREAD

**Issue by massimotamos** [nicehash/NiceHashMiner#1202]
What the hell is going on?

My friends are malware experts... I will ask to investigate this.

**Comment by hyas1312** [comment]
Thx, my defender deleted it instantly. How do you detect it so fast???

massimotamos <notifications@github.com> schrieb am Fr., 25. Mai 2018, 22:49:

**Comment by Novicracker** [comment]
you will have to add it to your allowed application. add the installer and
once installed add the installation directory.

**Comment by anazz20** [comment]
I am getting a headache from seeing the same non issue posted over and over, is there anyway to put "Your AV will think it is a virus, turn it off while downloading and installing" up in big bold letters? Why does it think it is? Well, because of the way it works, and there are REAL viruses out there that mine without you knowing and not for you.

**Comment by Novicracker** [comment]
thats why I said add the installer to the trusted applications

**Comment by anazz20** [comment]
Oh I know that's why you did, I was just thinking maybe put it above where the changes are listed on GitHub if that's possible. But I also know no matter how many stickies you put on forum boards, not many read them.

**Comment by Novicracker** [comment]
I completely agree. And if I could put that info up top I would. lol

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
