### ISSUE TITLE
Can't run...

### ISSUE THREAD

**Issue by Arbie456** [nicehash/NiceHashMiner#1243]
I am having troubles getting this whole thing started. I have downloaded NiceHash Miner for AMD, but I am unable to run NiceHashMinerLegacy.exe as it states to do in the Get_started.pdf file. When I attempt to run this NiceHashMinerLegacy.exe file (I'm using WinZip Universal btw), I get a message that says "This file is potentially unsafe to open." and it doesn't open. Any and all help will be appreciated.

**Comment by chrisfarley11** [comment]
Dude, turn off your anti virus or allow the nicehash folder through.  No offense but if you don't know enough to do that or to search the internet for a quick fix you shouldn't be mining.

**Comment by Arbie456** [comment]
the thing is... i have changed my antivirus settings to disregard the nicehash download already.

**Comment by Arbie456** [comment]
Now i have it fixed, but my gpu doesnt show up under the devices

**Comment by anazz20** [comment]
What GPU and which driver?

**Comment by chrisfarley11** [comment]
If your antivirus is popping up then you haven't done enough.  You need to allow the program and you need to make the whole folder that you downloaded into an exception.  I keep all my nicehash files in one place, the program, what I downloaded, everything went in to one file and I allowed that file through the anitvirus and as a program made nicehash an exception.  If you can't get around it then I would suggest putting an older version of windows on.  There is no way to stop antivirus all together, it comes back on by default even if you turn it off so the only way through is to make sure everything operating is excepted in the antivirus.
If this is a dedicated miner and not a gaming machine you have mining on the side you should look at simplemining instead of nicehash.  It is harder to setup and runs on linux but it will go around your security problem for sure.

    On Wednesday, June 13, 2018, 7:52:45 PM EDT, Arbie456 <notifications@github.com> wrote:  
 
 
the thing is... i have changed my antivirus settings to disregard the nicehash download already.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
