### ISSUE TITLE
AMD RX580's no longer showing up

### ISSUE THREAD

**Issue by Creativenauts** [nicehash/NiceHashMiner#1249]
None of my GPUs are no longer showing up. Tried historic drivers, nothing seems to work here.

![nh](https://user-images.githubusercontent.com/4481041/41549613-6ec5d9f0-72f4-11e8-9d48-7d5ff05cd9ef.png)

**Comment by Simaex** [comment]
Install W10Pro v1709 and set policy to prevent windows updates. Othervise you have to disable a shitty parameter in registry after you get update to v1803 to get your cards mining again.

**Comment by Creativenauts** [comment]
@Simaex which parameter in registry needs to be disabled? I'd rather do that right now.

**Comment by Creativenauts** [comment]
this is the version I'm running:

Version	10.0.17134 Build 17134

**Comment by foxwarernd** [comment]
check settings - Disable Detection of AMD ?

**Comment by Creativenauts** [comment]
Disable detection of ADM is not checked in settings.

**Comment by Creativenauts** [comment]
going to try beta optimized driver to see if that helps.

**Comment by Creativenauts** [comment]
went back to december 2017 drivers... still nothing works

**Comment by foxwarernd** [comment]
add log files from dir nicehash

**Comment by Creativenauts** [comment]
reinstalled windows a second time and all is good :)

**Comment by Petsuchos** [comment]
Same problem.
Windows 10 EDU, Version 1803, Build 17134.112
Log Attached.
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/2129874/log.txt)
I have, Reinstalled windows and drivers a few times. No luck. Only the Nvidia cards show after launching NiceHash. Even though they are present everywhere else.

**Comment by foxwarernd** [comment]
definitely a problem with AMD drivers. try to put other versions

**Comment by jerikb** [comment]
@DerekBess > reinstalled windows a second time and all is good :)

Which version of windows did you re-install? I had the same problem you originally described, and to be honest of all the fixes I went through I'm not sure which one did the trick. And I'm not shutting it down to mess with it to find out, but I think that will come eventually. I will probably be back to this thread for updates if there are any. I've installed the blockchain drivers most recently, that definitely stabilized the benchmarking. But my problem now is the system crashes during benchmarking if I add a 5th GPU.

**Comment by nickt5174** [comment]
I am having this same issue, there needs to be a work around for this.  Reinstalled windows and the drivers multiple times with out resolution.  I am running 6 RX580 8 g cards on an Intel board.  I had this problem once before, by reinstalling the Microsoft Visual C++ 2013 Redistributable Package.   Tried it again this time with no luck.

**Comment by jerikb** [comment]
@nickt5174 >  I am having this same issue, there needs to be a work around for this. 

I am trying to re-familiarize myself with this and remember what all I did. The most important thing was using AMD drivers 18.2.1. Benchmarking one at a time, like countless videos have said. Most of my problem with this motherboard is unresolved because either it was never designed to function with all 6 PCIe slots populated, or maybe it's an issue with the PLX chip. You can function with cards/risers in Slots 1 and 5 simultaneously, but add anything after that and the system won't see it. I'm still working with an EVGA Forum Moderator and also an EVGA Tech. I may quote the Tech here at some point, but it might embarrass him/her. I have not checked in a couple of nights, but they were down to asking me to send a picture of the motherboard pins, which I did, they were flawless. Anyway. Not sure where you're at but I know your post is recent, and I ran down so many old inactive threads. Let us know how you're doing with it. It drove me crazy. The rig in question for me is an EVGA Z97 Classified motherboard with 2 MSI MK2, 2 Red Devil, 1 Golden Sample and 1 Gaming X. All RX580.

**Comment by pbuva** [comment]
Have you set primary graphics to be integrated (igd(?
Then you will not be able to see anything on the boot, but the windows will go with all the graphics.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
