### ISSUE TITLE
daggerhasimoto benchmark at it again.

### ISSUE THREAD

**Issue by jimmyhackers** [nicehash/NiceHashMiner#1256]
im sure i commented about this aaaages ago....

gtx970....actually hashes at 3-4mhs not the 22mh/s the nicehash profitability calculator says. or how it benchmarks on nicehashlegacy which also give 20-22mh/s.

am i missing something is my hardware faulty......or is this a known fault with the benchmarking still?

**Comment by Simaex** [comment]
It's a known problem that is caused by the nature of Nicehash service. You are leasing your rig for use with different coins that differ a lot in DAG, but when benchmarking you are using a single (and old) DAG. GTX970 have 20M results for DAG that fits in 2G and rather disappointing 4M for the latest DAG that are up to 3Gb. No easy way to deal with the problem, cause if you set you benchmark to 4M you will not use the card in case somebody will purchase a lot of hashpower for a new coin with small DAG.

**Comment by foxwarernd** [comment]
I also have. sadness

**Comment by jimmyhackers** [comment]
heres the thing though.....if this essentially is misleading hundreads/thousands of nicehashes users cards to work at a fraction of their potential.

WHO IS REALLY LOSING OUT?
i half think if nicehash were losing out they would of put more effort into correcting this?
but seeing as they arn't i can only conclude its either of neutral effect or actually works in their favour.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
