### ISSUE TITLE
Feature request: Include optimized ethminer

### ISSUE THREAD

**Issue by zeuz542** [nicehash/NiceHashMiner#128]
Would it be possible to include the ethminer from 

https://github.com/ethereum-mining/ethminer/

It is optimized and works a lot better for me than the included one on my 1060. 
I have tried to just swap out the exe but then it does not start at all.

**Comment by DillonN** [comment]
Thanks for posting, I will look into this

**Comment by ebbbang** [comment]
https://github.com/ethereum-mining/ethminer/

is the best best Ethereum Miner for me right now

**Comment by juanfpina** [comment]
It seems the change that makes the swap not work is instead of --dag-load-mode singlekeep 0 it is now --dag-load-mode single 0, changing that in the command should make it work correctly.

**Comment by DillonN** [comment]
The problem is ethminer doesn't have an API on its own - which NHML uses to get current speed data, among other things. The version of ethminer in NHML now is custom so it has an API

The new update is better for 1060s, but do you see that it is better than just using ClaymoreDual instead (even the Ethereum only one)? CD did have an update recently that increased eth speed for NVIDIA cards as well

**Comment by zeuz542** [comment]
The speed is the same in the new claymore miner as in ethminer. But ethminer does not have any fees.

**Comment by DillonN** [comment]
@zeuz542 note that the Claymore fees are taken into account when benchmarking (the benchmarked speeds are 1% less than actual for strictly ETH mining)

**Comment by zeuz542** [comment]
Did not know that, as the speeds are about the same you can close the issue.
