### ISSUE TITLE
1.9.0.5 NHML downloads the miners everytime I open it. 

### ISSUE THREAD

**Issue by DTG123** [nicehash/NiceHashMiner#1290]
This started with 19.0.4. I guess miners get updated too which is why I always click yes to update, but this is ridiculous because it doesnt save previous cpu.txt. settings in xmr-stak folder

Also getting a CyrtoNight7 socket error for the San Jose service location, europe - amsterdam works fine tho

**Comment by undert03** [comment]
for me the problem was with bin\xmrig\xmrig.exe and every time i would manually extract it from the bin.zip to that directory it would get deleted when i reopened NHLM. So what i did since i don't use xmrig.exe I just make a blank text file and renamed it to xmrig.exe and that fixed the popup every time i opened NHLM

**Comment by merwynv** [comment]
If u use windows os try disabling the real time security, security and all stuff related to system protection. It worked for me.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
