### ISSUE TITLE
1.9.0.5 Missing "Default", "Save and close" & "Close without saving" Button

### ISSUE THREAD

**Issue by nazzier5463** [nicehash/NiceHashMiner#1295]
Anyone notice missing "Default", "Save" and "Close" & "Close without saving" button in settings ? Or just me ? @DillonN

**Comment by jeepwx03** [comment]
I am having the same issue

**Comment by jeepwx03** [comment]
Its related to your resolution within windows. 1440x900 didn't work, but 1400x1050 did

**Comment by nazzier5463** [comment]
@jeepwx03 im glad you can solve this issue but not all monitor support 1400x1050 as u recommended

**Comment by jeepwx03** [comment]
Just try different resolutions or try plugging in different monitors if possible to get that section of the application to operation. it's an issue with some type of auto sizing with the application, but at least it is a work around. I'm thinking the bigger the second number of the resolution the better.

**Comment by alexwmunro** [comment]
i am having same issue and jeepwx03 It is NOT a resolution problem

**Comment by nazzier5463** [comment]
For a temporary, there is other way u can save the setting by pressing TAB button on keyboard. Keep pressing until the "rectangle" at "Run script when CUDA GPU is lost" then after that sould be 
"Default" button, followed by "Save and close button" & "Close without saving button" even u cant see it.

**Comment by Lifeisvirtual** [comment]
Hey guys, it seems the problem is related to the screen's resolution. I was using 1600x900 and I wasn't seeing the save options, but if you play around with the other resolution options it comes into view (my options came into view at 1280x1024). so I guess a quick fix is to find a resolution that brings it into view, change your settings and save, then go back to your original resolution. The settings remain saved even though you change back to your resolution. peace.

**Comment by nazzier5463** [comment]
Fixed on version 1.9.0.6 above
