### ISSUE TITLE
All NHML closes randomly whether I am mining, benchmarking, or idling

### ISSUE THREAD

**Issue by inventorAdam5** [nicehash/NiceHashMiner#1349]
I am running 
-Windows 10 Pro
-16GB RAM
-i7 8700K 3.7 GHz 6-Core Processor
-R9 390 GPU

I have this issue on all versions of NHML I have tried.
Here is a log file with multiple runs: CPU&GPU mining, CPU&GPU mining, and Idle until close/crash
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/2577042/log.txt)

**Comment by foxwarernd** [comment]
firewall does not block your connection (try to disconnect for a while)?
`[2018-10-15 19:02:57] [INFO] [ClaymoreDual-MINER_ID(1)-DEVICE_IDs(0)] GetSummary exception: No connection could be made because the target machine actively refused it 127.0.0.1:4001`

set the paging file equal to the amount of your RAM and the amount of video card memory, that is, 16GB + 8GB = 24 GB
`[2018-10-15 19:01:01] [INFO] [NICEHASH] Page File Size: 6912MB`


try to start manually, that is, create a windows command file with contents in your miner folder Claymore's Dual Ethereum AMD + NVIDIA GPU Miner (usually located in bin_3rdparty \ claymore_dual):
`EthDcrMiner64.exe   -di 0    -epool stratum+tcp://daggerhashimoto.usa.nicehash.com:3353 -ewal 3GGqshWL2x9nn4X6ZUZVYpAnpZWcDcnVe1.worker1 -mport 127.0.0.1:-4001 -esm 3 -epsw x -allpools 1 -dbg -1`

**Comment by inventorAdam5** [comment]
Open, idle, crash
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/2577304/log.txt)
fresh file
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/2577309/log.txt)

**Comment by foxwarernd** [comment]
Open, idle, crash - 
here it cannot connect to the pool to get data on the algorithms - change the server in nh
`[2018-11-13 12:20:56] [INFO] [SOCKET] 11/13/2018 12:20:56|Fatal|WebSocket.connect|A socket operation was attempted to an unreachable network 104.17.61.220:443`

fresh file - 
Mining did not run here at all

and:
set the paging file equal to the amount of your RAM and the amount of video card memory, that is, 16GB + 8GB = 24 GB
`[2018-11-13 12:20:06] [INFO] [NICEHASH] Page File Size: 2432MB`

**Comment by inventorAdam5** [comment]
The problem is that it crashes no matter what after a few minutes

**Comment by foxwarernd** [comment]
need see windows event log:
https://www.veeam.com/kb1873

**Comment by inventorAdam5** [comment]
[New folder (2).zip](https://github.com/nicehash/NiceHashMinerLegacy/files/2577557/New.folder.2.zip)

**Comment by foxwarernd** [comment]
need folders from "C:\ProgramData\Microsoft\Windows\WER\ReportArchive" 
with a name that includes "NiceHashMinerLegacy"

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
