### ISSUE TITLE
Feature request: Make miner path selectable per algorithm, add custom algos

### ISSUE THREAD

**Issue by UselessGuru** [nicehash/NiceHashMiner#135]
For each algorithm I would like to freely configure which miner miner sw to use. The preconfigured miners are not optimal for every hw type.
e.g. on my 1080ti for nist5 the best miner is ccminer_x11gost (84Mh vs. 74Mh with ccminer_claust)

Furthermore I would like to add new algorithms & corresponding miner sw when they pop up.

**Comment by drkskwlkr** [comment]
> For each algorithm I would like to freely configure which miner miner sw to use.

@UselessGuru I think you can do that now, but it will require some footwork. You need to do the following:
+ enable `Allow multiple instances` in NHML settings window
+ disable all GPUs and all algos
+ close NHML
+ make copies of the folder containing NHML files for each GPU+algo pair you want to run
+ start a NHML instance from each folder and re-enable each GPU+algo pair as is your preference

Let me know if this works as needed :)

**Comment by UselessGuru** [comment]
>  **@drkskwlkr** I think you can do that now, but it will require some footwork. You need to do the following:

I don't think this is what I want. How would I set NHLM to use ccminer_x11gost for nist, but the same time use ccminer_claus for sia (this is just an example)?

**Comment by drkskwlkr** [comment]
@UselessGuru How about you put artificially low benchmark numbers by hand for the 'unwanted' algos?

**Comment by DillonN** [comment]
I do see better results with ccminer_x11gost (aka ccminer_alexis), but that miner is a bit experimental. I will look into adding it as a second option, similar to how it shows up now for X11Gost. 

Being able to customize miner paths is a neat idea I can look into in the future, however sometimes it is a bit more complicated than changing the paths since not all ccminer forks have the same interface. E.g., here ccminer_klaust does not have the same benchmarking options as other ccminers do, so if you swap nist5 to that NHML will not be sending the optimal benchmark lines (in this case, benchmark times will not reflect the selected length option). If you did vice-versa, i.e. swap another algo to klaust, benchmarks wouldn't work at all

**Comment by UselessGuru** [comment]
> more complicated than changing the paths since not all ccminer forks have the same interface.

Yep. You would have to create basic miner templates (e.g. for json, ccminer, ccminer-SP. etc.)
To determine hashrates per algo I find [nemosminer ](https://github.com/nemosminer/NemosMiner-v2.0-Zpool/releases) very helpful.

**Comment by DillonN** [comment]
Custom ccminer paths is now supported
