### ISSUE TITLE
Cannot connect to the Internet

### ISSUE THREAD

**Issue by proyaz** [nicehash/NiceHashMiner#146]
I have internet connection working but the miner displays an error saying it cannot connect to the internet. Tried switching ipv4 only but still no luck. First it was not able to download the miners - so I did it manually and after that it says "Unable to get nicehash profitablity data. If you connect to internet, try again later".

**Comment by janwarming** [comment]
I have the same issue, but if I continue I can download the miners, but when I access benchmark I get an exception.

**Comment by Alifton** [comment]
I recently started having a similar issue as well.  I first noticed the internet connection issue in version 1.8.1.0 Prerelease 3.  Prior to the release of 1.8.1.0 I was using version 1.8.0.1 and never encountered this issue.  This issue may be related to and possibly merged with #121.  

Closing the "Unable to get nicehash profitablity data. If you connect to internet, try again later" window then clicking start manually will restart the miner but the miner will not auto resume mining if this error occurs and is not resolved manually.  Possibly a result of the new socket connection method recently implemented?

I saved the log before, during and after the error was manually resolved.  It appears NHML v1.8.1.0 continues to try to poll the servers but fails according to the log. No other miners on my network running older versions of NHML (v1.8.0.1 or earlier) were having any connection issues when this problem occurred.

On the off chance I checked and this is not a firewall issue as some suggested in other threads. NHML v1.8.1.0 is fully whitelisted.

@DillonN If you'd like to a copy of the logs for auditing I can upload a copy.

----

**UPDATED**
 

Attached Log File.  Problem occurs at approximately [2017-08-12 05:07:30]
[log.1.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1219922/log.1.txt)

**Comment by ChriscomIT** [comment]
Any one of you guys use Rivet Networks/Killer Network solution?

**Comment by DillonN** [comment]
@Alifton from the logs it looks like the connection isn't being made to NH servers. There will be an update to the connection methods soon and hopefully this will fix for you all

**Comment by Msetknl** [comment]
I had the same issue with internet connectivity at start-up and was running the pre-release. I downloaded the new version and am doing the benchmark test now. 

--Update: After downloading the current version, everything is working properly.

**Comment by Max1232** [comment]
I have the exact same problem and I have also tried switching the ipv4 and ipv6 configurements. Hopefully someone will figure out a solution seeing as with the regular nicehash miner 2 loads but does not open for me.

**Comment by Alifton** [comment]
I've had a couple days to try out version 1.8.1.1 pre 3 and it seems even with the checkbox to bypass the internet connection check, the front end still halts with an error message when it fails to poll the profitability servers at start up.  It's possible this problem may be server side because I've seen the same issue occur while Claymore's miner was running. Claymore's automatic 20 second rechecks ran until the 3rd fail then defaulted to the EU servers instead of the USA servers without issue.  I have only encountered this connection issue with the Nicehash US servers.  Adding automatic failover without the error popup seems like it would be an easy fix if this issue is only intermittently effecting the US servers.

Can anyone else confirm if this problem has been effecting any of the other global servers?  I'll be running a test rig on the EU servers for the next couple of days to see if they also have the same issue I've been encountering with the US ones.


UPDATE
---

Even after changing my default server to EU from US the miner still halted on startup with the same profitability server connection popup.  The internet check bypass flag was set so the problem may stem from elsewhere.  Closing the window and starting the miner manually still works as before, but the miner will not start automatically if the popup occurs.

**Comment by VanceAnce** [comment]
have some troubles like you had ..... very anoying - cant connect to the stratum server and now thinking to use an other mingint tool  :(

**Comment by kevinmilesM** [comment]
Here is the fix - https://www.youtube.com/watch?v=QjNLVNANOrU

**Comment by Sav87** [comment]
add Pull request #625

**Comment by xtrime-ru** [comment]
@Sav87 made few fixes, so NHML can use another way of getting SMA data if primary method fails.
I've compiled his fixes and made this release:

https://github.com/xtrime-ru/NiceHashMinerLegacy-SMA-FIX/releases

**Comment by DillonN** [comment]
We made some updates to the server and NHML to better support higher volume of users. 

The alternative SMA connection that uses HTTP API (the old way of doing things) was deprecated long ago because it creates a much higher strain - if miners are using this then it will only further exacerbate the load issue for everyone

**Comment by xtrime-ru** [comment]
@DillonN Thanks for solution. Better late than never :) 

I updated description of our sma-fix release and add link to your comment, to warn people not to use fix anymore.

PS. I was using 1.8.1.8 since release and there was no sma issues for a week or so.
