### ISSUE TITLE
Trojan:Win32/Azden.A!cl

### ISSUE THREAD

**Issue by rkresha** [nicehash/NiceHashMiner#1478]
1.9.0.20 is getting flagged by Windows Defender as being a trojan 'Win32/Azden.A!cl'

![image](https://user-images.githubusercontent.com/19247761/55285129-f71bf280-534a-11e9-91ff-c0e0f564496a.png)

**Comment by bpclifford** [comment]
Yes.  Not a virus.  Please read the Troubleshooting section of he GitHub project page for more info.

**Comment by S74nk0** [comment]
@rkresha Most miners are flagged as viruses because they are packaged inside malware. This software and half of the bundled miners are open source so you or the community can check what it is doing. While we cannot vouch anything on closed source miners we have added those as well due to user demand and you can use those at your own will at your own risk.

Closing issue.
