### ISSUE TITLE
Onboard GPU results in a modal dialog that prevents mining

### ISSUE THREAD

**Issue by AlexGoOn** [nicehash/NiceHashMiner#1559]
I have an onboard GPU which is not used for mining. When I start NiceHashLegacy, it displays a modal dialog which says that one of my GPUs doesn't work:
"We have detected a video controller that is not working properly ... "
I am OK with that fact that my built-in GPU cannot mine, but this dialog breaks mining for the entire rig. 
It would be great if you make this dialog non-modal or provide the capability to exclude certain video controllers from being checked on startup.

**Comment by S74nk0** [comment]
@Alexgoon this can be disabled but I admit that it isn't clear how. You have to set **ShowDriverVersionWarning** to false in `General.json`. I assume you are using [1.9.0.23](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.0.23) and this still applies to [1.9.1.4](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.4), but we have completely remove this for the next upcoming release (**1.9.1.5**). 

The current Alpha (all 1.9.1.x versions) has a re-written core that is much more stable and various bugfixes. The Alpha mark is due to the GUI not being fully hooked with the business logic, but the *core* is a big improvement over what is currently "stable" 1.9.0.23.

But we will most likely re-write the whole GUI and remove all modal windows and make the miner responsive and flexible.

Closing issue.
