### ISSUE TITLE
1.9.1.5 Can't connect to the Internet

### ISSUE THREAD

**Issue by mrMad-Cat** [nicehash/NiceHashMiner#1578]
Tried updating to 1.9.1.5 from 1.9.1.4. NHML doesn't seem to be able to connect to internet.
Tried turning off all firewalls - no result.
Had to roll back to 1.9.1.4
![Screenshot (6)](https://user-images.githubusercontent.com/47658445/60371146-0883a200-9a01-11e9-9b1f-6801c79131fb.png)
![Screenshot (7)](https://user-images.githubusercontent.com/47658445/60371147-0883a200-9a01-11e9-84d2-00da31a01d48.png)

**Comment by shaikhmuddassir** [comment]
Same thing happening, just downloaded new version and getting same error

**Comment by erictardif** [comment]
same here on 3 different computers
2 X windows 10 1809
1 X windows server 2016

**Comment by AlexVk123** [comment]
Same here and I don't think it's version related as I've kept 0.23 and same socket exception 1015 thrown.
(can check this by enabling the debug console)
Also did a quick reinstall on another pc same thing.
Changed the internet connection to an entire new connection same thing.

One thing to mention is that the app downloads it's third party miners .. just can't access the servers (I think) to check the wallet status / do benchmarks / or mine obviously.
-this is what's shown in the console when the error message is thrown
![nicehash 1](https://user-images.githubusercontent.com/52333905/60371910-70d38300-9a03-11e9-898e-f32eea0d29eb.PNG)

-and this is what happens after choosing to continue even if no connection
![nicehash 2](https://user-images.githubusercontent.com/52333905/60371912-70d38300-9a03-11e9-8b03-17265361aed5.PNG)

Please let us know if the issue it's from the client app side or your servers etc. So we know to just wait until it is fixed instead of breaking our heads trying to find a go around.

Thanks and keep up the good work, nicehash team!

**Comment by rulezzzzz** [comment]
have the same issue at windows7  
looks as server want tls1.1 but client can tls1.2 only

**Comment by AlexVk123** [comment]
> 
> 
> have the same issue at windows7
> looks as server want tls1.1 but client can tls1.2 only

What does this mean, if I may ask, what's tls? - if you check the console says something about a handshake :)
"An error has occurred during a TLS handshake. ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The function requested is not supported" - from my printscreens

**Comment by AlexVk123** [comment]
Also changing the service location doesn't help!

(sorry I'm a noob in mining and coding so guess I'm just trying to point all the facts out maybe some of them help the most advanced of you)
However I still think they've changed something to the server side not on the client since the 1.9.0.23 version behaves the same.
Maybe they know of the issue so we should just give them time to resolve it.

**Comment by Maas1337** [comment]
same here

**Comment by AlexVk123** [comment]
Thread opened on nicehash reddit page
[https://www.reddit.com/r/NiceHash/comments/c6p0bg/no_connection/]

**Comment by JoshHiggins92** [comment]
Also not working.

I have reopened the old version that was working only moments ago, and now it is saying the same thing also. I've rebooted, tried using my mobile internet, rebooted the machines, added a firewall exception, disabled firewalls, I've also tried using a different server location, and I've tried running it on a laptop with a mobile connection just to see if the program will run. All of which are saying that there's no connection, despite them being able to connect!

Tried using NiceHashOS through my normal internet and two separate mobile connections. "No Connection want to continue?" - >.< Been unable to connect for over an hour! :(

I'm getting this issue on 1.9.0.21 to 1.9.1.5.

**Comment by Dragmeau** [comment]
Same problem here....  Older version working....

**Comment by JoshHiggins92** [comment]
I'm getting this issue on 1.9.0.21, 1.9.0.23, 1.9.1.5, and Nicehash OS. Tried different methods of connections, even ran it on a virtual machine just to see if it was all my machines playing up.
It's a connection error. Not sure how some people are getting lucky on older versions as I've tried the same things. :/

**Comment by scriptlev** [comment]
Same error here with 1.9.1.5 on windows 10. V1.9.0.23 working.

**Comment by JoshHiggins92** [comment]
Hoping the NiceHash staff aren't asleep!

**Comment by AlexVk123** [comment]
> 
> 
> I'm getting this issue on 1.9.0.21, 1.9.0.23, 1.9.1.5, and Nicehash OS. Tried different methods of connections, even ran it on a virtual machine just to see if it was all my machines playing up.
> It's a connection error. Not sure how some people are getting lucky on older versions as I've tried the same things. :/

Weird thing .... seems the versions that it works on it's random - mine works fine on 1.9.0.21 so back to mining on that until this gets resolved

PS: also most of the people have done a reset after updating to the new version, I accidentally turned off the wall socket before I managed to update and the issued first appeard on the old version (1.9.0.23) immediately after the restart. 

PS: **### I confirm version 1.9.0.21 is stable** (checked the wallet statistics as well - the client is communicating with the server so it's up). You can copy the benchmarks over to the .0.21 version and start mining there took me 2 mins to get transition so this is the solution for me ... for the moment at least

**Comment by erictardif** [comment]
it now works on my side not sure why.
I have tested many things, but now I am running without any registry tweaks and it connects

**Comment by AlexVk123** [comment]
> 
> 
> it now works on my side not sure why.
> I have tested many things, but now I am running without any registry tweaks and it connects

Yep confirmed here as well 1.9.1.15 works for me as well... will stick to the 0.21 till things are confirmed in the morning by the community.

**Comment by slanckma** [comment]
Reddit comment from nicehash. Was a problem on the server side. Works ok for me now (1.9.1.5)

**Comment by mrMad-Cat** [comment]
Yep, confirm, now all is working. Definitely server side problem. I wonder how are they missed this in QA )))

**Comment by muratia** [comment]
Still not connecting
