### ISSUE TITLE
Feature request: please re-add Xmrig miner

### ISSUE THREAD

**Issue by jwesolo** [nicehash/NiceHashMiner#1599]
Hello,

I sometimes prefer this miner to Xmr-Stak and have had to run it outside of Nicehash since it has been removed. I'm not sure why it was removed but I'd love to see it re-added.

Thanks!

**Comment by Nicheuji** [comment]
+1

**Comment by S74nk0** [comment]
We will add a miner plugin and you will be able to install it. 
![image](https://user-images.githubusercontent.com/1517233/60495975-29265300-9cb2-11e9-82c7-0a96117a2dfb.png)

Keep issue open until miner is implemented.

**Comment by grichter** [comment]
Xmr-stak and claymore are both unable to even work on my older hd/r7/r9 hardware, however xmrig is stable outside of the nicehash client so I'll put a +1 on this.

**Comment by luc1an24** [comment]
@jwesolo @Nicheuji @grichter 
Thank you for your patience. 
XMRig for CPU's is finally implemented as miner plugin, available from Plugins menu in the NHM.
Happy mining.
XMRig for GPU's will not be implemented since it is based on xmr-stak code, which is already available in NHM.

Closing this issue, implemented.
