### ISSUE TITLE
Problems mining with AMD Vega 64

### ISSUE THREAD

**Issue by ThiagoSF7** [nicehash/NiceHashMiner#1605]
So the old version before the beta has an option on the settings that allows me to chose to make mining with amd vega 64 more profitable and i was 80% of the time mining in Crypto night now only mines in dagger hashimoto and i am facing a - 30% leass daily profitability, theres 8 benchmarks that is not capable of doing but says that is all done.

Please fix this issue ASAP.

Thank you and cheers!

**Comment by S74nk0** [comment]
@ThiagoSF7 please be specific what setting are you referring to? Are you referring to removed unprofitable algorithms? Please provide information on what nhml versions are you comparing (the current and previous one)?

**Comment by ThiagoSF7** [comment]
@S74nk0 So i have been facing a lot of issues with the latest version (v1.9.1.5)
1. Price update and global rate get freeze and you need to exit the miner and get back in again to update.
2. My AMD Vega 64 Powercolor are always crashing and restarting my rig.
3. I am getting 30% less profits
4. Out of the 15 only 8 are enable and 6 are not allowed to be benchmark, so im constantly mining Dagger and never changes to Lyra or to Crypto Night 
5 The latest v. that was good and stable was the  v1.9.0.23 and when i couldn't benchmark some algorithms i just enable settings/general/disable default optimizations and then was able to benchmark all and was a beauty, super stable, fast, reliable and profitable.

So i am changing to the v1.9.0.23 until all those issues get fixed because im losing money by the minute.

I was as clear as possible but if you have any doubts let me know.

cheers

**Comment by luc1an24** [comment]
Hi @ThiagoSF7 
1) Please check this comment: https://github.com/nicehash/NiceHashMinerLegacy/issues/1597#issuecomment-507949393 and if you are able to see that info in your log
2) This could be issue with your setup if not what algorithm are you running on which miner?
3) This is very unlikely since we are updating miners constantly for highest profits possible - if you are still sure of this could you please test again and then tell me which miner is causing lower hash rates?
4) Algorithms are disabled due to tendency of rejected shares / low profitability; What do you mean by `not allowed to be benchmark`? 
5) The new 1.9.1.5 version is being actively developed and therefore should be more stable. If you know of any bugs please tell me so we can investigate them.

Thank you for your contribution!

**Comment by ThiagoSF7** [comment]
@S74nk0 So i am facing the same problems that i explain before, low profitability, unstable hash rate, not all Algos bench marked, etc.

I download the old version again and and is all good now, i will not use the latest version until all the problems, bugs and issues are fixed.

But thank you anyway for trying to help.

Cheers

**Comment by S74nk0** [comment]
@ThiagoSF7 provide logs for both versions please and we will examine them and try to resolve the issues you are experiencing.

**Comment by ThiagoSF7** [comment]
How can i send you the logs?
But i already solved my problem, i just down grade to v1.9.0.23 and now everything is perfect, no mBTC/day freeze, no crashes and 30% more profits. :)

**Comment by S74nk0** [comment]
Problem reported as solved by user. Solved by downgrading to v1.9.0.23
