### ISSUE TITLE
1.9.2.6 RX470/570 Cards no longer work with Lyra2REv3

### ISSUE THREAD

**Issue by manicmisfit** [nicehash/NiceHashMiner#1618]
1.9.0.23 and 1.9.1.5 Lyra2REv3 works with my RX470/570 Cards. Although 1.9.1.5 has a much lower BTC/Day rate. 1.9.2.6 just says error when i start the miner set on Lyra2REv3. I bench marked Lyra2REv3 again and it completed and turned green, but in the bench mark window, the Ratio BTC column it shows 0, and in the BTC/Day Column it shows NA. 

Also, no matter what i'm mining, the BTC/Day stays at 0.

**Comment by jwesolo** [comment]
I think 1.9.2.6 is for the new platform only...that's the only thing they said about it on the download page. I also get zero income with it. They said that mining on the new platform will start maybe 6 hours from when I post this comment (if I did my time zones right), so maybe try again with new version then. I have also found that 1.9.0.23 gives me higher profit than 1.9.1.5. I assumed it was just going down as people moved orders to the new platform but when I saw this issue I tried the old version and, while profits are lower than they were a day ago, it's still better than 1.9.1.5.

**Comment by S74nk0** [comment]
@manicmisfit 
[1.9.2.6](https://github.com/nicehash/NiceHashMiner/releases/tag/1.9.2.6) is the client for the new platform.

Lyra2REv3 has no orders currently and this is why it isn't mining it.
Lyra2REv3 and most other algorithms are bench-marked while mining and there are no orders it will not benchmark the algorithms. We will be fixing this https://github.com/nicehash/NiceHashMiner/issues/1524#issuecomment-506732596 so we can have better more deterministic benchmarks.

0 paying is because the new mining platform is not active yet. You are getting payed and the balance is visible on the old platform after the switch is done your balance will be visible on the new platform.

@jwesolo 

> 1.9.0.23 gives me higher profit than 1.9.1.5.

This is a false positive and this is related to the online benchmarks. This means that your benchmarks will vary depending on the order. As mentioned before we are working on a solution to have deterministic benchmarks https://github.com/nicehash/NiceHashMiner/issues/1524#issuecomment-506732596.

**Comment by manicmisfit** [comment]
I think i understand how it all works now. I did have my miners pointed to the new platform using the new address with 1.9.2.6. I'll wait for the transition to complete.
Thank you.
