### ISSUE TITLE
About the Profitability calculator 

### ISSUE THREAD

**Issue by liranscu** [nicehash/NiceHashMiner#162]
u see, i have three 1080ti cards(evga) and two 1070 cards(asus), the Profitability calculator told me i can earn "You could be making 145.80 USD/month with NiceHash for one 1080ti ,and 84.91usd/month for one 1070", the total is 605usd/month,i really want to knwo its true of not ,because my card working more than two days ,the website writes ,i can earn just 440usd/month ,so big diffferent. 
PS. i know the Profitability calculator is the theoretically.

**Comment by drkskwlkr** [comment]
Dude, please stop opening issues that have nothing to do with the software.

This place is reserved for feedback regarding NiceHash Miner Legacy and nothing else. The place is noisy as it is without having to go through totally unrelated newbie questions.

Every time somebody opens a non-existent 'issue' to ask something unrelated to anything, several people who work on the software get notified and have to stop doing what they are doing (improving NiceHash for the benefit of the community, usually) to go & check what is happening.

For general questions, go to [https://www.reddit.com/r/NiceHash/](https://www.reddit.com/r/NiceHash/). Please be respectful of other people's time.

**Comment by liranscu** [comment]
@drkskwlkr I can write what i want and where i like ,its not ur bussiness,thank u ,dont be so stupid

**Comment by liranscu** [comment]
@drkskwlkr  https://www.reddit.com/r/NiceHash/ this website is for NHM ,not for NHML, open ur eyes

**Comment by DillonN** [comment]
@liranscu The profitability calculator can tell you profitability based on past trends, and unless you check with the button in NHML it will give you projections for a card in general (your 1080 Ti may not be as powerful as the average). The miner stats page shows projections based on the last couple of hours and can be completely different than trends from the last couple of weeks

Closing this since it is not strictly relevant to NHML
