### ISSUE TITLE
Please add MTP mining on nVidia and AMD

### ISSUE THREAD

**Issue by electricdelicate** [nicehash/NiceHashMiner#1623]
Thank you!

**Comment by S74nk0** [comment]
@electricdelicate I am assuming that you are referring to 1.9.2.6 that runs on the new platform. 

MTP is not supported on the new platform and therefore we have filtered it out. If you still wish to support it open `nhm_path\\internals\\SupportedAlgorithmsFilter.json` and remove the filter (delete`[41]` from file). 

You will enable MTP but it will not mine on new platform since MTP is not supported so... do as you see fit.

For future issue please be specific about client version numbering.

Reopen issue if client is on the old platform any client version bellow 1.9.2.x
