### ISSUE TITLE
1.9.2.6 not properly detecting/initializing cards. Mixes them up.

### ISSUE THREAD

**Issue by tommyprevatt** [nicehash/NiceHashMiner#1625]
This issue is on 1.9.1.6 and 1.9.2.6
Windows 10
GPUs: 1x MSI Vega 56 and 1x MSI R9 380(Tonga)

When benchmarking, they benchmark the opposite card. And some mining software won't launch, such as TeamRedMiner, since it only supports the Vega and not the Tonga.
[log.txt](https://github.com/nicehash/NiceHashMiner/files/3362734/log.txt)

**Comment by S74nk0** [comment]
@tommyprevatt Copy and replace the file `TeamRedMiner.dll` from 1.9.1.5 to 1.9.1.6 or 1.9.2.6 **and report back if this works for you**. 

We have changed TeamRedMiner to use `--bus_reorder`. 
If you can please run TeamRedMiner with these two options:
  - `--list_devices --bus_reorder`
  - `--list_devices`

and post the results here. We didn't encounter any issues with this. Maybe the device indexing parser is broken now.

**Comment by luc1an24** [comment]
Hi @tommyprevatt 
I have made a fix in TeamRedMiner plugin and I would be happy if you could try it.
Please replace following files in your NHM folder: `TeamRedMiner.dll` and `TeamRedMiner.pdb` with the files in zip [TeamRedMiner.zip](https://github.com/nicehash/NiceHashMiner/files/3362973/TeamRedMiner.zip)
Also this fix brings updated extra launch parameters so try them too.
Please close issue if the problem is fixed, otherwise inform us.
