### ISSUE TITLE
1.9.2.6 No WorkerName, USD/Day, Balance, mBTC 

### ISSUE THREAD

**Issue by vasyapupkin1** [nicehash/NiceHashMiner#1630]
Try both btc mining addreses: on old platform and new platform.
It seems like on new platform it were visible, but then gone

![001](https://user-images.githubusercontent.com/29598026/60739364-54d36280-9f6a-11e9-94f1-d8e86adc84f0.jpg)
![002](https://user-images.githubusercontent.com/29598026/60739365-54d36280-9f6a-11e9-9497-20521962b336.jpg)
![003](https://user-images.githubusercontent.com/29598026/60739548-0377a300-9f6b-11e9-8ba5-0652cbb84a15.jpg)

**Comment by peteycrack420** [comment]
me either  am still using my old bitcoin address but it shows up in the new dashboard online   not sure if we are suppose to use the new address on the new dashboard

**Comment by Maas1337** [comment]
mee too

**Comment by rkresha** [comment]
> me either am still using my old bitcoin address but it shows up in the new dashboard online not sure if we are suppose to use the new address on the new dashboard

**Disclosure:** I am not affiliated with the project or team, just was thinking through the same question a couple of hours ago. 
Based on the page [here](https://www.nicehash.com/news/important-transition-to-a-new-nicehash-platform) it says 
> Your wallet funds from the current platform will be transferred to your new wallet (into your personal organization) on the new platform at the end of the transition period.

So technically both are still valid and it must know the mappings between old and new because using the old wallet address it shows on the new platform and also using the new wallet address shows on the new platform. That being said, I'd suggest just switching over to the new address. Just my 2 cents

**Comment by jwesolo** [comment]
Just look at the old wallet...the info will be there. You can mine using either the old or new address; both are reflected/combined if you look on the old stats page.

EDIT: This is apparently the opposite of the above comment. My new page shows no stats; only the old one does. I believe that it is combining your 2 wallets since they have the same email address; remember they said as long as you use the same email it would transfer at the end.

**Comment by QAlexx** [comment]
Hello!
After upgrading from version 1.9.1.5 to version 1.9.2.6, several bugs were immediately detected.

**Firstly**, the current profitability in dollars, the total balance of the internal wallet in both dollars and bitcoins is not displayed. (**Figure 1, position 2**)

**Secondly**, the current profitability in bitcoins is clearly overestimated, with the latest version of the miners, the benchmark spent again. (**Figure 1, position 1**)
**_Figure 1_**
![1-0_NHM_main_red](https://user-images.githubusercontent.com/52649009/60795147-f89c5880-a18c-11e9-9b22-30c5bf913f87.jpg)

**Thirdly**, the statistics on the site do not display workers. By reviewing the startup parameters of the miner using the ProcessExplorer program, it was revealed that some incomprehensible character set is transferred to the startup parameters of the miner as a worker. (**Figure 2 and 3, position 3 and 4**).
**_Figure 2_**
![2-0_Process_window_red](https://user-images.githubusercontent.com/52649009/60795219-1964ae00-a18d-11e9-8b72-26ac6d6352e7.jpg)
**_Figure 3_**
![2-1_Process_window_red](https://user-images.githubusercontent.com/52649009/60795227-1cf83500-a18d-11e9-8c20-f301a3e18c0a.jpg)

These bugs appear in two different rigs.
I ask others to confirm the presence of these bugs.

**Comment by seso1129** [comment]
You have to enter your wallet address from new platform directly in the 1.9.2.6 .
