### ISSUE TITLE
1.9.2.6 / 1.9.1.6 updates for ClaymoreDual14 

### ISSUE THREAD

**Issue by vasyapupkin1** [nicehash/NiceHashMiner#1645]
Need to add -cvddc -mvddc in MinerOptionsPackage.json
 [#1642](https://github.com/nicehash/NiceHashMiner/pull/1642)
[#1643](https://github.com/nicehash/NiceHashMiner/pull/1643)
Need to remove "-wd 0" from Update ClaymoreBase.cs
[#1644](https://github.com/nicehash/NiceHashMiner/pull/1644)

**Comment by luc1an24** [comment]
Hi @vasyapupkin1 
Thank you for reaching out. We will add these extra launch parameter options in the next update of NHM or plugin.

The `-wd 0` must be used since miner watchdog can interfere with our and create zombie processes and this is behaviour we don't want.

Will close this issue on the next release.
