### ISSUE TITLE
1.9.2.6 & 1.9.2.7 Bad worker name, no balance, no mBTC & $ /day, no BTC&GH/day

### ISSUE THREAD

**Issue by QAlexx** [nicehash/NiceHashMiner#1651]
Hello!

NHM 1.9.2.7 has been released. But the problems described in the [issues #1630](https://github.com/nicehash/NiceHashMiner/issues/1630) are relevant. I created a new request, as it relates to the new version of the program.

The following bugs were found:
1) The current profitability in dollars, the total balance of the internal wallet in both dollars and bitcoins is not displayed. (**Figure 1, position 1 and 2**)
![1_Main_window_red](https://user-images.githubusercontent.com/52649009/60862096-66548d00-a23e-11e9-8ae7-b92af3c4fef6.jpg)

2) The name of the worker, which is transferred to the miner when it starts, still consists of a set of characters that do not reflect the real name of the worker specified in the program. (**Figure 2, position 3**)
![2_Process_window_red](https://user-images.githubusercontent.com/52649009/60862107-6fddf500-a23e-11e9-8937-aa2cdf841299.jpg)

3) In the benchmark window for most algorithms zero cost is displayed (**Figure 3 and 4, position 4 and 5**).
![3-1_Benchmark_red](https://user-images.githubusercontent.com/52649009/60862115-753b3f80-a23e-11e9-9dd4-703cbf622872.jpg)
![3-2_Benchmark_red](https://user-images.githubusercontent.com/52649009/60862126-79675d00-a23e-11e9-87d3-25336196737f.jpg)

Operating system: Windows 7 x64
I attach the **log file** for analysis, maybe it can reveal the cause of these bugs.
[log_red.txt](https://github.com/nicehash/NiceHashMiner/files/3371350/log_red.txt)

I hope for a quick resolution of these problems, as they prevent the use of the new version of the program. I had to roll back to version 1.9.1.4.

**Comment by luc1an24** [comment]
Hi @QAlexx 
Thank you for reaching out.
The 1.9.2.x versions are intended to be used in the new platform (new.nicehash.com). 
Since transition of miners to the new platform was unsuccessful it would be wise to stay on the old platform for a while, until we fix all issues.
The miners for the old platform are of 1.9.1.x lineage.
Also here is the [link](https://github.com/nicehash/NiceHashMiner/releases/tag/1.9.1.7) to the new miner for old platform.
With the 1.9.1.x versions you will have no stated problems.
Closing issue, wrong platform mining.

**Comment by S74nk0** [comment]
@QAlexx all points you have written are not bugs. This is just how the new platform works. We are working on improving new platform issues
