### ISSUE TITLE
Hardware-specific profitability thresholds don't work 1.9.2.7, only global works currently

### ISSUE THREAD

**Issue by joseortiz3** [nicehash/NiceHashMiner#1658]
The hardware-specific profitability thresholds (minimum profits) don't work. For instance, setting a very high profit requirement for CPU does not stop CPU mining.

For instance, here is my CPU profitability threshold settings (minimum $99 a day for testing)

![image](https://user-images.githubusercontent.com/18585219/60939400-59f72100-a28c-11e9-8f5c-8d1828db7b64.png)

And here it is mining despite the above settings (it ignores them):

![image](https://user-images.githubusercontent.com/18585219/60939521-d853c300-a28c-11e9-97ed-f972c2a791a7.png)

Here is the JSON for the CPU settings:

```json
{
  "DeviceUUID": "CPU-368fd2af-7032-5123-a137-08480697e75e",
  "DeviceName": "(2x)Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz",
  "Enabled": true,
  "MinimumProfit": 99.0,
  "PowerTarget": 0,
  "PowerLevel": -2,
  "PluginAlgorithmSettings": [
    {
      "Name": "XmrStak",
      "PluginUUID": "XmrStak",
      "PluginVersion": "1.3",
      "AlgorithmIDs": "CryptoNightR",
      "Speeds": [
        809.8
      ],
      "ExtraLaunchParameters": "",
      "Enabled": true,
      "PowerUsage": 220.0
    }
  ]
}
```

Here are the global (general) settings

```json
{
  "ConfigFileVersion": {
    "Major": 1,
    "Minor": 9,
    "Build": 1,
    "Revision": 7,
    "MajorRevision": 0,
    "MinorRevision": 7
  },
  "hwid": "BFEBFBFF000306E4",
  "agreedWithTOS": 4,
  "SwitchSmaTimeChangeSeconds": {
    "Lower": 34,
    "Upper": 55
  },
  "SwitchSmaTicksStable": {
    "Lower": 2,
    "Upper": 3
  },
  "SwitchSmaTicksUnstable": {
    "Lower": 5,
    "Upper": 13
  },
  "MainFormSize": "1000, 494",
  "Language": "en",
  "DisplayCurrency": "USD",
  "DebugConsole": false,
  "BitcoinAddress": "3HPc1tBQ6qSQwJWUufoz1VsFvYVnmdjf1J",
  "WorkerName": "DoubleThought",
  "TimeUnit": 1,
  "ServiceLocation": 0,
  "AutoStartMining": true,
  "HideMiningWindows": true,
  "MinimizeMiningWindows": true,
  "MinimizeToTray": true,
  "SwitchProfitabilityThreshold": 0.05,
  "MinerAPIQueryInterval": 5,
  "MinerRestartDelayMS": 500,
  "AutoScaleBTCValues": true,
  "StartMiningWhenIdle": true,
  "IdleCheckType": 0,
  "MinIdleSeconds": 500,
  "LogToFile": true,
  "LogMaxFileSize": 1048576,
  "ShowDriverVersionWarning": true,
  "DisableWindowsErrorReporting": true,
  "ShowInternetConnectionWarning": true,
  "NVIDIAP0State": false,
  "ApiBindPortPoolStart": 4000,
  "MinimumProfit": 0.7,
  "MineRegardlessOfProfit": false,
  "IdleWhenNoInternetAccess": true,
  "RunScriptOnCUDA_GPU_Lost": false,
  "AllowMultipleInstances": false,
  "UseIFTTT": false,
  "IFTTTKey": "",
  "Use3rdPartyMiners": 2,
  "CoolDownCheckEnabled": true,
  "KwhPrice": 0.12,
  "UseSmaCache": true,
  "ShowPowerColumns": false,
  "ShowDiagColumns": true,
  "UseEthlargement": false,
  "RigGroup": "",
  "RunAtStartup": true,
  "GUIWindowsAlwaysOnTop": false,
  "DisableDeviceStatusMonitoring": false,
  "DisableDevicePowerModeSettings": true,
  "ShowGPUPCIeBusIDs": false
}
```
only the general setting's `MinimumProfit` works.

**Comment by joseortiz3** [comment]
Edit: Nevermind about the below, I was mistaken:

_ALSO, the profitability threshold does not currently take into account electricity costs, from what I can tell. Please verify that electricity costs are subtracted before comparing to the threshold. This should be simple to verify and fix._

**Comment by S74nk0** [comment]
@joseortiz3 This responding to the first post this issue is not implemented (the code stayed after the merge). @luc1an24 marked it as a wrongly as a *Bug*. We will implement this when in one of the next releases. 

Now regarding the second post about accounting electricity costs, this is accounted only if you turn off `Mine Regardless Of Profit`. You can set that to false put Electricity cost and set the minimum profit value (this can now also be negative as some users requested this).

**Comment by joseortiz3** [comment]
@S74nk0 I was mistaken, electricity costs are subtracted, it works. 

However there are some issues when profitability drops below the global threshold including electricity costs: **it takes a _very_ long time before the client stops mining.** In fact, I have never seen the client actually stop mining. My profitability threshold right now is `$0.60`, and its been mining for the last hour at `$0.20-$0.40`.

About being not implemented, would be nice to add a hover-over tooltip or textbox saying the feature isn't implemented yet.

**Comment by S74nk0** [comment]
@joseortiz3 The code for unimplemented feature shouldn't be there in the first place this is a mistake on our part.

The profitability threshold is somewhat a tricky feature. It doesn't take into account the actual active mining report it takes the estimate based on benchmarked speeds. 

The reason it doesn't take the API into account is because it needs to start the miners first and wait for the speeds to stabilize and second the speeds might vary depending on the order. So at the moment this only takes into account estimates based on benchmarked speeds and this is not ideal. I think that this feature needs to be improved or explained as it currently mostly confuses people.

**Comment by joseortiz3** [comment]
@S74nk0 Great info, thanks so much for the replies (and your work!).

So NHML uses the benchmarked hashrates, but are the market prices dynamic and updated in realtime? For instance if the market prices drop, will NHML stop mining if it's already mining? And conversely, if market prices rise, will NHML start mining?

From the behavior I see, profit thresholds are **completely static**, hashrates and market prices are determined at benchmark time and remain the same forever. Please correct me if I'm wrong.
