### ISSUE TITLE
Comments and requests for a version 1.9.2.10

### ISSUE THREAD

**Issue by EVGENY1777** [nicehash/NiceHashMiner#1697]
Hello! 
My configuration - WIN 10 x64, AMD 390, 474, 588. 
Drivers - 18.6.1

-  On ALL cards on the algorithm DH+Keccak Claymore 14.7 - 10-12 Mh. 
   I have the feeling that the card that is on DH+Keccak working in the "Graphics" and not 
   "Computing". 
   I use "AMD-Compute-Switcher". All cards are in Computer mode. 
   DH+Blake & DH+Decred - hashrate as expected, 29-32 Mh. 
   And it is noticed from earlier versions NHML and continues in version 1.9.2.10.

- NanoMiner - on ALL algorithms and ALL locations - "Invalid BTC address" 

 - Please include in the Assembly for CPU Xmrig (I have FX-8300, hashrate on 
   xmr-stak less by 10%, compare with earlier versions of NHML). 

With respect.

**Comment by 1434393364** [comment]
为什么我不能连接矿机打开矿机状态不显示我矿机在线的

**Comment by S74nk0** [comment]
@EVGENY1777 

xmrig is in the works. 

We will investigate Claymore 14.7 

Update NanoMiner  via the plugins form. You will have unmanaged rig in the dashboard when mining with NanoMiner because it doesn't support our RigID (but you will be able to mine with it). unmanaged rig means you will not be able to start/stop it via the web dashboard. We will resolve NanoMiner unmanaged rig with the NanoMiner developer or on our backend.
