### ISSUE TITLE
v1.9.2.11 How do I update miners? JSON file is overwritten at startup.

### ISSUE THREAD

**Issue by jwesolo** [nicehash/NiceHashMiner#1713]
Hello!

I am trying to update several of the individual miners between NHM releases.

In the past, one could simply replace the folder containing the miners. I have tried that now and NHM simply redownloads the version correlating to the NHM release.

I then tried editing the miner-plugins/plugin-name/internals/MinersBinsUrlsSettings.json file with updated URLs. Upon restart, these files were overwritten by NHM.

Upon a cursory examination of the code, it appears that the miner source URLs are hard-coded into NHM, defeating the purpose of the config files. Is this feature still being implemented? How do I update my miners in the mean time?

Many thanks!

**Comment by luc1an24** [comment]
Hi @jwesolo 
Thank you for reaching out.
This is indeed our mistake. We will fix it as soon as possible.
Thank you once again!
Keep issue open until this is fixed.

**Comment by luc1an24** [comment]
For now workaround would be to change `miner_plugins/plugin-name/internals/MinersBinsUrlsSettings.json` url. Don't forget to change `use_user_settings` to true.
After that delete bins folder.
If the NHM will ask you to download missing files just click `no` since the file check is set for old packet and some files may be missing in the new zip.
