### ISSUE TITLE
XMR-Stak benchmark error

### ISSUE THREAD

**Issue by N8Thrasher** [nicehash/NiceHashMiner#1745]
running the latest version, cryptonight-r benchmark error on xmrstak but ok with other miner. (TeamRedMiner and nanoMiner)

Win 764
RX3804GB and Rx4804GB
![xmr_380](https://user-images.githubusercontent.com/24593637/63463857-b68e5400-c466-11e9-9f45-d4f9530ac04e.PNG)
[log.txt](https://github.com/nicehash/NiceHashMiner/files/3527075/log.txt)

**Comment by grichter** [comment]
I'm finding that the kernel support varies across the miners enough that you actually need 3 to 6 miners, even if they're derived from a common code base, in order to run a wide variety of cards and keep them stable.

Not everyone has a properly built rig of 19 perfectly matched gtx 1080 cards... :p
