### ISSUE TITLE
Incorrect (or lost) balance

### ISSUE THREAD

**Issue by LeaTex** [nicehash/NiceHashMiner#1794]
I was mining and I had about 0.9 mBTC (aprox 10 USD).
Now I open NiceHashMiner and it shows only 0.002 mBTC, and if I look the stats it shows 0.66309 mBTC.

Why? Where are my balance? Why it is different in Miner and Stats?

![nicehashminer](https://user-images.githubusercontent.com/6115573/64747410-5464c400-d4e5-11e9-9d38-f8f0fd218d05.png)

https://www.nicehash.com/my/miner/38fNZJNf8upc5WFpQ4FKCMmtxfzpN37PS7

![nicehashminer_stats](https://user-images.githubusercontent.com/6115573/64747411-5464c400-d4e5-11e9-8f90-ed5939bd2c5a.png)

**Comment by yearight** [comment]
Me too.
Mines an external address, but the nicehash page doesn't even load...shows an error.
I've turned my miners off.

**Comment by luc1an24** [comment]
Hi @LeaTex
The label you are looking at shows unpaid balance. Since you were probably just paid it went to 0, but was added to your total balance that can be seen in your web [Dashboard](https://www.nicehash.com/my/dashboard).

@yearight could you please contact our support team regarding this issue?
We had some API down-time but mining was unaffected. 
If you are still unable to see your balance please write to: support@nicehash.com

**Comment by LeaTex** [comment]
@luc1an24 I don't have a personal dashboard because I'm using NiceHash with my own BTC address.

As I said, I had around 0.9 mBTC and I need 1.0 mBTC to be paid, so I wasn't paid.
If you see the transactions on my address, last movement was on Nov-2018
https://www.blockchain.com/es/btc/address/38fNZJNf8upc5WFpQ4FKCMmtxfzpN37PS7

Anyway, why I see different balance in the web (0.66) and the miner (0.002)?

**Comment by luc1an24** [comment]
@LeaTex 
Could you please contact our support team so they can check transactions on your account?
Please write an email to: support@nicehash.com
They should be able to find out what is happening with your balance.
