### ISSUE TITLE
NiceHash Miner v1.9.2.15 - miner launch parameters disappear!!!!!!!!

### ISSUE THREAD

**Issue by Sfinx-vrn** [nicehash/NiceHashMiner#1819]
Where did the window for **entering miner launch parameters** disappear? This was important for Claymore, for example - it was possible to set the voltage, temperature control, etc.

**Comment by jwesolo** [comment]
Note that the algorithm settings were moved to the benchmark screen. The extra launch parameters are now gone though, as you say. You will need to go into the JSON config files for each miner and configure them manually (miner_plugins\miner plugin UUID\internals\MinerOptionsPackage.json). Don't forget to set "use_user_settings" to true. I cannot figure out how to set the parameters any other way than modifying the default values and setting "ignore_default_value_options" to false. Note that once you set "ignore_default_value_options" to false, you will need to set *every single parameter* to something useful...I do not know how to set one parameter value and leave the others alone. Does anyone have suggestions on this? I am hoping that the next step they take is making forms in the app based on those config files so users can have easy GUI access to the settings.

EDIT: markdown/formatting got screwed up

**Comment by S74nk0** [comment]
@Sfinx-vrn This seems to be a scaling issue the *Extra launch parameters* are technically still there but practically inaccessible due to scaling. I have re-upload the packages with the GUI Forms fix, other dependencies are not be touched. So re-download the package and this should be fixed

@jwesolo Regarding the ELP params and MinerOptionsPackage this is not how it should be used. 
So for each device algorithms settings in the configs there is:
```
{
      "Name": "GMinerCuda9.0+",
      "PluginUUID": "1b7019d0-7237-11e9-b20c-f9f12eb6d835",
      "PluginVersion": "3.0",
      "AlgorithmIDs": "GrinCuckarood29",
      "Speeds": [
        0.0
      ],
      "ExtraLaunchParameters": "",
      "Enabled": true,
      "PowerUsage": 0.0
    },
```
So here each algorithm has **"ExtraLaunchParameters": "",** and this is where the user sets parameters.

The **MinerOptionsPackage.json** is used for [defining supported flags ](https://github.com/nicehash/NiceHashMiner/blob/master/doc/Plugins/InternalSettings/ExtraLaunchParameters.md#mineroptionspackage-file). This defines what flags will bi accepted by the parser. We will write up an article regarding this and improve the docs since this is a common misconception regarding this file.
