### ISSUE TITLE
v3.0.0.4 About those notifications...

### ISSUE THREAD

**Issue by jwesolo** [nicehash/NiceHashMiner#1966]
The new notification tab has a couple of issues.

Slightly off-topic, I did notice that the current software version is shown here ( see #1952 ), but it should be on the dashboard or devices tab, which is up 99% of the time NHM is running. At-a-glance is what I am looking for.

The Windows Defender exception notification...I have an exception for the parent directory but apparently NHM doesn't see this. Would it be possible to iterate up the hierarchy to more robustly determine if an exception exists?

Large pages for RandomX. Locking pages in memory *is* enabled (and XMRig is using large pages) but this notification keeps appearing. Also, looking at the instructions on the website, is the Group Policy Editor available in all Windows Home installations? I don't use Home so I'm not certain about this. I do know that it can be installed...perhaps instructions for this procedure would be helpful for those who have a standard installation (or, alternatively, Registry Editor instructions).

Thanks!

**Comment by S74nk0** [comment]
@jwesolo Some notifications have an option "Do not show again". 

![image](https://user-images.githubusercontent.com/1517233/73748801-7bed4f00-475a-11ea-9996-37b650fcb17c.png)

Show more info tick the checkbox and Remove. You will not see that notification again.

I will close this issue.

**Comment by jwesolo** [comment]
With respect, my issue report had nothing to do with being unable to make the notifications go away. These notifications should not appear unless they are relevant. I also mentioned some ways to improve the written procedure to enable page locking found on your website.

Thanks!

**Comment by S74nk0** [comment]
@jwesolo Your response is very much appreciated and taken seriously. My responses are brief because one person can do only so much in a day. 

The message being shown on every startup is from my point of view and the users point of view a **BUG**. The message should be shown only when it is relevant (and not always like in this case). 

Reason I have closed this issue is because I marked this in our backlog and it will get sorted out when other more urgent tasks get resolved. I know this isn't the correct way to keep track of issues on GitHub but we have our internal issue tracking and it is easier to follow that for our team. 

Sorry if my response seemed offensive or disrespectful as this certainly was not my intention.
