### ISSUE TITLE
v 1.8.1.1 virus false positive?

### ISSUE THREAD

**Issue by Meatwad1** [nicehash/NiceHashMiner#197]
When i download the newer version, Avast shows it as a virus. When i turned off Avast, Chrome blocked it as a dangerous file....?
This is the first time I have had issues like this with NiceHash.

**Comment by EtaYorius** [comment]
Same here, Avast keeps deleting the exe everytime i try to run it... even if set the whole folder and exe as a exclude Avast will not allow it to run at all...

**Comment by dinicthis** [comment]
It's because the code is loaded with code that uses your machine to make money for them. Who do you trust more? The virus-cleaning software company, or people who stand to gain a LOT of money by providing programs that enslave your computer for their profit?

It's infected by design. If they want to prove that this is not the case, they can provide the source code and then it will be obvious. They will not provide the source code, because then their cash cow would be vulnerable.

Quit believing what you want to believe and look at the facts.

**Comment by Mystere** [comment]
@dinicthis  -  Your comment is kind of all over the place and makes no sense.  It's not even clear if you're talking about the anti-virus companies or NiceHash.  NiceHash does in fact provide the source code.

@Meatwad1 - Almost all miner programs are detected by antivirus as malware, this is because many malware applications download miner software to victims computers.  The vast majority of such people have no idea what a miner is.

The antivirus companies assume that if you are knowledgeable enough to be mining, you're knowledgeable enough to know it's a false positive.  And if you're not, then the miner is probably malware.

**Comment by EtaYorius** [comment]
Well i still can't run newer version without avast deleting the exe, no matter what i do or if set it as excluded file.

**Comment by Meatwad1** [comment]
Resolution: Uninstall Avast, run NiceHash... Get paid.

Thank you Mystere.

**Comment by DillonN** [comment]
NHML downloads miner programs that are often included in viruses, so this can get it flagged
