### ISSUE TITLE
3.0.0.5 crash

### ISSUE THREAD

**Issue by EvgeniyKorepov** [nicehash/NiceHashMiner#1984]
Windows 10 with last update
Now I downloaded and installed the .NET Framework 4.8
![image](https://user-images.githubusercontent.com/35364901/74529948-f88de380-4f39-11ea-8ac7-da94f1cda9dc.png)

**Comment by EvgeniyKorepov** [comment]
Huge request - write the application on Delphi, or on the Golang. A single binary file without a bunch of junk dependencies.

**Comment by S74nk0** [comment]
@EvgeniyKorepov Well this is quite a request 😄. Golang is a great language I agree with you on that one. 
Well we are kinda stuck with the project stack since its inception. It would be a huge undertaking to re-write it just to gain the single instance no dependencies binary (that would be amazing for us and the users). 
We will probably attempt to migrate the project to .NET Core since that can give us a single package (with packaged junk dependencies) but that would not rely on any system dependencies.

**Comment by luc1an24** [comment]
Inactive thread, therefore closing it.
