### ISSUE TITLE
algorithm switch logic

### ISSUE THREAD

**Issue by votartem** [nicehash/NiceHashMiner#201]
Hello!
if you include all the available algorithms for the GPU, it automatically selects the crypt "1", if you disable all the algorithms and put only the crypt "2", the yield is higher than the crypt "1". it turns out that it automatically chooses the most profitable crypt, and comes from some other logic? or something I'm missing.

**Comment by Krolow93** [comment]
I think rebenchmarking would solve the problem for you. It sounds like the benchamark gave to low values on "2". 
If you manualy run "2" and then compare it to the value on that algorithm in settings you will se if my guess is correct. If so you can then manualy enter the correct value and it will once again go for the most profitable algo.

I have seen a few friends with similar issues when they did not run the benchmark in "precise" mode. Not pointing out was that in their cases the difference was marginal.

A guide on how to manualy benchmark from the Wiki
[https://github.com/NiceHash/NiceHashMinerLegacy/wiki/Getting-started#-manual-benchmarking](url)

**Comment by streaml1ne555** [comment]
One other thing to note here if you do rebench. Do not touch the system while it's benchmarking and only run nicehash, close other apps, browsers, etc.  Even going so far as not touching the mouse and turning off the monitors can help bench results. The point is you want to do that during all benchmarks so that you get consistent results and thus improve your profitability checks.

**Comment by DillonN** [comment]
It sounds like this is an issue with inaccurate benchmarks - benchmarks are not perfect and in these situations manual benchmarking can help
