### ISSUE TITLE
WINDOWS 10 AV deletes the exe same goes for chrome

### ISSUE THREAD

**Issue by kolet** [nicehash/NiceHashMiner#2015]
Windows 10 AV goes all over the place, deleted right away same for google chrome, deleted the file before it even got to the pc.

chrome didnt even let me to discard/keep it.

**Comment by kolet** [comment]
why not just signing the exe with the right certificates ?

**Comment by kramarenkop** [comment]
Windows 10 AV идет по всему месту, сразу же удален же для google chrome, удалил файл, прежде чем он даже попал на ПК.

хром даже не позволил мне выбросить / сохранить его.

**Comment by kramarenkop** [comment]
почему бы просто не подписать exe с правильными сертификатами ?

**Comment by luc1an24** [comment]
Hi
Since we are packing 3rd party miners we are unable to guarantee for their code, therefore we are not signing it.
If you still experience issue, please check these 2 links about restricting AV to delete NHM:
https://www.nicehash.com/blog/post/how-to-add-nicehash-miner-folder-to-windows-defender-exclusion%3F
https://www.nicehash.com/support/mining-help/nicehash-miner/my-broswer-antivirus-software-reports-nhm-as-a-virus
Have a nice day!
