### ISSUE TITLE
No supported devices found

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner#2038]
I am totally new to crypto mining.
I downloaded  the newest version of NiceHash
I am already mining on my laptop, and now want to also use my pc to help mine.
When starting NiceHash it says i should either " login " or " enter bitcoin adress manually "
When i press login, the pop up disappears and restarts itself. When i press enter bitcoin adress manually it says no supported devices found.

I have a Intel(R) Pentium(R) CPU  G3240 @ 3.10GHz prosessor

What must i do to so that my pc can find the device?

**Comment by luc1an24** [comment]
Hi @bitminer777 
Thank you for reaching out.
We only support CPU devices that support AES (Advanced Encryption Standard instructions), which your CPU does not.

Do you have any kind of antivirus software that could prevent you from visiting our webpage since login redirects to NH online page?

If you have any questions, feel free to reach out!
Have a nice day

**Comment by luc1an24** [comment]
Inactive thread therefore closing issue.
