### ISSUE TITLE
GPU (C) Website

### ISSUE THREAD

**Issue by ilkanaydin** [nicehash/NiceHashMiner#204]
It would be great if you added the GPU health (C)  to the website in order to view it.

**Comment by drkskwlkr** [comment]
@ilkanaydin GPU temp and load are reported for all workers that use NiceHash wallets since NHML version 1.8.0. According to the dev team, such ability will not be enabled for users mining to external wallets (if you want to know their reasoning, look it up among the closed issues from about a week ago).

See how reporting works at NiceHash website:
[http://i.imgur.com/onoNpLq.jpg](http://i.imgur.com/onoNpLq.jpg)

Is that what you're asking for?

**Comment by DillonN** [comment]
@ilkanaydin you can read more about rig stats monitoring [on the wiki](https://github.com/nicehash/NiceHashMinerLegacy/wiki/Rig-Stats-Monitoring)

**Comment by ilkanaydin** [comment]
@drkskwlkr  ı cant see picture

**Comment by ilkanaydin** [comment]
@DillonN , @drkskwlkr i see temp thank you :) 👍
