### ISSUE TITLE
profit big issue>!?

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner#207]
sup
in Program front says that i`ll earn between 8-9.5 USD each day my unpaid blance on 3:51 AM was 0.0122 BTC = 49.0474  USD Now it`s 3:13 PM my unpaid blance 0.0131 BTC= 51.8968 USD

So that mean i earned in 12H=half aday 0.0009BTC = 2.8494USD

So wtf is that.!!???????????????

**Comment by rpglord** [comment]
You don't earn USD at all, you earn bitcoin, and its price is more volatile then USD so it varies from day to day even from hour to hour
If you usually earn around 0.0009BTC in 12 hours, then nothing is wrong, USD price is not relavant

**Comment by drkskwlkr** [comment]
> So wtf is that.!!???????????????

@SolimanEvo: how about you mind your language, first and foremost? What you are asking is (1) stupid (because it suggests you have no idea how NiceHash works) and (2) completely unrelated to NiceHash Mining Legacy. So at least be polite if you expect answers.

The answer to your question is that price calculators give profit _estimates_ based on _past performance_. It does not promise future fixed income.

Hash power sellers are paid based on what buyers are willing to pay for the numerous algorithms offered by NiceHash. When bids are low, we are paid less. Your results have little to do with BTC/USD rate volatility although @rpglord is correct to point out that the only important number is the daily BTC profit and USD rate is irrelevant (in case you know what you are doing, anyway).

Now be kind and close your own ticket. Thank you.

**Comment by ghost** [comment]
Thx you guys for answers Rpglord you made it Clear for me bro :)

drkskwlkr first of all i`m not going to close my own ticket i hope every one share his Thoughts up here .... you misunderstood what i`m asking about 

any way WTF is normal thing in our Area i don`t mean to detraction or abused any one here if you think that i said my words just for what you said i think you totally wrong but any way thank you for your explanation it give me alot of info 

once more don`t be mad at me dude  i`m just Amateur ^_^ and i`m asking for help and more info :)

**Comment by ChriscomIT** [comment]
@SolimanEvo Yeah but what maybe you don't understand is that's the wrong place to ask such questions (especially noob question). This platform and repo are intended for bugs and development of NHML. With these questions, you distracting the developers and helping members in a deep way. 

I am not trying to tell you what to do or not to do and it's not my intention to sound rude but this is annoying as hell. I just asking you to use Reddit, Nicehash support or any other kind of support/help forum like Nicehash facebook support instead and not Github which is not meant for such use cases. BTW there are plenty tutorials and explanations out there. As well a ton of info material on nicehash.com with exact explanations how the service and all other aspects work. I would advise you may read them before stealing others time. That's what normal ppl do, read before using a service which they don't yet know ANYTHING about (as it seems).

And please close your ticket as @rpglord did explain it to you correct and the question/issue, therefore, was solved and this issue is 100% non-relevant for NHML development or bug fixing.

Thanks in advance!!!!

pm: please fix ur English grammar, I got headaches from reading your stumblings
