### ISSUE TITLE
new version queries

### ISSUE THREAD

**Issue by jimmyhackers** [nicehash/NiceHashMiner#209]
not quite sure why but it seems a good thing.
the newest version has made my cryptonight on a 3770k nearly double its hash rate. 
has it just been optimised or something else?

also now my my gtx770 on the last version was doing 9.5Mh's but got locked down to like 6 for the past 3 days. its working fine on the newer version now though. any ideas what that was?

thumbs up anyways on the new version.
keep up the good work dudes

**Comment by adem4ik** [comment]
> the newest version has made my cryptonight on a 3770k nearly double its hash rate.
> has it just been optimised or something else?

I don't think so, more like older version didn't use your CPU fully. from my experience it may be caused by incorrect benchmarking, so NHML generated incorrect config.

I've got the similar problem after benching 1.8.1.1 using Quick type. NHML generated config with 4 threads and 2 cpus and it had around 120H/s, while previously it was 3 threads and 3 cpus (of 4) with 170 H/s. So re-benching on Standard has fixed it.
