### ISSUE TITLE
No supported devices in 3.0.3.0

### ISSUE THREAD

**Issue by heezy01** [nicehash/NiceHashMiner#2092]
my RX 580 is no longer detected, even though the log file can detect the hardware, but NHM detects ZERO devices.

[log.txt](https://github.com/nicehash/NiceHashMiner/files/4854425/log.txt)

**Comment by heezy01** [comment]
Working now after updating to the latest drivers. i originally had the crimson beta drivers installed. what changed? it was working fine in 3.0.2.0.

**Comment by S74nk0** [comment]
These issues are related to Windows drivers and/or other OpenCL.dll dependencies on the system (Intel integrated graphics, NVIDIA or AMD). 
Device detection libraries are unchanged https://github.com/nicehash/DeviceDetection/releases the AMD library wasn't changed since **Jul 22, 2019**. 

Usually these problems occur with driver setup or Windows updates when the system dependencies get changed. The system loads the wrong `*.dll`. Windows setup is beyond the application scope.
