### ISSUE TITLE
AMD RX 4x/5x series limited GMiner Algo

### ISSUE THREAD

**Issue by N8Thrasher** [nicehash/NiceHashMiner#2111]
My AMD RX 480 and 580 (both are 4GB) only have two algo (BeamV2 and Eaglesong) for GMiner plugin. NHM updated to latest 3.0.4.0 and all plugins.
![1](https://user-images.githubusercontent.com/24593637/87913384-b41deb00-ca77-11ea-964d-00e76ebbe9f5.PNG)
![2](https://user-images.githubusercontent.com/24593637/87913387-b6804500-ca77-11ea-949b-514622f32161.PNG)

**Comment by luc1an24** [comment]
Hi @N8Thrasher 
Thank you for reaching out.
You only have 2 algorithms displayed for GMiner because your cards don't support others.
For AMD cards there are 4 algorithms available (CuckooCycle, BeamV2, Eaglesong, Cuckaroo29BFC) of which only BeamV2 and Eaglesong can be used on your GPUs.
CuckooCycle needs at leats 6GB and Cuckaroo29BFC needs at least 5GB.
If you have any questions feel free to ask!
Have a nice day

**Comment by N8Thrasher** [comment]
I see, thank you.
