### ISSUE TITLE
Switch Profitability Threshold ...

### ISSUE THREAD

**Issue by electricdelicate** [nicehash/NiceHashMiner#2130]
Why not possible to change them permanently? For Example, if I overwrite them to 0.03 is the value after the next start at 0.05 again. 

It´s a bug or feature?

**Comment by luc1an24** [comment]
Hi @electricdelicate 
Thank you for reaching out
This is indeed a bug which will be fixed by next release.
For now you can change this setting inside "General.json" file located in configs directory inside NHM root folder. If you change it via file everything will work as expected.
If you have any questions, feel free to ask.
Have a nice day!

**Comment by luc1an24** [comment]
New release includes fix.
Closing issue.
