### ISSUE TITLE
Switch manually to any algorithm during mining

### ISSUE THREAD

**Issue by maxgamurar** [nicehash/NiceHashMiner#221]
It would be nice to have a switch tool to any available algorithm per device during mining process.

**Comment by drkskwlkr** [comment]
@maxgamurar What exactly do you mean? NHML does have the ability to switch manually to any algorithm per device. Go to `Settings->Devices/Algorithms` and disable all unwanted algos for that device :)

**Comment by maxgamurar** [comment]
@drkskwlkr -during mining process-, without hitting STOP button, it would be nice to have ability to override automatic selection of algorithm by profitability.

**Comment by drkskwlkr** [comment]
@maxgamurar I see now. Totally pointless. The whole idea of NHML is to automate the process of selecting the most profitable algorithm, so that people don't have to micromanage.

**Comment by maxgamurar** [comment]
@drkskwlkr since its a legacy version for pros, it would be realy useful, because sometimes I suspect that selected algo is not the most profitable one.
Or, if that sounds pointless, it would be even better to have a table with all available devices, enabled algos with current profitabilty (in btc and usd).
I have 2 identical cards and sometimes they are using different algos. So the button to force-override current algo realtime would be useful indeed IMO.

**Comment by RodAus** [comment]
@maxgamurar Actually, you're totally correct. This is a "pro" version the user supposedly has all the control of turning profitable options on/off or change it manually if is necessary. 

NHML needs a long time to read the exchange rates. The reaction time is over and very often not changed to the most profitable. I have to manually tick in dozens of boxes to switch to the most profitable one. *the "copy the settings algorithm from to" option does not work properly.

@maxgamurar your suspicions are very correct
Two of my Nvidia rigs are EXACTLY the same but with different results, it is very clear when one algorithm switch and the other does not and the profit difference is not small.

**Comment by maxgamurar** [comment]
@drkskwlkr I think we can close this one in favor of https://github.com/nicehash/NiceHashMinerLegacy/issues/271

**Comment by drkskwlkr** [comment]
@maxgamurar I can't close anything, I have no role in this repo. But opening another ticket for the same reason, especially since DillonN has indicated he will be looking into it, seems... how to say... pointless :D

**Comment by maxgamurar** [comment]
@drkskwlkr ok, but again its not pointless to suggest even better solution.
@DillonN please check  https://github.com/nicehash/NiceHashMinerLegacy/issues/271

**Comment by drkskwlkr** [comment]
@maxgamurar I stopped arguing as soon as my previous opinion got downvoted and Dillon indicated interest in the topic. Obviously your ideas resonate with others and that is fine; this is how things move forward — by sharing thoughts and ideas others thought not possible or impractical.

I personally still believe what you are asking makes little sense in the grand scheme of things. Knowing a thing or two about building interfaces, I happen to think that it will be a huge challenge to make a user interface that will accommodate such functionality and look/work well.

Even if such functionality is implemented, I know for sure I won't be sitting at my rig whole day to switch algos constantly and worry that I am not getting the maximum coin per watt theoretically possible; I have better use of my time. Also, I am confident that >95% of the other users of this service will feel the same and won't bother using such manual features.

I also believe that time dedicated to implementing a sophisticated interface for overriding automated tasks would be much better spent tweaking and improving the automated profit calculation algorithm.

But hey, all of this is just me.

If you want me to take back my words so that you can feel good, I won't do that. However what I think and do on this matter should not be bothering you at all at this point — your job should be to keep pushing for the implementation of the features you believe will make the product better. Peace.

**Comment by crystal-way** [comment]
Hello. I only can choose "Configure" but not "settings". And there is no "Devices/Algorithms" as you can see in the screenshots :| 
How do i configure algorithms?

Thank you.

![screen shot 2018-01-09 at 20 00 27 pm](https://user-images.githubusercontent.com/35271080/34735340-c939617c-f577-11e7-811b-93dca057889c.png)
![screen shot 2018-01-09 at 20 00 13 pm](https://user-images.githubusercontent.com/35271080/34735341-c98029ae-f577-11e7-8d53-042f9833ba16.png)

**Comment by drkskwlkr** [comment]
1. This repo *is not* for NiceHash 2.x, it is for NiceHash Legacy only.
2. Devices/Algorithms are found under 'Hardware Details'

**Comment by crystal-way** [comment]
All clear, Thank you!
