### ISSUE TITLE
NHM 3.0.5.6 benchmarking GPU "Error during benchmark"

### ISSUE THREAD

**Issue by Dzonns01** [nicehash/NiceHashMiner#2261]
Tried all possible fixes found on the internet, NHM spits gives an "Error during benchmark" after taking some time benchmarking. If someone could guide me, I'd be grateful.

1050Ti 4gb
Core i3-6300 3.8GHz
8Gb ddr4 ram
1914-10000 virtual memory

[log.txt](https://github.com/nicehash/NiceHashMiner/files/5756279/log.txt)

**Comment by luc1an24** [comment]
Hi @Dzonns01 
Thank you for reaching out and sorry for slow response.
Have you tried direct mining?
Since the card is 4gb it is a possible cause for those errors. 
For example please try to miner KawPow on NBMiner with the following command: `nbminer.exe -a kawpow -o stratum+tcp://kawpow.eu.nicehash.com:3385 -u 33hGFJZQAfbdzyHGqhJPvZwncDjUBdZqjW --api 127.0.0.1:4000 -d 0 --no-watchdog `
This will show you the miner output and you will see if it mines ok or not.
If it does, head into benchmark tab inside NHM and put the mining speeds into algorithm settings (select cog icon in the algorithm section and insert speed into benchmarks speed)
If you will need any help, feel free to contact me.
Have a nice day!
