### ISSUE TITLE
Online Browser can recognize GPU DESKTOP SOFTWARE DOEST 

### ISSUE THREAD

**Issue by probizwi89** [nicehash/NiceHashMiner#2296]
Auto Detection WORKS ONLINE BUT DOESNT REONIZE MY GPS ON THE DESKTOP 
![2021-01-22_15-34-04](https://user-images.githubusercontent.com/77857911/105542472-66549a80-5cc7-11eb-891a-e299863777f3.jpg)

**Comment by S74nk0** [comment]
@probizwi89 Can you please run NiceHash Miner and post the logs. The online detector is checking the GPUs via the video driver (https://github.com/nicehash/device-detection-server) but the application is checking OpenCL and CUDA devices these are the actual compute devices that the miners use (https://github.com/nicehash/DeviceDetection). I see you have a mixed NVIDIA and AMD GPUs. This can also be a problem for the OpenCL detector and for mining in general due to unstable NVIDIA and AMD drivers on the same machine. 
Maybe consider removing the NVIDIA 750 Ti you will not be able to mine with it at least not for long as it is being phased out by new GPUs on the market and no profitable miner will support older NVIDIA GPUs. We will also drop support for all NVIDIA GPUs bellow 5.2 compute capability for the next upcoming release and in about 3-6 months we will raise the requirement to 6.0 compute capability (https://en.wikipedia.org/wiki/CUDA) in the near future.
