### ISSUE TITLE
NHM Experienced too many crashes recently. Therefor it will closer itself..... full format the whole 9. Nothing.....

### ISSUE THREAD

**Issue by Doner8749** [nicehash/NiceHashMiner#2327]
Seriously so messed up. Came home and the one rig was down. Get this

Too many restarts
NHM Experienced too many crashes recently. Therefor it will closer itself..... full format the whole 9. Nothing.....

The system is fine and all components tested. Full format does not help even after Fdisk and reformat.... ???

**Comment by bantman33** [comment]
having exact same issue. Had nicehash downloaded around jan 10th 2021. Was running phoenix with ethpill on my 1080ti @ 50mh.

Had to reinstall nicehash today and cannot get the ethpill downloaded no matter what i do in WD and firewall

**Comment by bantman33** [comment]
Same here. The address for the ethenlargment pill is no Langer valid. Please fix ASAP

**Comment by kylhuk** [comment]
This bug is actually quite common and not really a good way to handle a potentially harmless issue. So the app locks itself out, until you delete certain directories.

Apparently, NiceHash records on how many times the app crashed in a specific timeframe. If it is too large, the app thinks that there is a major issue on the system. Unfortunately, there are cases where this happens without any major issue. Instead of quitting the app after experiencing too many crashes, the app should just send a warn message, so the user can still use the app (if it is working) and is able to investigate further, if he wants to.

**Comment by kylhuk** [comment]
Just made a very tiny, ugly quick fix, so we are still able to use this app, even though it crashed too many times. Let's just wait until they accept this pull request. :)

**Comment by mauler2025** [comment]
I have the same issue after I made Windows Defender remove `Win32/Uwasson.A!ml`.

Reinstalling NHM will fix the issue but `Win32/Uwasson.A!ml` attack reappears. 

It is really strange, why does NHM come with this "attack" warning?

**Comment by Dohtar1337** [comment]
> I have the same issue after I made Windows Defender remove `Win32/Uwasson.A!ml`.
> 
> Reinstalling NHM will fix the issue but `Win32/Uwasson.A!ml` attack reappears.
> 
> It is really strange, why does NHM come with this "attack" warning?

fixed

**Comment by DolbyID** [comment]
How please ?

**Comment by teehanming** [comment]
still happen

**Comment by kxtna09** [comment]
Bro I fixed it

My defender just blocked some of its programma

Add them to exclusion list
