### ISSUE TITLE
Why was the Gminer plugin removed? 

### ISSUE THREAD

**Issue by guitarmonkey** [nicehash/NiceHashMiner#2331]
Any security issues there, or what was the reason for this? 
Kind regards

**Comment by S74nk0** [comment]
@guitarmonkey the reason we removed Gminer plugin from the preinstalled list is simply because of the binary package size. The package size increases the initialization time of NiceHash Miner. Users can still install the plugin manually.

We provide 3rd party plugins because of their demand. They are flagged by different Anti Virus programs. The reason for this is because there are cases where people get infected by malware that distribute these same miners and are flagged as unwanted software because in that case that is what they are. And there are people that wish to use these very same miners to utilize their hardware for earning passive income. 
Regarding miner plugin binaries and their security this decision up to the user. We can only vouch for our own software that we develop e.g. [NiceHash Miner](https://github.com/nicehash/NiceHashMiner), [excavator](https://github.com/nicehash/excavator)...
