### ISSUE TITLE
windows cannot access specified device

### ISSUE THREAD

**Issue by DonDoggy01** [nicehash/NiceHashMiner#2370]
not sure if this is an issue on my end or with the download but when ever i try to run the nicehashquickinstaller i keep getting the same error message
![Screenshot_1](https://user-images.githubusercontent.com/80864203/111557506-b3636300-8784-11eb-98a7-44c0aa60e02c.png)

if anyone has any ideas would be appriciated.

**Comment by dledwith** [comment]
What antivirus solution do you use? Try right clicking on downloaded file and look at the properties. Attributes: and Security: sections at bottom of "General" tab.

**Comment by stufine** [comment]
I get this same issue using the amd version
the nvidia one seems to load ask stops since no nvidia card
properties=full
Noticed that after clicking nicehashminer.exe, it gives the error and the the file is deleted. I've added file and folder to windows defender and tried it with defender and comodo off.

Scratch that!!  It seems comodo was the one deleting it even with it turned off. sigh....It works

**Comment by Dohtar1337** [comment]
Disable PUA detection in windows defender
