### ISSUE TITLE
App crashes after removing detected security threats

### ISSUE THREAD

**Issue by mauler2025** [nicehash/NiceHashMiner#2416]
I installed NHM app on Windows. 
Windows Defender notified me as follows.

![virus](https://user-images.githubusercontent.com/50270635/115785370-8d675900-a3e9-11eb-9a8d-6f6f9e95c7d9.png)

Removing those threats makes the NHM app no longer works with an error saying:

> NHM Experienced too many crashes recently. Therefor it will closer itself

Should I assume those security warnings  are just a false positive and ignore them (not removing them)?

**Comment by mishmanners** [comment]
I get the same Trojan detected.

**Comment by mishmanners** [comment]
This all worked fine for me before the new update.

**Comment by mauler2025** [comment]
@MishManners  What did you do? Removing the Trojan? Does the app still work without the Trojan?

**Comment by mishmanners** [comment]
There's no way to allow the trojan. The app doesn't work at all

**Comment by pstricks-fans** [comment]
@MishManners : But does the NHM miner still work normal?

**Comment by mishmanners** [comment]
There's no longer a way to allow false positives

**Comment by mauler2025** [comment]
![trojan](https://user-images.githubusercontent.com/50270635/115906715-1508a280-a492-11eb-8c02-70648b8966a7.png)

**Comment by mauler2025** [comment]
Cryptojacking is the act of hijacking a person's computer to secretly mine cryptocurrency. 

Because cryptojacking requires increasing processing power to mine cryptocurrencies like Bitcoin, miners are discovering new ways to wield that processing power. One such way is to borrow it from thousands of unwitting internet users.

**Comment by Michaela813** [comment]
hello good evening! is this message for me? thats why nicehash still message me that i thought its normal for them having a convo , if ive done wrong im truly sorry. maybe the honeyminer too that always popped out because it still running. pls forgive me but i lost my IT guy thats why im struggling here doing everything on my own and learning too. this is not my field and born on the 70's , i apologise for any caused and i tried mining crypto but i said its a stupid idea for me and out of boredom, and to hashminer i had a problem with logged in and i got busy with trading , i dont need to mine just watch and still not learning. ill try to fix it pls forgive me! thank you.

**Comment by mishmanners** [comment]
Yay can now report this works through Windows Defender! Thanks team 😄

**Comment by mauler2025** [comment]
@MishManners : What do you mean? Who reported?

**Comment by mishmanners** [comment]
I can report it works through Windows Defender IF you decide to turn some things off. Ie. remove all other accounts that are managed by anyone then you'll be good. But it's only a workaround, not an actual fix.
