### ISSUE TITLE
Getting an error while running benchmark

### ISSUE THREAD

**Issue by afaktor** [nicehash/NiceHashMiner#2440]
**NOTE this issue tracker is for NiceHashMiner bugs/feature requests ONLY! If you need general help or have a support question related to NHM2 (OBSOLETE) or NHOS please look at https://www.nicehash.com/support first and open a ticket there if your issue is not specifically NHM related**

For general help there are several community resources available, such as https://reddit.com/r/NiceHash

There is a [documentation](https://github.com/nicehash/NiceHashMiner/tree/master/doc) available, so please check it out first. If you don't find the answer there, please create a new issue, that follows requirements stated below. 

To keep development of NiceHash Miner streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- **Relevant log files are included (generally `\logs\log.txt`).**
- **The issue is with NHM and not inherent of miner executables.** This can be verified by launching the miner manually and looking for the error.
- **The issue is relevant to NHM specifically and not to the NiceHash service, NHOS or NHM2.** (see above)
- Specifications of setup such as NHM version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

Log Id: 61f7f171-b003-40f4-996e-a3bf399e4a1b

**Comment by Edu3020** [comment]
Apparently there are errors & bugs occurring in nicehash when using algo KawPow and NBminer and for the most part it doesn't even work, I opened a topic reporting this followed by an extensive log.

**Comment by salvatoreboemia** [comment]
Hi,
report bug ID: a9b034ef-9a0a-4006-9c9a-cbc6df926022
basically I don't know why but I get always benchmark failed, only dagger hashimoto with Excavator works (as you can see in the attached screen)

I tried:
- DDU in order to unistall all driver (safe mode and offline)
- completly removed Nice Hash and re install
- add exception in defender windows 10
- install the last Nvidia Driver without DCH
- NO overclock is set for my GPU when I launch the benchmark
- RAM; 4GB physics - 15GB virtual

the mining in running, but why ONLY Excavator benchmark works fine? I really I don't Know. I tried all.

thanks

HARDWARE: RTX 2070 Super

![allError](https://user-images.githubusercontent.com/20614870/119267932-ee549d80-bbf0-11eb-9460-84cb4468f31f.JPG)

**Comment by Dohtar1337** [comment]
https://www.nicehash.com/bloag/post/benchmark-error-in-nicehash-miner

Most likely asus router or ISP is blocking the connection, read the article above

**Comment by douglasg14b** [comment]
Link rot, google sends me here, the above link is dead :/
