### ISSUE TITLE
GTX 760 4GB cuda 3.0 not supported somehow

### ISSUE THREAD

**Issue by SamKook** [nicehash/NiceHashMiner#2441]
GPU-Z detects the card without issues, tells me it supports cuda 3.0 and that my GTX 760 indeed has 4 GB of memory size so I don't see why nicehash miner doesn't detect it has a supported card since it does show up in the log and meets the minimum requirement as far as I can tell.
The GPU is plugged in directly in the main pci-e slot and is the only gpu in the pc(my motherboard doesn't support the integrated gpu of my cpu).

I'm running the 466.27 driver with a clean installation since gpu-z wouldn't detect the memory size or the cuda when I first updated it but the clean installation fixed it. Tried an older driver too before without success either.
Installed NHM v3.0.6.5 and I can mine with my cpu(i7-2600k) without issue.
I am using win 7 x64 which I assume is fine for this one since it doesn't mention it only runs on windows 10 like the quickminer version.

Rebooted many times, don't have much running on this pc and the windows install is only a few months old so don't think anything else should cause a compatibility issue and I did try the troubleshooting steps and looked in the issues but found nothing helpful so I'm kinda stumped at what else to try here.

Included the logfile for 1 opening of the software.
[log.txt](https://github.com/nicehash/NiceHashMiner/files/6470941/log.txt)

**Comment by alexsaga89** [comment]
Same problem here. Win 10 x64 with Gtx 760... Tried countless different settings, drivers, tried switching different Motherboards, CPUs, Ram. Drivers off all sorts. Even think i tried drivers from 2013-14.. And all that for no reason. I hope someone can figure this one out. All the time and effort and no explanation.😤 😆

**Comment by SamKook** [comment]
I know most 760 only had 2GB of memory(unlike mine which is a 4GB version) so you have to make sure you have a version with more than 3GB or it won't work for sure since that's the minimum supported..

**Comment by anazz20** [comment]
760 can support CUDA 3.0, although the minimum is now 5.2
https://www.nicehash.com/support/mining-help/general-help/is-my-hardware-supported

**Comment by alexsaga89** [comment]
Ohhh... Now i feel really dumb. But i never read anything other than 3.0 so i thought everything was ok. Forgot to write that mine is also 4gb. Did you Try other miners with success? Or mining services? I make about 1usd a day  with my core i7-3770 and the Gtx 760. Cant remember what algos but i have had luck with the kryptex mining service but sometimes when it updates it stops working. but on the Next update it usually works again. Well better start saving money so that i am prepared for that time when i walk in a computer store and see rtx 3080 and 3090`s in stock and on display. The Gtx 760 is about 9years old by now i think 😆

**Comment by SamKook** [comment]
The readme file for NHM says the minimum hardware requirement is compute capability 3.0 which the 760 is so I assumed that 5.2 was for quickminer or something. I usually trust the readme above all else for this but you could be right and it simply wasn't updated yet.
