### ISSUE TITLE
NiceHash 1.8.1.1 Freezes with RX580+1080

### ISSUE THREAD

**Issue by Xv0stik** [nicehash/NiceHashMiner#249]
NiceHash 1.8.1.1 with RX580 freeze windows after 5 minutes of mining. So now I use NiceHash 2 for 1080 and Clamore for AMD. Tried change drivers with out success.
System: Asrock H110 PRO BTC+, Win 10 x64, 6 x 1080ti+5 x RX580

**Comment by jimmyhackers** [comment]
i got a 1080ti today. it decided to lock up and black the screen on benchmarking. untill i did each benchmark individually.

i have a feeling "dual" mining algos were messing it up and individually benchmarking negated this error.

its not mining any duel stuff atm due to profitability. so all is well. i guess if it does start dual mining and crashes my pc i know what the culprit is

**Comment by raclarke1** [comment]
I had the same problem with  RX580 and 1080 ti being on the same machine causing the machine to be non responsive.
