### ISSUE TITLE
Stat window re starts periodically, lower hashing rate now...

### ISSUE THREAD

**Issue by ZUMA48** [nicehash/NiceHashMiner#2558]
my window closes and re-opens restarting the mining process, I think it's affecting my hashing because it went down for the last few payouts. LMK  TY

**Comment by remotettl** [comment]
my guess its caused by gpu. if you have more than one gpu, first one who finished benchmarking, starts the miner (NB miner for example), runs and then when other card is done, it restarts. have rig with 5 gpus and it constantly restarts over time. its related, in my case, cause of one bad gpu. it stays in red color, and it forces NB miner periodically restart itself. doesnt cause much of a loss but small. over year might leave some impact but dont mind it. 
if you have one card, might be drivers (DHCP ones was issue for me once with similar restart every 2 or less hours) of GPU or low virtual memmory of the system itself.

**Comment by Dohtar1337** [comment]
Does the issue still persist with the latest version?

**Comment by Dohtar1337** [comment]
No response. Closing.
