### ISSUE TITLE
less efficiency after new update v1.8.1.2, less earning, 40% less.

### ISSUE THREAD

**Issue by mandeep148** [nicehash/NiceHashMiner#270]
new update is not efficient and using less gpu and cpu causing less earning, please tell me how to fix it.

**Comment by adem4ik** [comment]
> please tell me how to fix it

considering the lack of information you gave, i have only answer - by using previous version

**Comment by jimmyhackers** [comment]
it is possible during your benchmarks your computer was doing "other" tasks in the background reducing your benchmark score and reducing your profit.

open up the new and old versions settings and see if you benchmarked scores are the same.

try rerunning the benchmarks. see if that helps
if not try a "precise" benchmark test and see if that helps.

**Comment by mandeep148** [comment]
thanks for reply, im doing benchmark again. :) will tell you :)
Also wanted to tell, that thers freeze problem, some time cursor loading circle spinning, software stay freeze.. had to restart software. i mean software some time do lose of electricity,
like yesterday night i started mining and saw on morning no earning and software freezed. these kind of issue disgusting :(

**Comment by rickrs** [comment]
question :  the benchamark ,

how many times we need run in a week? one time only? or for better results,
is good run a few more times?

tks

**Comment by mandeep148** [comment]
i ran benchmark it remains same, i dont think benchmarks do anything? its just for measuring how much performance in different algorithm..
btw which algorithm for gtx 1070? mine does better in Equahash, 
which you prefer?

**Comment by dinicthis** [comment]
Mandeep, you are correct in that the benchmarks don't DO anything, but if they were inaccurate, then your machine will mine with a less-profitable currency that it THINKS is more profitable.

However, mine has also been acting stupid, mining a patently less-profitable currency even when the benchmarks I did (and I did the longest benchmark available) show that the currency is less profitable.

So, I just look down the list of benchmarks, and lock out the currencies that are less profitable, and mine is profiting okay.

Example: it has flipped onto Gost and Keccak a few times, and I can see the readout that says profit per day, and it reads lower than if I just keep it doing EWBF's Zcash miner. Usually it gives up on them after a while, but I lock them out if I see that it just won't quit flogging a dead horse.

When I benchmark, I close all other programs that will not be running during mining, and let'er rip. I avoid the temptation to touch the keyboard and use the computer. This yields an accurate benchmark.

But, strangely, I have found that it will go over to the lower-paying currency anyway. I can see right on the mini-screen that it is making less money.

But, is the mini-screen that shows your momentary gains more accurate than whatever algorithm chooses your benchmarks?

I've been up about 20 percent since I started using EWBF's miner and carefully setting the computers to use what is ACTUALLY more profitable, instead of what NHML erroneously calls more profitable.

After that increase, I also uninstalled Bitdefender, which seems to cause crashes and erase entire DIRECTORIES, no matter how much you protect the files, folders, processes, web access. When a new update comes out, it ignores ALL THE RULES you have spent hours putting in place, protecting every single individual file and folder.

I recommend you abandon Bitdefender if you are using it, and use something less intrusive, like Windows Defender.

Then see how it's working.

**Comment by luongk** [comment]
> Example: it has flipped onto Gost and Keccak a few times, and I can see the readout that says profit per day, and it reads lower than if I just keep it doing EWBF's Zcash miner. Usually it gives up on them after a while, but I lock them out if I see that it just won't quit flogging a dead horse.

I wonder if this is a side effect of the new profit normalization feature - i.e. NHML isn't switching you over when the price initially spikes, but when the price is still high (but about to go down) so by the time you start mining the other coin the price has fallen.

**Comment by dinicthis** [comment]
It would not take much to make it monitor more accurately, but it would chew up a tiny bit more bandwidth, but I think it would be worth it.

**Comment by mandeep148** [comment]
@dinicthis  can you guide me how to setup zcash miner manually? i tried but worker not showing in nicehash dashboard.

**Comment by DillonN** [comment]
@dinicthis from what I can tell by your description, it sounds like you are having problems because some buyers on NiceHash intentionally place very small but high priced orders on random algorithms (e.g. X11Gost is popular) to switch miners away. The order finishes very quickly so the paying rate goes back down (i.e. to less profitable than Equihash) but NHML has not yet switched (due to switching time setting)

There was a feature introduced into 1.8.1.2 to try and mitigate this issue, but you can try adjusting the values for it to make it more aggressive. More info [here](https://github.com/nicehash/NiceHashMinerLegacy/wiki/Profit-Normalization)

@luongk the way the profit normalization feature works is it only normalizes upward spikes, so if X11Gost drops back down to normal level before the switch takes place, the switch should not happen (it uses freshesht profit data with no normalization at that point)

@mandeep148 I think @dinicthis meant just disabling other algorithms to force NHML to stay on EWBF. However if what you said in the initial post is true (less GPU/CPU usage) then the problem is not with that but miners not using all available resources (try adjusting intensities)

**Comment by dinicthis** [comment]
Thanks. I abbreviated the window of switching the miner to a different algorithm, seen very very little dumbo mining as a result.

**Comment by dinicthis** [comment]
Mandeep: you set up which version?

If you set up 1.8.1.1, then you may not have a certain miner that 1.8.1.2 has.

I ran into that, thought miners were disappearing, but alas, I had accidentally opened 1.7.5.3.

**Comment by mandeep148** [comment]
@dinicthis on latest 1.8.1.2
@DillonN  bro, can you tell which intensities good for nvidia gtx 1070, im not good at coding things? :(
profits are decreasing :/ dont know why, im confused. market value of Bitcoin increase and mining profits are decreasing.

**Comment by dinicthis** [comment]
I haven't touched the intensities.

**Comment by mandeep148** [comment]
im confused with intensities, it would be great if any tell me what to put their.
anyways,
im really frustrated that time, think that, Bitcoin price  are increasing but mining profit decrease, like my old machine was used to earn 0.0009 and now i check same machine its earning 0.0004 its so annoying,
i think something wrong or any scam doing by pool..

**Comment by dinicthis** [comment]
if Bitcoin is worth twice as much and you are mining OTHER coins,  then
your BTC per day will be half as much for the same dollar value.

**Comment by dinicthis** [comment]
.005 BTC  at $4500/ BTC is the same earnings as .010 BTC at $2250/ BTC.

**Comment by mandeep148** [comment]
you are right but profit is going down on Computer hardware, but its worth in asic mining.
if its not bitcoin or pool problem, what can be the issue, help me find out..

**Comment by mandeep148** [comment]
right now, i check card profitablity, one card of GTX 1070 is earning 60INR a day, which is so bad,
but if i look nice hash website, its written that gtx 1070 is top 5 GPU in world for earning, its earning 150inr per day, thats so big difference, why im earning less. please help.

**Comment by DillonN** [comment]
Intensity settings are specific to each miner type, you can add them through an extra launch parameter. By default if you don't touch anything, the miner programs themselves choose a default intensity. I can't tell you what the best values are for your cards unless I have them (I do not have a 1070) but you can adjust these values yourself and see if it makes your problem better or worse. If you have less than full GPU usage I'd recommend adjusting upward.

The specific values for each miner program are [on the wiki](https://github.com/nicehash/NiceHashMinerLegacy/wiki/Algorithm-ExtraLaunchParameters)

**Comment by dinicthis** [comment]
on X11 Ghost my GPU usage plummets.

**Comment by mandeep148** [comment]
please im so weak in these things, i still cant understand, but i want to try intensities.
one more thing, if i choose equahash(excavator) i get 390 sols and if i run equahash with EWBF, i get 430 Sols, i cant find EWBF in latest version of equahash, so im using old version,
please give intensity for more profit i can get, i would try that, i would really appreciate thanks alot,

**Comment by dinicthis** [comment]
Equihash.

"I can't find EWBF in latest version of Equihash." Meaning? Nicehash? I'm using NHML 1.8.1.2.

**Comment by dinicthis** [comment]
You open the miner.cfg file and look at intensity. It's defaulted for 64, which is the maximum. You could try 32 and see if it gets better, if not then try around 48, etc. and zero in on whatever gives best rates.

**Comment by dinicthis** [comment]
Oh, and if you just run your fans on maximum all the time, you will get more profits. The GPU will self-regulate based on temperatures, whether or not it tells you it is in Afterburner or Precision X Overclocking (PXOC)
As an example, my machine was going along at 218 H/s on Cryptonight,(on the CPU) and 332 on EWBF/Equihash, and by cranking only the video card fans to max, the Cryptonight immediately jumped to 249, and the EWBF jumped to 369 or something like that.

Computers thrive on cold, and they won't always tell you that. They are like women and money in that sense. Like it is impossible to run a computer too cold, it's impossible to give a woman too much money. They will both be happier, even though neither one will actually admit it. You will get more output from a computer AND a woman when you add more cooling or money.

Whether you agree with this or not, try it. See how it goes.

**Comment by mandeep148** [comment]
@dinicthis i dont see miner.cfg in 1.8.1.2 version, there is extraparameter in selected algorithm, do you mean that?

**Comment by mandeep148** [comment]
@dinicthis @DillonN 
im really getting power profitablity and power performance,
please help me, give me intensity to apply on Equahash(EWBF) 
im getting 440Sol/s with one GTx 1070,
see in nicehash calculator, GPU is writen as 435sols getting 20% more revenue, but im getting less.
ialso applied intensity in EQUAHASH(EWBF) i.e. --intensity= 70 dont know its true or not, you should suggest intensity, its difficult for non coder person but easy for you..

![screenshot 9](https://user-images.githubusercontent.com/30183847/30363654-a9ead14e-987e-11e7-80ec-5b9414088d45.png)
![screenshot h9](https://user-images.githubusercontent.com/30183847/30363655-aa1cb646-987e-11e7-9d41-9de66468b57a.png)
