### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by DmitryDMR** [nicehash/NiceHashMiner#276]
1. Please add fee wallet function to the NHML like as devfee with % of time of mining to them.
2. For rigs with slow hdd with enabled windows start options NHML not detected videocards. Needed to adding timeout box and starting any procedures only after timeout.
3. Need add autocheck internet connection and NHML profability data loading without any promts and manually NHML restartig. Only info in the main program window with timer to the next recheck.
![1](https://user-images.githubusercontent.com/30769434/30079457-e4988b70-9288-11e7-9dfb-f674c06172ad.jpg)

**Comment by Avalonis** [comment]
to 2.
make a bat file with sleep (10  - 30 sec) command than c:\\folder\NHML.exe

make a softlink and take it to "autostart" 

in settings checkbox "start mine after NHL starts)

**Comment by DillonN** [comment]
For 1, adding a donation option can cause issues since many IPs mining to one address from around the world looks like a botnet

For 3 that is a good idea I will look into it

**Comment by underway113** [comment]
Please add Auto Server Feature.

**Comment by Olegik-ah** [comment]
For 3. Pls, add "default" algo also. For example. When NHML starts and cant get profability data - it will use "default" algo.
Thanks!

**Comment by DmitryDMR** [comment]
@DillonN. For 1. This is not an obligatory donation. For example, my friend does not understand anything in the rigs, nor in the mining and constantly asks me to help him. I havn`t time for this, but only i may help him. And any work should be rewarded. And I'm not the only one. So it will be convenient for him to reward me for my work and encourage me to work as quickly and steadily as possible. 
And other friend buy only 1 videocard at this time, and install it to my rig. for this situation i want mining 15-20% to the his wallet. Everyone is happy.

@Olegik-ah good idea. We need start default/more profitable algos based on benchmark results

**Comment by jackpot1136** [comment]
I AM THE REASON THEY CHANGED EVERYTHING UP THIS MORNING.You are completely right about any work should be rewarded because for rhe simple reason like your friend I don't know too much about computers or mining, but I'm learning. Two days ago I finally figured out a how to mine better through getting my miner to focus on the important things where he's more efficient. I understand that their ass is hurting because of the 31 million that they lost on sunday noon, but that doesn't give them the right to strip me of all of my hardworked earnings. Because the stole from me of all of my hard earned money this morning and I havent even figured out how to transfer into my wallet yet.  Ive been up day and night working and teaching myself about coputers mining and everything that goes along with it so that I can provide for my family. And these moterfuckers wanna hack into my computer and strip me of months of hard work besause two days ago a few of my sections of mining for that day didn't equal up. Now because of me talking shit this morning doesn't mean they have the right to STEAL my proof of work.I understand about taking those sections from two days ago,out but to strip me of everything is bullshit. It is because of us (people mining)why they are growing for them to turn on us like we're the bad guys and rob us for everything is bullshit. I'm talking abouth Geth and the wonderful staff for niche\hash Miner Legacy, and Etherbase. I want my hard earned money back mother fuckers. I understand am ok with you taking part of it out from two days ago but the rest of it is proof of hard earned work and i deserve to get paid for it. YOU GUYS ARE NO BETTER THAN THE guy/girl that GOT THAT 31 MILLION ON SUNDAY. I WANT MY MONEY BACK.

**Comment by luongk** [comment]
@jackpot1136 I'm confused about how this relates to NHML - exactly what has happened?

**Comment by jackpot1136** [comment]
The change you had this morning, is because of me mining through geth.

In Health,

Milan Popich
Milan.popich@yahoo.com


On Sep 7, 2017, at 5:51 PM, luongk <notifications@github.com> wrote:

@jackpot1136 I'm confused about how this relates to NHML - exactly what has happened?

**Comment by luongk** [comment]
@jackpot1136 What change are you referring to? I'm not aware of any chances to Nicehash/NHML
