### ISSUE TITLE
Suggestion after months of using

### ISSUE THREAD

**Issue by Lysnyt** [nicehash/NiceHashMiner#2769]
1. unable to choose install path even through that you know the software will be flaged by antivirus
2. never never ever the option to start with windows work for me, nor any help from your side (help in the program) to make it manualy 
3. autoupdate nicehash miner never worked for me
4. autoupdate installed plugins - maybe for your excavator, but what for is this function if plugin has never version, or couple new versions and you have still version from long time ago (i know, not always is never better, but..)
   xmrig your version 6.8 (1yr old) newest v6.18.0
5. The list of GPU-s is -to put it bluntly- elementary. If you have a rig with 14x same cards, all is somehow chaoticall. For example if i close the algorythm list for a card, and all other cards are closed too, i don´t see any optical difference which card i have opened (only if i memorized before that little gray id GPU#..) 
   I would apreciate at least the every other row color / or make the row named "benchmarked">yellow "disable">red "enabled">green or anything different as gray on black / black on white
5. if i want to fill extra parameters to overclock the card in any algorythm, i don´t know what to fill in cause there is no wiki/link/help.. nothing .. i need to search the web for it ( help is simple solution, even you are advanced user)
   i still don´t know if there is any overclock solution for your excavator in nicehashminer through extra parameters 
6. if i want to benchmark whole rig and i don´t know exactly what card is stable and which not, the rig will take stock settings for all cards, will put them on max TDP and voila > at least overcurrent cut out, at worst burned equipment
   After benchmark the mining is automaticaly started, but why ? the whole proces is long if you have big rig, you are not whole time by it, and after you come back, the rig is restarted becuase something happened > please give there at least an option to make it auto or not
   Manualy choosing card to benchmark and other disable is not very  Manualy choosing card to benchmark and other disable is not very effective in my opinion 
   ? why there is no safety check / automatic behaviour, as all cards are benchmarked at once > there can be option to benchmark card after card at least, or change the cards stock settings to lower TDP depend of amount of cards in the system < and this can be overriden by option if the user is suicider 
7. after closing nicehash miner / or when is steam game started, the grafic card overclock settings should go back to stock settings / auto, but here i need to restart OS (this will cause underpowered card > freezing, BSOD, fan fixed speed..)
8. Benchmark process is loooong (first benchark, then manualy fill the exact values to all cards/algorythms) and there is no option to export this database, if you will manualy update the nicehash miner. So you need to go through whole benchmark proces again
9. No check or warning that Power usage is ZERO ! after benchmark (therefore, any related function will not function correctly) 
10. minimum profit/day function does not work ( current profibality  show negative values - deficit but still mining ) 
11. If something happen and the algorythm is clasiffied as "unstable", you can hit "Start mining" and it is showing mining, but no mining is present / no window with mining, nothing - instead you get silent notification "no available algorythms"
12. After OS restart, the power profile is always High no matter what i choose before 
13. Replacing physically one card for another in system (workaround > Changing the list of graphic cards in nbminer extra commands) caused restart of nicehash three times > and unable to start nicehash itself (removing file NBMiner-xxxxxxx.json in config directory solved issue)

**Comment by Dohtar1337** [comment]
Thanks for your feedback!

1. You can change the install path by using the ZIP (portable) version of NiceHash Miner
2. We are investigating this issue, but cannot find any ways to reproduce it. 
3. Make sure to enable auto update in the settings
4. We need to check the xmrig code to update it. It is on our roadmap. 
5. You can enable GPU PCIe bus IDs in the advanced settings
6. We plan to prepare articles for extra commandlines. Stay tuned
7. If your rigs are restarting, then you have some other issue that needs to be addressed. For example, a bad GPU riser or high OC settings or not enough power from the power supply
8. Your PC is unstable, this is not the expected behaviour
9. You can always disable the unnecessary benchmarks. Also, these benchmarks are only run once and most of the times are not re-benchmarked
10. This should be added, I agree.
11.  What currency are you using? What NHM version? This was worked on couple of versions ago.
12. If benchmarks are unstable, you need to check them manually, Like I said, it seems like your PC is unstable due to bad risers, bad hardware configuration, bad driver installation or issues with PSU
13. There are no profiles in NiceHash Miner
14. Of course, you should check all the settings after changing the GPU in the system
