### ISSUE TITLE
Stops working 1 GPU

### ISSUE THREAD

**Issue by Woldemar83M** [nicehash/NiceHashMiner#284]
Rig 2 GPU. Stops working 1 GPU. After restarting the program in the list finds only 1 GPU. Helps only restart the system completely or through device Manager to disable then enable the device and restart NiceHash Miner legacy. NiceHash Miner legacy 1.8.1.2. Windows 7 professional. GPU without overclocking.

1 stopped working 2 gpu
![1 stopped working 2 gpu](https://user-images.githubusercontent.com/31724423/30165713-bb5050f6-93e9-11e7-9e3b-38f1acf7db6e.jpg)
2 stopped working 2 gpu even on a different algorithm
![2 stopped working 2 gpu even on a different algorithm](https://user-images.githubusercontent.com/31724423/30165711-bb4b849a-93e9-11e7-8e83-abefaa434eda.jpg)
3 after you restart the program finds only 1 gpu
![3 after you restart the program finds only 1 gpu](https://user-images.githubusercontent.com/31724423/30165712-bb4cc738-93e9-11e7-8b6c-9c1a78a8aeda.jpg)

[log before restarting the program where it really works only 1 GPU.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1284801/log.before.restarting.the.program.where.it.really.works.only.1.GPU.txt)

**Comment by jimmyhackers** [comment]
sometimes my gpu dissapears from the menu like yours also....
its usually after ive come to my pc in the morning to find that the gpu algo has been opening and closing all night long. :s

i usually have to restart my pc to get it to reappear
i half think its a windows error reporting service thats causing a hangup but im not sure.

**Comment by Woldemar83M** [comment]
It would be nice if fixed this problem, since it appears this problem on different video cards and rig! Without additional software it's hard to notice the problem!

**Comment by DmitryDMR** [comment]
try this bat file for nvidia cards. (rename txt to bat) it was restart your rig when average gpu loading lower than 85%.
and it applay msi ab profile when memory clock not as set in msi ab and .bat file
you need change this settings:
set timeout=120
set NUMGPU=6
set mingpuload=85
set ABProfile=Profile5
set /a "gpu0memset=4608"
set /a "gpu1memset=4590"
set /a "gpu2memset=4590"
set /a "gpu3memset=4590"
set /a "gpu4memset=4590"
set /a "gpu5memset=4212"

[Mining_Listener_2card.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1286093/Mining_Listener_2card.txt)
[Mining_Listener_6card.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1286092/Mining_Listener_6card.txt)

**Comment by sebeksd** [comment]
It is known issue (same as #74 and probably more). It happens when algo switching take place (for some algos more than for other), it can happen also if GPU is not 100% stable. I made solution/workaround for this (you can compile NHML from sources from here https://github.com/sebeksd/NiceHashMinerLegacy/tree/CUDA_GPU_lost_restart).

It is working for me for about a week (automatic 3-4 restarts per day).

Also you can switch off all aglos and leave only Equihash, your rig should be stable with this settings.

**Comment by jackpot1136** [comment]
I AM THE REASON THEY CHANGED EVERYTHING UP THIS MORNING.You are completely right about any work should be rewarded because for rhe simple reason like your friend I don't know too much about computers or mining, but I'm learning. Two days ago I finally figured out a how to mine better through getting my miner to focus on the important things where he's more efficient. I understand that their ass is hurting because of the 31 million that they lost on sunday noon, but that doesn't give them the right to strip me of all of my hardworked earnings. Because the stole from me of all of my hard earned money this morning and I havent even figured out how to transfer into my wallet yet.  Ive been up day and night working and teaching myself about coputers mining and everything that goes along with it so that I can provide for my family. And these moterfuckers wanna hack into my computer and strip me of months of hard work besause two days ago a few of my sections of mining for that day didn't equal up. Now because of me talking shit this morning doesn't mean they have the right to STEAL my proof of work.I understand about taking those sections from two days ago,out but to strip me of everything is bullshit. It is because of us (people mining)why they are growing for them to turn on us like we're the bad guys and rob us for everything is bullshit. I'm talking abouth Geth and the wonderful staff for niche\hash Miner Legacy, and Etherbase. I want my hard earned money back mother fuckers. I understand am ok with you taking part of it out from two days ago but the rest of it is proof of hard earned work and i deserve to get paid for it. YOU GUYS ARE NO BETTER THAN THE guy/girl that GOT THAT 31 MILLION ON SUNDAY. I WANT MY MONEY BACK.

**Comment by Sav87** [comment]
as an option to run "nvidiaInspector.exe -restartDisploDriver" with subsequent application of video card settings.

**Comment by sebeksd** [comment]
@Sav87  it work perfectly, thanks :) I added it to my pull request #268
