### ISSUE TITLE
cryptonight, socket error receive error: socket closed

### ISSUE THREAD

**Issue by jimmyhackers** [nicehash/NiceHashMiner#286]
i7 3770k running at about 320h/s on crypto.....
gtx660 running at about 125h/s also on crypto
it seem ever 10 minutes i get this error.

miner disconnects for about 5-10 seconds then reconnects. over 24hrs this adds upto about 24 minutes of "downtime"  granted as an individual im not losing a lot of profit but if nearly every nicehash user is having a similar issue as a community were loosing a fair amount of hashing power.

googling the problem doesnt seem to help much either. the consensus appears to be as the difficulty recently went upto 80000 instead of 40000 my hardware (aswell as everyone elses) is now too rubbish/slow to mine crypto with hence me getting timed out evey 10mins.

is this a fixable problem with the algo/service?
or will this be happening forever more ? :(

**Comment by ChriscomIT** [comment]
Dude its normal behavior. Cryptonight sometimes needs more than 10 minutes to finish an result. Following the stratum protocol spec, the socket gets disconnected after 10 minutes until another result is received. Therefore you see some sort of downtime in the web stats but when the result was submitted/received by the server you see the spike in web stats so you not losing anything (keep in mind web stats itself has a 5 min refresh interval as well).

Nothing "to fix" here as it is expected behavior and everything is working as intended.

**Comment by DillonN** [comment]
As @ChriscomIT said it is because you are submitting shares less frequently than once every 10 minutes, and so the connection times out.
