### ISSUE TITLE
NiceHash app crashes after running for long periods

### ISSUE THREAD

**Issue by Mystere** [nicehash/NiceHashMiner#306]
The miner keeps running, but the NHML app itself crashes.  Typically, this seems to happen if i'm running it for 12+ hours at a time.  

It's good that the miner keeps going, but there is no profit switching because NHML is no longer running.

Nothing that I can see in EventViewer related to this, and unfortunately the NH logs have rotated already.  I'll see if I can get a log next time.  This has happened about 6 times for me already in the last week or so, since 1.8.1.2 was released.

My guess is that you're catching the exception, but then exiting the app somewhere, since no other error information seems available.

**Comment by Mystere** [comment]
Here's the last thing that happened the last time the app crashed.

`[2017-09-14 00:11:02] [INFO] [SOCKET] Sending data: {"method":"devices.status","devices":[[0,"Intel(R) Celeron(R) CPU G3950 @ 3.00GHz",2,40,0,0],[1,"EVGA GeForce GTX 1080 Ti",5,99,56,2821],[2,"EVGA GeForce GTX 1080 Ti",5,99,59,2934],[3,"EVGA GeForce GTX 1080 Ti",5,97,73,3251],[4,"EVGA GeForce GTX 1070",5,99,52,2591],[5,"EVGA GeForce GTX 1080 Ti",5,98,65,3277],[6,"EVGA GeForce GTX 1080 Ti",5,98,66,3393],[7,"EVGA GeForce GTX 1080 Ti",5,98,68,3126]]}
`

After that, nothing.  No errors in the log.

**Comment by miesdr** [comment]
Hi Nicehash dev,

i have the same problem for version 1.8.1.2 and 1.8.1.3 not responding if run more than 12 hours
Nicehash main apps will not responding if run for more than 12 hours.  i have to kill and restart the apps.

Attached is the log.
[LOG.zip](https://github.com/nicehash/NiceHashMinerLegacy/files/1309856/LOG.zip)

**Comment by DillonN** [comment]
@Mystere if that is the last entry in the log it is hard to tell what would cause the crash. It looks like all the device status updates worked properly, the only other thing would be trying to send on the socket if it has closed, but you would see an error for that before. There is also a lot of error catching in this area, all of which would log and none of which would close the program so it is hard to say if the crash is related to that at all. What miners were being used at the time of the crash?

@miesdr you may have a different issue since it is a freeze. From your logs there is a corruption in your Windows performance library you can try to fix it with the instructions [here](https://github.com/nicehash/NiceHashMinerLegacy/wiki/Rig-Stats-Monitoring#perflib-problems). That shouldn't be causing a problem though just cluttering up the logs

**Comment by Mystere** [comment]
@DillonN - EWBF was running at the time, but as I said.. the miner kept running just fine.

**Comment by Mystere** [comment]
@DillonN  - FYI, this issue is still happening.  It's random, and there are no indications in the logs of anything specific.  Clearly your exception handling is not catching some exception.
