### ISSUE TITLE
1.8.1.1-2 - NHML with gf1050 break second NHML with 1060 (once more)

### ISSUE THREAD

**Issue by leonik3** [nicehash/NiceHashMiner#308]
I made a video for this error. You can see usage of cpu and memory from 4 different cards. Most interested are from first card A and third card E (1050).
[https://youtu.be/yUjqNe6yQJw](https://youtu.be/yUjqNe6yQJw)

When first start program NHML 1.8.1.1 with gf 1050 2GB (usually Equihash), then do something on another gf card (1060 3GB, which is first on NHML list). I can see this on MSI Afterburner, because gpu core on some seconds grows to 1500MHz. After that no one of Dagger Claymore algorithms works on 1060. There is an error. On NHM 1.7.5.13 there was not any problems, because this version does not contain this Claymore algorithms.

CUDA error - cannot allocate big buffer for DAG. Check readme.txt for possible solutions.
GPU 0 failed
Setting DAG epoch #139 for GPU0
GPU 0, CUDA error 11 - cannot write buffer for DAG
GPU 0 failed

Now I know that there is an identical situation when there are 2 NV 1060 3GB cards. If the second card first launches Equihash, the first one can not start Dagger Claymore. There is identical error. If I close the second card with Equihash, the first one starts without error.

Logs in this issue:
https://github.com/nicehash/NiceHashMinerLegacy/issues/206

**Comment by DillonN** [comment]
Hello @leonik3, do you see this behaviour if you launch EWBF on the 1050 manually, i.e. without NHML? You can do this by opening a command prompt in the `bin_3rdparty\ewbf` folder and entering `miner.exe --cuda_devices 2   --server equihash.eu.nicehash.com --user 3DJhaQaKA6oyRaGyDZYdkZcise4b9DrCi2.leo2E --pass x --port 3357 --api 127.0.0.1:4500 --fee 0` (this is the exact command line NHML is using to launch). 

It does look like NHML is always launching EWBF with the correct device code, 2, for the 1050. It is still possible that EWBF may be taking resources from another card though, since the miner is closed source I cannot tell you how it works. Do you also get this error if you use Excavator for Equihash mining on the 1050? 

In the video you do not show memory usage on the other 2 1060s, do they go up in usage when the 1050 starts as well? It's possible EWBF is using some of the display VRAM (assuming the first 1060 is what the display is plugged into).

**Comment by leonik3** [comment]
Hello @DillonN. I do not have this error when I use Excavator.
I think error is only in code EWBF when miner is starting work. It do something on first card (memory+GPU) and don't free memory after that period. In this period (when miner start)  - second and third cards does nothing - remain in their state  (slow and without memory occupied).
On 2 computers I can see in MSI Afterburner, that always in start period EWBF Equihash use FIRST CARD.

**Comment by DillonN** [comment]
dtsm miner was added which should be faster than EWBF, so as an issue with EWBF it is recommended to just use dtsm instead
