### ISSUE TITLE
NHML 1.8.1.3 GPU FAN SPEED AND TEMP NOT SHOWN (XMR)

### ISSUE THREAD

**Issue by Paapo** [nicehash/NiceHashMiner#317]
Hi,
i´ve installed nhml new Version yesterday. It is working fine and stable, except the Monitoring of the GPUs. I don´t know why, but when i mine cryptonight (XMR), no GPU Stats are shown. No GPU TEmp and no Fan Speed. Picture is attached.
I´m using the crimson Blockchain Driver (latest). All Cards, except one of 12 Cards, are bios modded. Operating System is Windows 10.
![nhm](https://user-images.githubusercontent.com/27375501/30481338-4e8f7e2a-9a1e-11e7-90b6-0024ba226418.JPG)

Is is not effecting the mining procedure itself. Might be an Installation failure from my side. I´m wondering, nobody else is reporting this issue. I tried Version nhml1.8.1.2 and nhm1.8.1.3. Both the same.

Regards,
Marcus

**Comment by TheSorrow1** [comment]
The issue is not from you, What you can do is to use a older driver in case its critical for you to see the temps/fan speed, you can also use programs such as MSI afterburner to view that as well.

This has to do with the claymore GPU XMR miner, and not nicehash legacy itself. Claymore has replied that he will release a new version of his XMR miner in a week or so with fixed detection of fan and
temperatures and a 5% increase on most cards. Once that is out you can copy it into the bin folder of nicehash legacy and replace the old one or wait for legacy to include it.

Best regards
The Sorrow

**Comment by Paapo** [comment]
Ah OK, many thanks. Will ait..

Regards,
Marcus
