### ISSUE TITLE
Worker name for each individual gpu and cpu

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner#321]
Could we get a feature to allow us to name each gpu and cpu a custom name instead of 1 generic name for the entire miner.

Thanks :)

**Comment by Mystere** [comment]
Since miners themselves aggregate the hashrate, that's not really possible without rewriting the miners.  The best you could do is have a different miner name per miner instance, which most of the time would be a single instance.

**Comment by DillonN** [comment]
@seiterseiter I don't understand the request fully, what names exactly do you want to change? Spitting individual hashrates for GPUs working on the same miner program is not feasible as @Mystere said

**Comment by ghost** [comment]
@DillonN Okay so say my computer has 1 GTX750ti GPU, 1 GTX1070 and 1 cpu fx-8350. Since these are different and run seperate miners for example my current running nicehash says that the 750ti is mining cryptonight and that my 1070 is mining neoscrypt and my cpu is mining cryptonight as well.

So nicehash is currently controlling 3 seperate mining cmd windows. So I could I make it that my gtx750ti reports its name as "GTX750tiMiner" and then my 1070's name is "GTX1070Miner" to nicehash and then when you look on there stats page under "Active workers", those 3 seperate names instead of the generic worker name shown in the nicehash [GUI](https://i.imgur.com/w0tbrt7.png) .

Does that make more sense on what im meaning?

**Comment by DillonN** [comment]
@seiterseiter I understand now, I had misread the title earlier (thinking you meant the display names in the device list on NHML). This is technically possible but you would have to give up grouping miner instances for GPUs (e.g. if the 1070 and 750Ti can both mine the same algorithm with the same miner program, two windows open instead of the usual one). 

This isn't so bad in your situation since you will not get much grouping anyway, but could be if someone is running similar GPUs (e.g. if you added a 1080 it may share with the 1070 often). So some logic would have to be there to group whenever possible and split them off if the user selects a setting to prioritize separate workernames over grouping. 

A little involved but it is something I can look into (at least not changing grouping logic but using different names whenever grouping is not possible anyway)

**Comment by ghost** [comment]
@DillonN Haha sorry about that, im not the best at explaining things most of the time but yeah thats what im meaning, since I mainly look at the stats page and not nicehashes GUI, it would be a lot easier to see which gpu/cpu's are mining what currency just to makes things easier.

Thanks :)

**Comment by ezaruba** [comment]
I am having an issue where my CPU & GPU are both mining on the same machine but it only shows two workers and on my statistics page it shows what my GPU is actually mining (Lyra2Rev2, I think) and my SHA256 Antminer S9. 

However, it's as if it's only mining SHA256 & Cryptonight with my CPU on the workers page. I named my worker using the windows nicehash miner application but it only shows the CPU on the workers page. But on the stats page it shows both the GPU & CPU but the CPU is showing as 0mh/s so I don't even know if I'm earning despite the fact I'm certainly mining with my GPU & CPU when I check my PC.

Does anyone know how I can fix this, or was an update ever made to address the issue being discussed above? 

Right now I'm going to shut off my CPU miner temporarily to see if that makes the GPU miner appear on the workers page instead of the CPU miner & if it helps the issue where the MH/s is showing as 0 on the statistics page for the GPU miner.

**Comment by S74nk0** [comment]
This feature is covered with the [new upcoming platform](https://www.nicehash.com/news/important-transition-to-a-new-nicehash-platform) where per device mining stats are visible.

Closing
