### ISSUE TITLE
Heads up - Windows Defender quarantining NiceHashLegacyMiner.exe 1.8.1.3 as from today

### ISSUE THREAD

**Issue by revaido** [nicehash/NiceHashMiner#340]
I noticed one of my rigs had stalled overnight and after investigating it turns out that after todays Windows Defender updates it is now detecting NiceHashLegacyMiner.exe as Trojan:Win32/Tilken.B!cl and quarantining the file.

The easy fix is exclude the folder that it sits in and then restore the file from the GitHub download.

A quick look at VirusTotal shows many of them flagging up NiceHashLegacyMiner.exe today so I guess this could cause problems for anyone not running exclusions already.

**Comment by xthydra** [comment]
i can confirm that the source isn't dropping the trojan because if i compile from source, windows defender doesn't remove the executable and also avast doesn't detect a trojan dropper from the source

/edit/

 tho yes the latest released executable that someone compiled is actually triggering avast and windows defender as a "trojan dropper"

**Comment by Tailzip** [comment]
Same here, executable is flagged by Windows Defender!

**Comment by RevngeSevnFold** [comment]
Happened to me too. Found my miner with Nicehash gone with just one of the 3rd party script still running.
