### ISSUE TITLE
Nicehash Opens Lots of CMD's then stops responding

### ISSUE THREAD

**Issue by wesleyjayfrisby** [nicehash/NiceHashMiner#351]
My nicehash mines for about 10 minutes but then opens lots of CMD's that causes nicehash to stop 
responding
![capture](https://user-images.githubusercontent.com/16436876/30781485-d494e728-a11f-11e7-9d86-febbcf897dc3.PNG)
[log.1.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1327191/log.1.txt)
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1327192/log.txt)

**Comment by DillonN** [comment]
Hmm, from your logs it looks as though NHML is unable to communicate with ClaymoreDual, and as is standard behaviour after a couple minutes of this tries to restart the miner. However it seems it's unable to kill the old process (getting access denied errors), which causes multiple windows to be made since it still starts a new instance.

I will look for a way to fix this in the code, but could you try running NHML as an administrator which may help it to kill the processes?

**Comment by wesleyjayfrisby** [comment]
Thanks please keep me updated

**Comment by DillonN** [comment]
@wesleyjayfrisby would you be able to try replacing the ClaymoreDual files with the ones from 1.8.1.2? You can download them [here](https://github.com/NiceHash/NiceHashMinerLegacy/releases/download/1.8.1.1-Pre4/bin_3rdparty_1_8_1_1.zip) and extract the bin_3rdparty folder into the main NHML folder, overwriting existing files. (or just copy them from the old folder if you used 1.8.1.2 before)

This could be an issue with the new CD version if you're not getting any problems after doing that

**Comment by wesleyjayfrisby** [comment]
thanks will try it now and let you kow

**Comment by Olegik-ah** [comment]
Hello!
It's not CD issue. Some times (maybe 1 time in month) i'm getting same errors with other algo. I'm running NH from Admin. Logs in attachment.
[log-copy.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1328382/log-copy.txt)
Problem begins from 1.8.1.0 but i cant post logs - because they are overwritten...

**Comment by wesleyjayfrisby** [comment]
tried older CD but same issue, also tried admin but still does the same

**Comment by wesleyjayfrisby** [comment]
Any other ideas/possible solutions

**Comment by Olegik-ah** [comment]
Additional - no errors in system windows eventlog. No GPU driver crash...

**Comment by DillonN** [comment]
Hello sorry for the wait, I have released a pre-release which has the ability to disable the cooldown checker (the system that checks if speeds are 0 and restarts, which is what is causing problems here). This isn't a fix for the issue but it is a temporary workaround until there is one. 

You can download the pre-release [here](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.8.1.4-Pre), update by extracting the folder and copying only the config folder from your old install over. After running it will prompt that miner files are missing, click yes and it will redownload, then do the same again (for 3rd party miner files)

Once it is ready to go, close NHML, edit the `configs\General.json` file. There should be a line near the end starting with `CooldownCheckEnabled`. Change the true to false, save, then open NHML again.

The downside to this is that if miners hang, NHML will not care and not attempt to restart it. However most of the time miners will crash instead of hang, and NHML will still notice a crash and restart the miner with CooldownCheckEnabled set to false.

**Comment by wesleyjayfrisby** [comment]
Thanks will test it through night

**Comment by wesleyjayfrisby** [comment]
i had same problem with new version, but after doing a clean windows install version 1.8.1.3 also works on pc now not sure what the cause was
