### ISSUE TITLE
AVG Antivirus kills main application at launch 

### ISSUE THREAD

**Issue by Horsetoothless** [nicehash/NiceHashMiner#371]
Forget the miner software issues with antivirus Main program
Win32:Dropper-gen [Drp]
Downloads\NHML-1.8.1.3\NiceHashMinerLegacy.exe

and poof it is gone will not let get in to start any mining have address can mine manually but think
issue should at least let you start before downloading eternal miners

**Comment by DillonN** [comment]
@Horsetoothless NHML can be flagged as a false positive by AV programs, see #368 

If i understand you want to be able to start NHML without automatically downloading miner files? You can do this by manually downloading the bin zips from the release page (links at the end of the description), and extracting them in before NHML is first started. However I do not think this would help since AVG is likely removing NHML based on a flag in its database, not how it behaves on your machine specifically

**Comment by xthydra** [comment]
if you compile NHM from source, it will not trigger AWG , Avast or windows defender, it's isnt a false positive.

**Comment by DillonN** [comment]
NHML 1.8.1.3 was removed from the Defender database as a false positive, again see issue #368
