### ISSUE TITLE
All Iterations Closing?

### ISSUE THREAD

**Issue by bmaccafferty** [nicehash/NiceHashMiner#381]
So far, I've tried to download and run all versions  of the legacy version but I will only get as far as the launch where is will start to download miners. Midway through, it will spontaneously close and I will have to launch it again. With the newest pre-release, I made it to the benchmarking screen where it then shut down. With the .3 version though, the program would close and I would try to restart it but one time I tried to restart it and the program disappeared from the folder. 
I have a computer with a AMD RX 580.
Any help is deeply appreciated.

**Comment by luongk** [comment]
Run as administrator if you've unpacked the program to a protected folder, and/or add an exclusion to your antivirus program.

**Comment by bmaccafferty** [comment]
It continues to spontaneously close.

**Comment by juggernautsei** [comment]
I have this same issue and I have spent two days trying to figure out what is wrong. I have run the claymore miner without the nicehash interface and it loads up and runs. Nicehash closes the window after about 30 seconds it appears on the screen. 
I am using 12 MSI AMD RX 550.

[1506894533_log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1347582/1506894533_log.txt)

**Comment by DillonN** [comment]
@Wilted if the program was removed, it sounds as though anti-virus might be interfering? Make sure you've set the NHML folder as an exclusion

For @Wilted and @juggernautsei could you please post your `logs\log.txt` files so I can get a better idea of what is going on in NHML (the file you uploaded @juggernautsei is the output from Claymore Dual running, not NHML)

**Comment by juggernautsei** [comment]
Apologies, @Wilted  Here are all of my log files
[Log_GEN.zip](https://github.com/nicehash/NiceHashMinerLegacy/files/1348681/Log_GEN.zip)
[log.1.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1348673/log.1.txt)
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1348672/log.txt)

**Comment by juggernautsei** [comment]
@Wilted , Maybe this will help:
Faulting application name: EthDcrMiner64.exe, version: 0.0.0.0, time stamp: 0x59a94db0
Faulting module name: ntdll.dll, version: 10.0.15063.608, time stamp: 0x8274fd8b
Exception code: 0xc0000409
Fault offset: 0x00000000000bb91c
Faulting process id: 0x1d78
Faulting application start time: 0x01d33b87b948b5b6
Faulting application path: C:\Users\Miner2\Downloads\NHML-1.8.1.4\bin_3rdparty\claymore_dual\EthDcrMiner64.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: b6907d1a-0861-4a6a-a3e3-4cfae53cf9a2
Faulting package full name: 
Faulting package-relative application ID:

**Comment by bmaccafferty** [comment]
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1350582/log.txt)

**Comment by juggernautsei** [comment]
A buddy of mine suggested that I break down the rig to one card and see if that one card would mine. It did. So, now I am going through the process of adding one card at a time and going through the benchmark and bringing it up to mining status. It worked with one card. I added a second and it worked. I am on my fourth card waiting on the benchmark to complete and see if it will start mining. I will report back shortly. 

This is painful but if this is the way to get it to work then so be it.

**Comment by juggernautsei** [comment]
@luongk  The joy did not last. Two cards will run but with constant restarting. I have an ASRock H110 MB with 4GB RAM and a 600GB HD with virtual memory set to 16000 - 32000MB on windows 10 OS. The cards are MSI Radeon RX 550. I have a similar system with an H81 MB and it is running fine. It is using Sapphire RX 550. 

I switched to Multiminer to see if my rig is junk and Multiminer recognized all 8 cards instantly and starts mining in seconds. But it does not have all the bells and whistles nice hash has.

**Comment by DillonN** [comment]
@juggernautsei from the logs it looks like ClaymoreDual is crashing and NHML is restarting it. The error you posted indicates some problem your system is having with the ClaymoreDual miner itself. Are you able to run it on its own? You can try downloading another copy from the official Claymore links [here](https://bitcointalk.org/index.php?topic=1433925.0)

@Wilted from your logs there is no indication of error. When you say you can open the benchmark window, how long does it stay open before the crash? Do you get to see the device list and such? Also could are you able to open the settings window, and if so navigate to the devices tab?

**Comment by bmaccafferty** [comment]
1) It stays open an average of 2 minutes. 2) Yes, and I try to benchmark my RX 580 and it closes. 3) Is the image.
![2](https://user-images.githubusercontent.com/32426008/31304726-223c4494-aaee-11e7-9fb6-71deb2d08926.PNG)

**Comment by juggernautsei** [comment]
@DillonN  Thank you for the reply. I reloaded the machine with a different hard drive and a clean install. It ran 2 days before starting the crashing thing again. 

I get approx 9.8MH per card. Is that a good speed or is it too slow. Some times it shows a line that says it changing the setting for slow cards.

**Comment by bmaccafferty** [comment]
Another thing that I might want it bring up is that the CryptoNight displays a speed of zero in the benchmark.

**Comment by juggernautsei** [comment]
What I have learned is that the cards need to all have the same speed/clock. If these cards are not clocked in unison, the system will crash. After I loaded afterburner and clocked all the cards the same and undervolted them. The system runs. I am still trying to fix random crashes but it feels like with every fix I put in place the system gets a little better. The conclusion of the matter for me is that it is a hardware issue that presented as a software issue because of a lack of knowledge of how these systems are supposed to work together.  My first rig was a blessing because it just worked. I used Sapphire RX 550 cards in it. This time I bought MSI RX 550 to save a little money. Maybe a bad idea given all the issues trying to keep this miner working. Right now I have four cards working. I am sure that I need to buy new risers again. Out of the 18 risers, I have purchased so far that is all that I can get to work stable. 
Here is a screenshot of my system settings
![msi-settings](https://user-images.githubusercontent.com/834958/31433744-34bfc976-ae48-11e7-9ad5-4256754f6264.png)

**Comment by juggernautsei** [comment]
After this last round of reboot.
Looking at my rig right now the third GPU is hanging up the system. And instead of it rebooting the system it is attempting to reload the miner.

I disabled the bugcheck in windows so the system would not reboot when the driver failed.  

I'll update you when I find out more. I am buying new risers. I think I have a bad set of risers. They are all version 006. I am going to switch to version 006c. Looking for v007 to buy. I suspect these risers don't work well with the MSI RX 550 cards. I have these same risers with Sapphire RX 550 and the system works. 

As I am typing this message the Nicehash system restarted twice and now GPU3 (card 4) is working again. So, no more hard downing the system. It can keep mining as long as it comes back up. 

Thanks for reading!

**Comment by bmaccafferty** [comment]
Nothing has worked so far and I have yet to make it past the benchmark.

**Comment by juggernautsei** [comment]
The new risers came in today and I changed out three of the first ones with the new ones. I have four of the first round that I bought that work. I am trying to run 7 GPU's right now. 
I am having moderate success in that the system can stay online mining for up to a day and then all of a sudden start blue screening. I will not change a thing and just restart it and it may blue screen a few times more then go back to work for another 24hrs. 
Right now I am having the issue with the socket being closed by pool try again 20 sec.
I have found that v002, v006, and v007 risers cannot be mixed together.  I can run the group of cards that are on one or the other but not all together. If I run them all together I get the socket closed error.

**Comment by juggernautsei** [comment]
UPDATE:
The system has been running stable with no reboots or blue screens since running only v7 risers. 
No more software issues. It was never a software issue.

**Comment by juggernautsei** [comment]
Update:
I am still having issues with the rig being stable despite many attempts to change the drivers to the older version and changing the (underclocking) the cards. The cards seem to run best when I underclock them. But the issue is the video driver won't stay stable. I have no idea why. 
I did find out from ASRock that the H110 BTC Pro+ has a limitation in windows to only recognize 8 of the same cards. I wish would have known that up front. I would never have bought the board. I would have stuck with the 6 GPU board instead. 
Right now it seems that the NiceHash software updated automagically. I am not sure what happened. After a reboot, the software came up like it was the first time opening it and asked me for the account information and to agree to the license agreement again. 
This is my second rig and I did not have any of these issues on my first rig with an ASRock H81

Here is what they wrote me:
We have tested with 8 NVIDIA cards in the Windows environment, and it could be detected and worked properly in the system.
Hence, we would like to share some suggestions with the customer.
1. Please test with one VGA card on each PCIe slot to make sure all PCIe slots working individually.
2. Test all VGA card one by one to assure all VGA cards working individually.
3. Test make sure all PCIe x1 slots are connected to the power supply by PCIe x1 to x16 riser card.
4. Install VGA cards on black slots first, and install another two VGA cards on white one.

Let the testing begin!

**Comment by juggernautsei** [comment]
Here is the latest with what is going on with my rig. The NiceHash system switched my rigs from claymore miner to sgminer. I don't know why or how it was decided. However, my second rig that I have been trying to fix here is now working smoothly. It has been operational more than 24hrs. It is now mining Cryptonight with an increase in mBTC/day. Now it is time to build a third rig from all the leftover parts from rig 2. Of course, I am working on building a farm.

**Comment by juggernautsei** [comment]
This will be the end of my story. I have been mining Ethereum for the past month. I gave up windows altogether. Now, I am using simplemining.net. It is a Linux based OS. It took me a few times to figure out how to use it but it is a lifesaver for me. No more pulling my hair out at 2 AM because the windows drivers crashed again after 2hrs. Don't get me wrong the simple mining OS keeps track of the reboots but the system reboots and keeps going. That is the key. The keep going part. Now, I rarely think about my rig being online. I am moving on to my third rig now and will continue to use simple mining OS. Also, a side benefit is that I have doubled my income. I was using nice hash and making roughly $100/mo. Now on dwarfpool.com, that amount is every two weeks. So, I received a win-win all the way around. Thank God!!
