### ISSUE TITLE
NiceHashMinerLegacy crashing during benchmark

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner#384]
After installation 7 GPU (Asus 1080 TI) for the mining rig - while running Nicehash miner OS freezes (and stays unresponsive or get 0x00000133 BSOD).
All 7 GPU are shown correctly in Windows device manager.
All the drivers are updated to latest versions.
Kindly ask you to assist on that matter.
Waiting for your response.

P.S. With 5 GPU it is working with no problems whatsoever. Using nhm legacy v1.8.1.3 and driver 385.69  WHQL. (Windows 10 ltsb 64bit, ASUS x99, 7x Asus Strix geforce 1080ti 11g)
![2017-10-01 17 24 39](https://user-images.githubusercontent.com/2413194/31056761-9e1caa92-a6f0-11e7-9c02-8b6a7f875b9a.jpg)

**Comment by smsforme** [comment]
Here is link for screenshot when nhm crushes OS. https://ibb.co/fGkcqb

**Comment by mesouug** [comment]
I have exactly same problem. Once a day in middle system crashes with 133 error. System is fresh. Drivers are latest. GPUs: MSI 1050Ti x2 and ASUS 1060.
Any way to debug?

UPD:
For those who is interested. Problem was hardware. Faulty power supply. When replaced motherboard it started to reboot every 10 seconds thus means power supply safety switch automatically shutdown power. Because motherboard is good it crashed only once a day.
