### ISSUE TITLE
Automatic selection of parameter dcri

### ISSUE THREAD

**Issue by solandmedotru** [nicehash/NiceHashMiner#4]
Can you add automatic selection of parameter -dcri in running dual miner? Automatically increase or reduce this parameter for max profitability. increase -dcri, look proftablilitym if it bigger then last - increase too, if it smaller then set last -dcri. This selection run each hour or half hour.

ps sorry for my english

**Comment by navjack** [comment]
i love this idea. i guess it could be done easiest with the claymore miner since you can dynamically adjust it while its running.
ccminer and anything else that has an intensity adjustment seem to only be at runtime, i'm not sure how you could automate that except maybe in a way like how the cpu miner runs thru available cores to see which core count is most profitable. but that would only be at benchmark runtime essentially. 

for the dcri i picture it adjusting the value constantly up and then down from i guess either 20 or 30 (sometimes i've seen 15 be the choice number mattering on the algo) until it finds the point where, well in the case of rx480, it drops from 27 OR the profitability goes down (if the 2nd algo being mined is for some reason more profitable at the time)

**Comment by DillonN** [comment]
This is definitely an idea that has been floating around. While there are currently no set in stone plans for it, I will update if that changes

**Comment by fefsf** [comment]
Hell yes, this idea is amazing

**Comment by XBrav** [comment]
I looked into the ways of doing this. It's more of a question of how far NH and DillonN want to go into it.

Basically, EthDcrMiner64 does not expose the hash rate of the secondary values when benchmarking. As a result, there's a workaround where you actually are mining during the benchmark (Thanks for not putting your own address in there!). So, even though messing with the DCRI values can take a long time to determine a nice value, it would still generate a little profit.

Now, with that in mind, thanks to claymore_dual being closed-source, the only feasible way to do it would be as follows:

1) Cycle through all the DCRIs (maybe benchmarking precise at an increment of 1, 3 at standard and 10 at quick), either through:
a) Spawn a new process at each DCRI for a certain time period (longer), or
b) Manipulate the EthDcrMiner64 session starting at zero and "virtually" hitting the + key (like AutoHotKey).
2) Change the profitability check to validate each result as its own miner.

The only issue I see is making sure NHML doesn't flip between the DCRIs too often, resulting in lower return rates thanks to the ramp up time in firing up the algorithm.

**Comment by Varjo1** [comment]
This would be great! I don't think overthinking it makes sense. Just offer a 24hour "mining benchmark" option that cycles through increments of 10 DCRI for common miners.

After benchmarking these can be used to estimate profitably and miners with dynamic adjustment can be tweaked online (think gradient decent, the shape of the function is nice and smooth after all).

**Comment by DillonN** [comment]
Implemented in 1.8.2.0
