### ISSUE TITLE
RIG Chash - Need to power off to restart.

### ISSUE THREAD

**Issue by MatuKing** [nicehash/NiceHashMiner#421]
Hello, I have a problem with the nicehash program, I have a RIG with 2 RX570 boards and 5 RX580 boards and when I go under the program and I run it, it turns out that the PC hangs up, the only thing I found to make it work is to disable the option to use third-party programs, when removing that option the PC works correctly, wanted to know if you can help me with the topic, because I would like it to work with all the functions of your software.

**Comment by Nikko85** [comment]
Does your problem match mine?
https://github.com/nicehash/NiceHashMinerLegacy/issues/422

I tried disabling Third party miners like you said but ended up with only sgminers which won't do because I can't benchmark them...

**Comment by MatuKing** [comment]
If it seems to be the same problem, my boards have passed all the benchmarks so the sgminer works for me and I'm mining CryptoNight as the only option. Do you have configured the virtual memory of the PC? That is necessary.

**Comment by Nikko85** [comment]
Yeah i just checked and we put 40K Virtual memory when we first set up the rig. I've tried benchmarking the sgminers again though to see if it works and it did. Can you dual mine with Crypto? Like if I take Crypto (Claymore) and Equihash (Claymore) I should be able to dual mine right? Cuz i've tried it ans I get like 5,50$ USD/day instead of 8-9$. Plus I got no clue if it's dual mining since the command prompt windows doesn't say much...

**Comment by DillonN** [comment]
See comment on #422
