### ISSUE TITLE
ETH+LBR 25Mhs / ETH+SIA 30Mhs

### ISSUE THREAD

**Issue by RodAus** [nicehash/NiceHashMiner#449]
Hi when I double mining ETH+LBR, is limited to mining 25MHs while ETH+SIA or PAS reached 30MHs this is a limitation of NS pool? I have the same results in others miners.

**Comment by DillonN** [comment]
You can likely change this by lowering the dcri value for LBC dual miner. There are details at the bottom of [this page](https://github.com/nicehash/NiceHashMinerLegacy/wiki/Tweaking-ClaymoreDual-Intensity)

This will lower the intensity with which ClaymoreDual mines the secondary coin so that you get higher Ethereum speeds

**Comment by RodAus** [comment]
There was no effect on the limit of 25MHs, several levels were tested. I started use decri 6 months ago
