### ISSUE TITLE
Exactly same rig but very different results 

### ISSUE THREAD

**Issue by RodAus** [nicehash/NiceHashMiner#450]
Hi, usually they are quite equivalent but especially today the difference is very large. I have exactly 2 rigs mining the same coin but the ratios even get close, what its could be? (afterburner settings are the same,  GPU speeds are compatible with usual speed) . After 1 hour one rig is mining DaggerPascal, and other rig Equihash which is much more profitable according to Whattomine. I restarted , reinstalled drivers, mine reinstalled, new benchmark, nothing solved. UTC time 6:32 pm Friday, 20 October 2017

Please take a look at the screenshots 
![capture11](https://user-images.githubusercontent.com/31544552/31836447-1bfe5110-b621-11e7-8d5e-8ecf612be3ac.JPG)
![capture111](https://user-images.githubusercontent.com/31544552/31836453-20996ad4-b621-11e7-84cb-eb85857a8395.JPG)
![capture1111](https://user-images.githubusercontent.com/31544552/31836458-231141f6-b621-11e7-8ac6-0cbb9a11b523.JPG)

**Comment by DillonN** [comment]
In your first screenshot, it looks as though the two clients have different profitabilities set for Equihash (the ~2-3% in hashrate is not enough to cause that disparity for profit rate). This can happen if one has been opened longer than the other. NHML has a feature to normalize profit spikes to prevent falling victim to some buyer manipulation (more info [here](https://github.com/nicehash/NiceHashMinerLegacy/wiki/Profit-Normalization)). This feature does not kick in until around half an hour of being open. 

If you've tried having both of them open for a while (at least an hour), then there may be some error that is preventing one of them getting proper profits. In that case could you please upload the logs\log.txt files for each so I can see if this is the case?

**Comment by RodAus** [comment]
Interesting, Yes, after about 45 minutes they returned to normal. But hardly the application stays alive and with health for more than 24 hours, I have a routine to restart it before bed and when I wake up.
Most of the problems seem to occur when there is an exchange of miners. Is there any project to standardize the miners? Thank you

**Comment by RodAus** [comment]
Is happening again, both are mining at 24 hours.  Could you have a way to change mining manually, so I can check on Whattomine and change it.
UTC Time 11:18 pm

![capture2](https://user-images.githubusercontent.com/31544552/31856658-4a7a58f8-b712-11e7-9a14-b0b8b41e8a9d.JPG)
[nvidia1.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1404548/nvidia1.txt)
[nvidia2.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1404549/nvidia2.txt)

**Comment by Paapo** [comment]
Just go to the settings Tab and choose algorithm. Then disable Neoscrypt for any CPU and GPU and just leave the most profitable algorithm checked. There you can choose manually wich algorithm you wanna mine.

Regards,
Marcus

**Comment by RodAus** [comment]
@Paapo I've been doing this, but sometimes the disabled algorithm is actually the most profitable so I have to re-enable it. It's a huge job since it's 16 gpu and around 16 algorithm each so ~256 tick boxes to enable and disable . It would be interesting an option to disable/enable algorithms in a global way. Thanks for the advice.

**Comment by DillonN** [comment]
@RodAus the logs you sent cover ~12:20 - 12:48 your local time, but there are periods where one will mine Equihash while the other NeoScrypt. NHML only receives updated paying ratios every ~2.5min, and will only check for new profitabilities based on the switch time set in the settings. In these cases it looks as though one is spending a couple minutes remaining on NeoScrypt simply because it has not received the updated spike in Equihash paying rate that the other already received.

These spikes happen often and it is usually a good thing switches do not happen immediately, otherwise there would be too much switching (wasted downtime) and spikes can go away quite quickly, leaving you on a lower paying algo before an update comes through. Even if the upward spike stays high, a couple minutes delay will not be too much over a long time period

Currently the easiest way to make global changes would be to disable the ones you want on one device, and copy them over to the others (right click on the other devices). I agree this could be made easier in an update though

**Comment by RodAus** [comment]
@DillonN Thank you for clarifying. 
I always take care of the downtime process and if the spikes are really profitable. 
If the exchange for BCT is fast enough or if there is some kind of record at the moment of the mining. (I do not know how the exchange process is done) Yes it is profitable, so I prefer to keep them for now.

These issues seem to be quite punctual when NS is making adjustments.
I'm excited to start mining BTG!

**Comment by DillonN** [comment]
Glad it's working out

I'll close this issue now
