### ISSUE TITLE
Extra Launch parameters

### ISSUE THREAD

**Issue by nn111** [nicehash/NiceHashMiner#454]
Nicehash Miner Legacy 1.8.1.3
Why are my Extra Launch parameters not working ? 
Extra parameters :
"-fanmin 40 -tt 66 -tstop 72 -cclock 1060"
<img width="554" alt="screen shot 2017-10-20 at 13 52 20" src="https://user-images.githubusercontent.com/32977277/31849778-b6440812-b650-11e7-8b48-62e1f5941e59.png">

**Comment by DillonN** [comment]
Make sure you have "Disable AMD Temperature Control" unchecked in the General tab

**Comment by nn111** [comment]
@DillonN  Nope DillonN than isn't it ...

**Comment by DillonN** [comment]
Could you post your logs\log.txt file please?

**Comment by seiferflo** [comment]
Hi. I'm also having issues with Launch parameters not making any visible change. 
Looking at debug, I get "Cannot parse "-i", not supported," to all pamameters I try to input.
This is using Cryptonight (ccminer) for GPU. 
Problem is I'm half the Hashrate I normally do with that same miner because I need to tweak with intensity, threads & blocks.
