### ISSUE TITLE
Keccak Mining Issue - Binding Thread

### ISSUE THREAD

**Issue by Micster001** [nicehash/NiceHashMiner#467]
Hi Guys,

As of 48 hours ago I have started to have a Keccak mining issue for some or other reason

![keccak mining issue](https://user-images.githubusercontent.com/33043324/31917671-4bb0f63a-b88b-11e7-91ad-824e150a2686.jpg)
My system is a Windows 10 64bit and I'm running GXT 1070 GPU's using NiceHashMiner-1.8.1.4-Pre3

Initial after install It would retry for 6-10 attempts and then start mining, however now it just retries for as long as Nicehash wants to mine Keccak. Obviously no earning in this time which can be up to a couple hours per day

Is anyone able to shed in light on this issue?

help would greatly be appreciated

**Comment by DillonN** [comment]
It looks like Keccak is not playing well with this version of ccminer and your GPUs, you can try [changing the  path](https://github.com/nicehash/NiceHashMinerLegacy/wiki/Customizing-ccminer-and-sgminer-paths) to one of the other versions. Also you could try turning off CPU mining/lowering CPU intensity since that could interfere with GPU miners if CPU is at 100%
