### ISSUE TITLE
Noob Problems

### ISSUE THREAD

**Issue by perryismyname** [nicehash/NiceHashMiner#474]
Hello I am new to bitcoin mining and am running in to several problems. I have a laptop with a decent CPU and a semi decent nvidea graphics card. I got nicehash 2 to run fine on the laptop but I am now trying to get nicehash miner legacy to run on a separate desktop that I have that has an AMD CPU and GPU and I am running into nothing but problems. First off all please forgive me if I forget something as I do not know the terminology or how to add the proper things. Note that I have avast and windows defender on my computer but both are completely turned off.
      My desktop is fairly new and has an AMD A6-6310 APU with AMD Radeon R4 graphics CPU and a AMD Rageon(TM) R4 Grphics GPU. (Note full specs at bottom) I have run in to several problems when I try to benchmark or run both of these. I will start with the bench marking problems. I can benchmark the CPU just fine and it results in a measly 4 cents a day... we'll get to that later. For now the Gpu barely benchmarks. most all of the benchmarks either say "terrminated" or "Failed try precise" despite me canceling nothing and attempting it on precise. Is there a problem with the software? Am i doing something wrong? 
      Now time for the problems encountered while running. As far as I can tell there is only one algorithm to run my CPU and it benchmarks at 29 H/s and generates .00000787 bitcoins a day which is 4 cents. That seems pretty measly to me, is that an actual representation of my CPU? Or is something not working? I would think that i would at least get something basic like 10 cents a day which is still hardly anything. Next is the graphics card. It is a decent graphics card but it has many problems. Most of the benchmarks fail to complete properly and the ones that do only generate 2 to 3 cents a day.... That disappointed me severely. But that is just the benchmarks both the CPU and GPU don't even appear to actually generate anything. When I try to run the CPU alone it says "socket error - receive error: socket closed  Pool connection lost. waiting 10s before retry (attempt 47)" (I am sorry I don't know how to copy from the bin, how do I?) When I try running the GPU alone it runs in to several different problems, when I run it with the few working algorithms several weird things happen. I realize that different algorithms will say different things that's why I am having a difficult time explaining this but either way it produces 2 cents a day. Is that accurate or what am I doing wrong? Thank you for dealing with my noob-ness but any help about any of this would help me a lot. I have tried watching many tutorials but i never see anything as spastic as this. Plus everyone you can watch is using the newest of the new GPUs and so it doesn't translate very well.
Full details that I think are important that I a running
Nicehash miner Legacy V1.8.1.3
Graphics card: AMD Radeon(TM) R4 Graphics 1.8GHz
windows 10 home
64 bit 64x based processor

**Comment by bonifacio123** [comment]
CPU's with embedded GPU's are not powerful enough to efficiently process crypto functions. They lack the memory and shader's to get the work done to benefit you. If you manage to get it to work you'll probably spend more money on power then you'd make in profit.

As for Cryptonight - your profit is dependent on how free your CPU is. If you're running other things your hashes/sec will drop resulting in lower rewards for you. Also, it seems your CPU support AES and xmrig requires AES-NI. Not sure if these designations mean the same thing. Check out the git repo's for these miners - study the details they have provided:

[https://github.com/fireice-uk/xmr-stak-cpu/releases](https://github.com/fireice-uk/xmr-stak-cpu/releases)
[https://github.com/xmrig/xmrig](https://github.com/xmrig/xmrig)

Visit this site to properly set your expectations on profits: 

[https://www.nicehash.com/profitability-calculator](https://www.nicehash.com/profitability-calculator)

If you don't know your cost of power per KW then use .10 as a starting point.

**Comment by DillonN** [comment]
@perryismyname, as @bonifacio123 has said the GPU component of your APU is not very suited for mining. It will show up as compatible since at a basic level it works the same way as AMD graphics cards, but it will likely fail in most algorithms and perform poorly in the ones that work.

As for the CPU mining, again it is not a very powerful CPU and if I had to guess I would say 29 H/s is a little slow but not by too much (I would guess ~40 which isn't a big improvement). 

The reason you're seeing the socket errors is due to the STRATUM connection protocol that miners use - if no share is submitted in 10 minutes then it will disconnect and attempt a reconnect shortly after (10s in this case). Since you are mining slowly you will probably not be submitting shares in less than 10 min intervals so this disconnect happens. Even powerful CPUs that can get 300 H/s will get this error relatively frequently

Unfortunately to be profitable mining (after taking power costs into consideration) you need a more modern/beefier CPU and/or a dedicated graphics card
