### ISSUE TITLE
AMD DH8490 Benchmarked but not Mining

### ISSUE THREAD

**Issue by PalipCs** [nicehash/NiceHashMiner#482]
HI

VErsion: 1.8.1.4 Pre-release 3
Win: 10 Home 
Cpu: Intel i5-3570 @ 3.40GHz
GPU: ADM Radeo HD8490

Problem:
Benchmarking when well., 2 algos left out
However the GPU is not picking up anything, it is stacked on Keccak and not gaining any value.

Can somebody please advice what to tune to move it a bit.

Thank you for your time. 

[log.1.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1421711/log.1.txt)

**Comment by DillonN** [comment]
@PalipCs is the issue only with Keccak, does it work if you disable it and try mining something else?

From your logs it looks as though this is a hashrate reporting problem though. Over long-term the miner is reporting an average of ~17MH/s (the same as benchmarked speed) but frequently the immediate hashrate drops to 0 (NHML reports the immediate hashrate). In a reporting problem like this it is best to go by the average hashrate overtime reported on the NiceHash website (hit the Check my miner stats link), since that is what you will be paid on. Try leaving it for an hour or so and see what it says on there

The 8490 is not well suited for mining unfortunately, it is a rebranded 6450 from 2011 (but with better clocks/VRAM) and won't be profitable with current mining when you factor in power costs. Even if Keccak were working you'd only get around $0.04/day according to the benchmarked speeds

**Comment by PalipCs** [comment]
Hi Dillon

Thanks for your answer. The issue with the GPU seems to be just with the Keccak.
Not a big issue, just started learning about this and experimenting with my comps oin the office.
At the same time Ive ordered a Baikal Cube 600, will see how that boy will preform.
