### ISSUE TITLE
Claymore's CryptoNote (CryptoNight) on R9 380 2GB

### ISSUE THREAD

**Issue by RealityRipple** [nicehash/NiceHashMiner#485]
Having trouble with the latest version, both CPU and GPU.

CPU problem is that the hash rate keeps resetting to zero in the NHML GUI while I'm mining. It shows the rate for a bit, then goes back to 0 again. AMD FX 8370. No OC. xmr-stak-cpu.

GPU problem is the big one that really matters. The new version of Claymore doesn't seem to like my XFX R9 380 2GB card. When I start, it says:
`OpenCL error 0 #101 - -61, cannot create GPU memory buffer`
and then it just... does nothing. The CLI output acts like it thinks its mining, but with a 0 hashes a second rate. I tried running it manually and setting the memory to normal instead of double since it's only a 2GB card, since for some reason it won't pass that command through NHML (guess that's another bug), but it didn't help. Even with the lower memory allocation (1890MB), there was no mining. Temps didn't change, wattage usage didn't change, but the miner didn't seem to notice it wasn't mining.

For reference, [here's the benchmark log](https://github.com/nicehash/NiceHashMinerLegacy/files/1424545/1509209388_log.txt)

I'm able to run the old version just fine by command line, so for now, I'm using the miners through batch files instead of using NHML. I'd suggest an "old version fallback" command line parameter or checkbox or something so users can choose which version to use in case of other compatibility issues.

**Comment by DillonN** [comment]
It seems support on the new Claymore CN miner is spotty. There is fallback on the old version for some newer cards [Claymore didn't list as supported](https://bitcointalk.org/index.php?topic=638915.msg22374404#msg22374404), but he lists Tonga as supported (380 is Tonga). 

I can look into adding a manual override to force the old version, but Claymore did say support will be fixed in a new version so hopefully that comes out 

Regarding the CPU, how does the hashrate look in the CPU miner window? It should report hashrates every minute or so, or you can hit 'h' to have it report. If hashrate is looking good there then it is probably just an error between NHML reading them

**Comment by RealityRipple** [comment]
It's probably got something to do with most 380s being 4GB models... I don't mind using the CLI for now.

The hashrate looks mostly normal... except I don't think it used to say (na) for the times it hasn't reached yet. I'm guessing you have it set up to read the 15m column? That'd do it...

**Comment by DillonN** [comment]
It should be reading all three columns and pick the first one that has a value (which would almost always be the 2.5s value). I'll look into it

**Comment by RealityRipple** [comment]
Guess I'll count this as fixed. XMR is showing its stats correctly, the old Claymore EXE is accessible and works fine, and nothing exploded in my face. Thank you!

**Comment by Listerstorm** [comment]
RealityRipple, hi there!
A have the same GPU and the same error. How did you solve the problem? Didn't understand.
