### ISSUE TITLE
Internet lose from storm (No power lose to computer)

### ISSUE THREAD

**Issue by cfDroid** [nicehash/NiceHashMiner#50]
This morning I had noticed the miner had stopped via checking my phone and when I went to check the computer the was a dialog box saying the miner needed internet connection to work. I had to hit the OK button for it to continue, after which it, immediately started. Is there a way to prevent that dialog box from appearing so the miner can continue on it's own automatically once the internet connection is reestablished? Thanks!

**Comment by drkskwlkr** [comment]
@cfDroid: There are two things you should do to allow unattended operation.

1. Click on 'Settings' and check `Disable Windows Error Reporting`.
2. In the same panel make sure `Idle when no Internet access` is enabled.

Also, please note that unless you have done both and the problem persists, this is not an issue with the program but a 'how to' question. For 'how to use' cases, you are kindly invited to use the [NiceHash Bitcointalk thread](https://bitcointalk.org/index.php?topic=562238.0) or the [NiceHash subreddit](https://www.reddit.com/r/NiceHash/). 'How to' questions are not considered problems with the software that require the opening of Github issues.

The developers and contributors for each project are usually subscribed to receive all updates in order to provide timely support and maintain the software properly. Every non-issue like this one causes unnecessary distraction, wastes valuable time and generally annoys the very people to whom you and others rely to get free money from mining.

Please respect the time of other users and use GitHub responsibly :)

**Comment by cfDroid** [comment]
Thanks very much and apologies for using the wrong forum. Noob problems.
