### ISSUE TITLE
Pool with Problems ???

### ISSUE THREAD

**Issue by CAVACO-PT** [nicehash/NiceHashMiner#500]
Hello , are the pools having problems ??? , they are doing timeouts a lot , and i see (FAILLOVER 1 and 2) , and then they try to get to main pool , these past days all the pools keep going down and coming up a few times , is anyone else having problems ??

its not the connection because i have miners in different internet connections and locations and they all do the same thing 

![image](https://user-images.githubusercontent.com/9946471/32267591-abf7aa4e-bee3-11e7-81ed-9131417274d6.png)

**Comment by CAVACO-PT** [comment]
![image](https://user-images.githubusercontent.com/9946471/32268882-9e7fd0c6-bee8-11e7-8f7b-629b5cd4a93f.png)

**Comment by CAVACO-PT** [comment]
![image](https://user-images.githubusercontent.com/9946471/32270160-a97ca720-beec-11e7-9fb6-66f8daab5915.png)

**Comment by Ithan74** [comment]
I have the same problem((

**Comment by pjmt** [comment]
I get the same connection problems on the cryptonight.eu.nicehash.com, mostly around this time of day.

**Comment by DillonN** [comment]
Unfortunately this seems like a connection/pool problem so not much can be done here

Best way to troubleshoot if it's a connection problem is to try disabling firewall or use another internet connection if you are behind a corporate/university connection

**Comment by CAVACO-PT** [comment]
@DillonN  has i written in the issue , its not a connection problem , because i have multiple diferente miners in diferent providers in diferent locations , and a few i disabled the firewall , and all from diferent internet providers do the exact same thing ,  its ether a routing problem ... the routes that take each client to the pool , or the internet pool provider is having issues ,  both problems its nicehash that has to tell their internet provider of the EU pool that the problems exist .. not us the users

**Comment by CAVACO-PT** [comment]
i will try to connect a few miners to usa pool and we will see when the eu pool goes down again if the usa connection doesnt go down its for sure a problem of routes or pool internet provider of eu location !!!

**Comment by VadimEv** [comment]
@DillonN that is not a connection issue. I experience exactly the same problem on multiple endpoints with different channel setups. 

![stratum_errors](https://user-images.githubusercontent.com/10043733/32313707-4c75d87a-bfb5-11e7-9059-c0cee3f466e7.png)
![nicehash_stratum_connection](https://user-images.githubusercontent.com/10043733/32313773-8c539fb8-bfb5-11e7-926f-b4e86d231e77.png)

Since I use mining listener batch, rigs restarting after 240 secs of inactivity which is not so good. Maybe there is a way to limit reconnection attempts to 5 for example and if it fails temporary disable algorithm used so it wont keep knocking to the door closed tight and restarting in vain.

**Comment by DillonN** [comment]
It IS a connection problem, but that does not necessarily mean it is a connection problem on your PC/internet. Just that at some point the connection between the miner program and the server has a problem. 

Again, this is not an issue with NHML but one of any the miner/network/server
