### ISSUE TITLE
Cant run new versions 1.8.2.0 and 1.8.1.4 due to windows defender smartscreen.

### ISSUE THREAD

**Issue by mandeep148** [nicehash/NiceHashMiner#509]
hi, im using pre release of 1.8.1.4 3rd, i downloaded both latest version that is 1.8.1.4 and 1.8.2.0 , i cant run those, when i try to open i only have option showing "dont run" i tried to disable windows defender, 
so what should i do now.
![screenshot 17](https://user-images.githubusercontent.com/30183847/32318737-27b4133e-bfde-11e7-9c30-f71ec32b416d.png)

**Comment by DillonN** [comment]
You need to go to the Windows Defender settings and configure SmartScreen to be "Warn" instead of "Block"

![image](https://user-images.githubusercontent.com/5328577/32403306-c9da1cd8-c10c-11e7-9981-c1ca128a414a.png)

After that, that popup will have a "more info" button which exposes the "Run anyway" button

**Comment by mandeep148** [comment]
@DillonN
Thanks for help,
Sorru but in dont think i should put my whole computer at risk just because of nicehash, dont you think you should improve or approve the software or whatever?

**Comment by drkskwlkr** [comment]
> Sorru but in dont think i should put my whole computer at risk just because of nicehash, dont you think you should improve or approve the software or whatever?

You annoying, computer illiterate, entitled person...! The only thing that puts your computer at risk is you. Dillon and others spent so much time helping you out with your silly questions and yet you have the temerity to throw snide remarks and boss the dev team around?

Changing SmartScreen behavior from Block to Warning is so much better than disabling Windows Defender as you thought to do. It does nothing to decrease security because you still have to approve every warning Windows Defender issues.

Had you spent at least as much time studying how Windows Defender works as you did complaining here about everything you couldn't figure out (that means everything), you would have known that you only need to confirm this change once each time after updating the version of the NiceHash executable, and switching back to Block after approving NiceHash would work for you.

**Comment by mandeep148** [comment]
I meant to said, i would stick to old version, till they fix problem, i
cant change settings to warn mode from “block” i have costly data and i
used to run many pendrives on this mining setup.

**Comment by mandeep148** [comment]
@drkskwlkr for 1 second i agree what you said,
you are telling 

"annoying, computer illiterate, entitled person"
to your and all parents and all those person who are only using Pc for accounting..
everyone dont have all knowledge, i bet you dont even know how pc architect work, first of  all your nothing without GOOGLE, look at your mouth, you look like you have Glue-ed youself with computer screen... you have no sense of how to talk...

Second thing i meant to said at first reply, was i will use older version, once issue get fixed... my kid can even install unknown SOFTWARE, i just cant revert settings to 'WARN". thats my choice..
