### ISSUE TITLE
Claymore cryptonight

### ISSUE THREAD

**Issue by nin3tin** [nicehash/NiceHashMiner#523]
Claymore cryptonight hangs on r9 Fury GPU, if i ran old version it works perfectly.

is there a way to make r9 use old version while RX uses new version.

im using 1.8.2.0 i know its not official but you might want it to include in benchmark old and new claymore for r9 users.

**Comment by snowcrawl** [comment]
The way that I am doing it is to run both the current version for my non R9 cards, and an older version on which the R9 worked for CryptoNight.   You need to unclick the R9 under devices so that it does not run in the current edition of NiceHash Miner Legacy.   Then you need to unclick all of the non R9 devices in the older version of Nicehash miner so that only the R9 card will run with that instance of the program.   So basically you have two separate instances of the software running.   I figured out that this worked long ago, whenever an upgrade would come along, and I needed to transfer some piece of information from the old version the the newly downloaded version, such as the Bitcoin wallet address.

**Comment by imrecsoka** [comment]
Snowcrawl, i didnt follow much of that :) screen shots?

**Comment by nin3tin** [comment]
he means to use use 2 versions of NHML, one using the latest claymore crypto the other using the old version. Disable r9 in the new version and to the old version only enable r9 the rest are disabled.

**Comment by nin3tin** [comment]
im using 1.8.1.2 no problem and the speed is the same anyway. so i dont mind using old version.

**Comment by DillonN** [comment]
1.8.1.5 is out, you can decide which ClaymoreCN version you want to use in it

https://github.com/nicehash/NiceHashMinerLegacy/tree/1.8.1.5
