### ISSUE TITLE
sgminer fails to launch with a specific GPU combination (works in standalone mode)

### ISSUE THREAD

**Issue by fonyo** [nicehash/NiceHashMiner#548]
Due to my cards have very different results in benchmarks, NHML tends to assign them different algorithms to mine, sometimes even 3 separate ones.

I have the following set-up with one of my rigs:
GPU0 RX 480 8GB
GPU1 RX 480 8GB
GPU2 RX 580 8GB
Driver 17.7.x
Win10 pro 64 bit
Latest NHML

Everything works well when they all mine the same algorithm, or they mine 3 different kinds of ethash+dual combos BUT there is one case which comes up often and makes mining fail on two cards.
GPU1 is assigned dual ethash usually (works well) and GPU0 and GPU2 are assigned sgminer cryptonight. At that point sgminer pops up, tries to load and quits after a few seconds (before fully loaded and mining starts) and NHML tries to relaunch it indefinitely or until this combination is not profitable anymore.

I tried to recreate this issue by launching a config involving GPU0 and GPU2 only and sgminer worked as intended mining cryptonight therefore, I think this could be an NHML issue.

**Comment by doverosx** [comment]
What do you see in logs.txt?

**Comment by bmazz731** [comment]
I'm having the same issue on NHLM 1.8.1.4 - #534 

Hopefully, we can get some feedback on the issue soon!

**Comment by fonyo** [comment]
Took me a while but I managed to catch it.
[errorlog.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1453675/errorlog.txt)

I obviously changed the address and worker name.

**Comment by DillonN** [comment]
@fonyo NHML is passing the correct values to sgminer so if you are able to launch it properly manually the problem will be hard to find. A while back I tested another sgminer fork, and it was the same issue - would work fine manually but launched within NHML it would restart before showing anything (even with identical parameters). Ultimately I didn't look into it since it wasn't useful anyway, but this could be a similar issue. 

For now you can try changing the sgminer path used, to the other type for that algorithm (see [here](https://github.com/nicehash/NiceHashMinerLegacy/wiki/Customizing-ccminer-and-sgminer-paths)), or different values for hide mining windows.

**Comment by mandarb** [comment]
I have the same issue. The nicehashminerlagacy tries to set 4 gpus mining eth using claymore and 2 mining cryptonight using sgminer and sgminer keeps restarting. I checked the logs and the problem is identical to the one @fonyo is having. I have tried to start sgminer manually using the correct values and it exits with no error message.

Here are the arguments being passed to sgminer accordering to the log (changed address and worker):
--gpu-platform 0 -k cryptonight --url=stratum+tcp://cryptonight.eu.nicehash.com:3355 --userpass=<wallet.worker> -p x  --api-listen --api-port=4003  --keccak-unroll 0 --hamsi-expand-big 4 --rawintensity 512,512 --worksize 4,4 --gpu-threads 2,2 --remove-disabled --device  0,5

I also tried changing the path to sgminer-5.6.0-general with the same result as for sgminer-gm

**Comment by bmazz731** [comment]
Although not ideal in case anyone needs a workaround for the time being - I copied my benchmarks for all my AMD cards to ensure that my RX 470s and 2 RX 580s will run the same algos to prevent sgminer for failing to start in a continuum. 

I did notice the following "Application Error" in Windows Event Viewer when sgminer is failing to launch - has anyone else received the same error?
```
Faulting application name: sgminer.exe, version: 0.0.0.0, time stamp: 0x58b364ad
Faulting module name: amdocl64.dll, version: 22.19.677.257, time stamp: 0x59c57bf4
Exception code: 0xc0000005
Fault offset: 0x000000000049e346
Faulting process id: 0xc0
Faulting application start time: 0x01d35b4e3955d778
Faulting application path: C:\Users\<User>\Desktop\NHLM 1.8.1.3 - Copy\bin\sgminer-gm\sgminer.exe
Faulting module path: C:\Windows\System32\DriverStore\FileRepository\c0318486.inf_amd64_11ba0b4b7cc81d52\amdocl64.dll
Report Id: 9e866261-076a-4005-8bb9-31c05710267f
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by tazna** [comment]
I got the same error on NHLM 1.8.1.5.
I'm using blockchain driver(23.Aug).

**Comment by fonyo** [comment]
Just to point out to rule out: I am not using the blockchain compute driver.

**Comment by fonyo** [comment]
Any ideas what could be done by the user to fix this in the short term? My suggestion for the long term would be splitting sgminer to run separately for each device instead of bunching up the cards together.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
