### ISSUE TITLE
Mining not stable, GPUs' fans RPM to zero, heats up and systems fails

### ISSUE THREAD

**Issue by matatan08** [nicehash/NiceHashMiner#554]
I'm new to NHML (using 1.8.1.5), rigs have been 100% stable with Claymore v9.7. While testing out the miner yesterday, a couple things have occurred: firstly, benchmarking seems to take a long time, like 3-4 hours on "quick", didn't even bother to test out "precise", is this normal? Running Crimson 16.9.1 on 6 x AMD RX470's. Secondly, after performing ping tests to the different stratum servers, I chose the best one and still (my connection is super stable with very low pings) "connection interrupted" appears a lot with few but some stale shares. I see a lot of threads with the same issue so this one is not to be handled here but wanted to mention it. Thirdly, and most important, the miner just isn't stable. It mines fine until I see a problem with one or two fans' RPM dropping to ZERO. I open Sapphire Trixx and indeed its conflicting with something because I have all my fans fixed to 70% and two appear at 0%. If I close miner, goes back to normal. In settings I have ticked the disabled AMD Fan settings which I tried Unticked and the fans would go to 35%, when I tick disabled, back to my fixed 70%. This is the most concerning since GPUs are overheating and systems crashes due to temp protection.  Wait to hear back from you guys, thanks.

**Comment by matatan08** [comment]
One more thing, just to get it straight. There are 3 different NiceHash miners correct? NHML, NiceHash miner 2.0 (can't find the download link anywhere and seems for beginners), and the sole SgMiner that all of the above base themselves off of but has no friendly interface. Is that right?

**Comment by DillonN** [comment]
@matatan08 benchmarking can take a long time for AMD. If you have multiple identical GPUs, it's recommended to benchmark on one then copy the settings over to the others (you can right click on the GPUs in the benchmark window to do this). 

The connection interrupted issue has been posted a lot as you said, it is a server side issue due to CryptoNight popularity right now though and not relevant to NHML

There are only 2 official miners for NH, NHML and NHM2, sgminer is an open-source miner that is included with NHML. NHML includes many community miner programs (like Claymore), NHM2 relies solely on the NH-developed Excavator miner (NHM2 provides a UI for Excavator). 

For your fan issue, many miner files included in NHML are capable of setting the fan speeds as you found out. None of these options should be used if you tick the disable AMD temperature control option. Could you post which specific miners you are having this issue with, and your logs/log.txt file so I can make sure no options are being passed?

It is possible a miner program is buggy and setting fans to 0 without being told to. This is outside the scope of this forum, which is for issues with the NHML only
