### ISSUE TITLE
profitability line "who broke it?"

### ISSUE THREAD

**Issue by jimmyhackers** [nicehash/NiceHashMiner#561]
The profitability line and corresponding graph has lost a lot of functionality :(
This means i cant see whats happening with my miners anymore.

not happy :(

is a this temporary glitch or is nicehash trying to cut costs on their service?

**Comment by github12101** [comment]
What are you talking about? If would be nice if you say exactly WHERE is the problem and HOW TO REPRODUCE it. So other users can verify, add credibility to your report.

**Comment by Crypto-Lord** [comment]
Sounds like this is a NH issue not a NHML issue.

**Comment by Rickochey** [comment]
For the last 12 hours-ish, NHML 1.8.1.5 bottom line profitability and balance is showing currency figure @ USD rate regardless of what currency I set it to show.

**Comment by DillonN** [comment]
@jimmyhackers this sounds like a NH problem, this forum is for NHML problems specifically

@Rickochey yes I noticed this, it's because the API server has been returning no exchange rates so NHML falls back onto the USD value (which is the original number used for all exchanges). If you look in your log you'll probably see lines like `[10:15:22] [CurrencyConverter] Unable to retrieve update, Falling back to USD`. In the future I'll look into making it more clear that the currency shown is actually USD when this happens

**Comment by jimmyhackers** [comment]
sorry for not being clear, this is a problem with he nicehash service not NHML. (i think)
to clarify....
after clicking view my stats the graph that shows all mining and profitability is not how it should (or used to) be.

if i deselect one of the currencies ive been mining....the black profitability line stays unchanged whereas before it would change to show the profitability for only the selected currencies.

this doesnt seem like a glitch or error but more a designed cutback in service on the NH side of things probabaly to save them some money????

**Comment by DillonN** [comment]
You can find help for the NH service and correct contact emails [here](https://www.nicehash.com/help)
