### ISSUE TITLE
Suggestion: add power consumption to calculate most profitable algo

### ISSUE THREAD

**Issue by Joern85** [nicehash/NiceHashMiner#589]
Hi,

when recently the price for cryptonight hashing power increased i noticed that especially this algorithm is using much less power than others. 

Would it be possible to add a feature where we can enter the power consumption of each card and algo and nhml then uses this values for the profitability calculation? I think it would be very useful especially for users with high electricity costs.

**Comment by supertux1** [comment]
Seconded and upvoted etc... that would be really great. 

Here is an example: With 6x RX480's I can dual mine Dagger (ETH) and LBRY and earn $10 a day.
Each card consumes 175W dual mining, for a total of 1050W which at my electricity prices is $3.27 a day. Profit: $6.73 / day.

The same rig mines $10 a day with Cryptonote (XMR) and that causes each card to only use 100W, for a total of 600W which at my prices is $1.87. Profit: $8.13 / day.

**Comment by micax** [comment]
+1 true.

**Comment by streaml1ne555** [comment]
Would be nice if we could add the $ per kWh and power consumption though it could get tricky when it comes to benchmarking mismatched cards. A Kill-A-Watt and some math will get you close enough. It might be a reasonable enough estimate to use what the card thinks it's drawing via SMI for Nvidia. Not sure if AMD has an equivalent.

**Comment by DillonN** [comment]
Will look into this

**Comment by Jdruitt** [comment]
+1

**Comment by boby361** [comment]
This is so crucial as some algorithms consume 25% more power. $/watt is the name of the game and this miner cant do that. Been making me thinking about looking at other options. I see the power_calc branch and PRs to do this but there has been nothing to really support it that i see recently.

**Comment by S74nk0** [comment]
This feature is already available (in the latest or more recent releases) but it is not reliable at the moment and I will explain why. For example:
```
{
      "Name": "CCMinerTpruvot",
      "PluginUUID": "CCMinerTpruvot",
      "PluginVersion": "1.1",
      "AlgorithmIDs": "Lyra2REv3",
      "Speeds": [
        38703333.333333336
      ],
      "ExtraLaunchParameters": "",
      "Enabled": true,
      "PowerUsage": 176.03557017543844
    },
```

There is a `PowerUsage` field that is measured during bench-marking and it will be deducted from `CurrentProfit` if MinimumProfit is set. 

The `PowerUsage`  measurement could be done with different TDP settings and also the benchmarking time might not be long enough to calculate power usage reliably. 

It would be much better if we would use real time power usage data instead of static data that was recorded in different conditions (that might be obsolete with each update). We will improve the implementation of this feature. We already have 3 power usage sources for devices: miner API, device monitoring reading and algorithm `PowerUsage` field  and we prioritize them in that order.

We will improve this when we introduce BenchmarkModes for each algorithm.

Keep issue open
