### ISSUE TITLE
font issue with 1.8.2.0-pre (and previous)

### ISSUE THREAD

**Issue by apprehensivemom** [nicehash/NiceHashMiner#598]
I am using Windows 7-64bit with a 4k monitor and of course I use big fonts
_(font set at 150% from control panel - screen)_
Nicehash uses those larger fonts but **only in the last line** even if the main window doesn't scale
The bigger font takes more space and some of the text is lost (Balance in EUR is missing)
This is how it looks like
![immagine](https://user-images.githubusercontent.com/16473762/32783310-8e540b82-c94b-11e7-8cd0-a44ee3d07f34.jpg)
A fast solution? all text should be normal size, regardless of big fonts.

Another suggestion:
If I install nicehash from a country inside Europe, the installer should set _default change_ to eur, if I install from Japan, should set it to yen, .... and so on.
Of course after install, - if I need  - I could go to settings and modify currency to whatever I like
Thank you

**Comment by DillonN** [comment]
NHML is built on the Windows Forms framework, where native DPI scaling wasn't implemented. The problem lies in Windows 7 - in W8/W10 there is a new better DPI scaling method that doesn't cause issues with NHML (confirmed on 4k monitor @ 150%). You can try editing the properties (right click on the exe), and checking "Disable display scaling on high DPI displays" under compatibility
