### ISSUE TITLE
NiceHash Miner Legacy Recommends More Virtual Memory

### ISSUE THREAD

**Issue by billmcilhargey** [nicehash/NiceHashMiner#6]
Three items,

One is my virtual memory is set to 20480 - 30720 MB which should be more than enough (but let me know if it isn't) - 5 1080 Tis GPUs

Second, have an option which then asks the user would you like me to increase it to the recommended amount for you?

Attached a sample power shell script to adjust this automatically (does require system restart)

[Adjust-PageFile.zip](https://github.com/nicehash/NiceHashMinerLegacy/files/1143637/Adjust-PageFile.zip)

Third: Specify the recommendation for the user to adjust manually.

**Comment by billmcilhargey** [comment]
Scratch number 1 - increased page memory to 61440 - 71680 MB

This is overkill but since I have 11GB VRAM x 5 GPUs better to have more than not enough (its a dedicated computer too so not using the extra SSD space for anything else)

Seems to be good now 👍

**Comment by DillonN** [comment]
Right now NHML checks if your total available memory is larger than a certain percentage of your total VRAM. With 1 1080 Ti being 11GB this can add up fast. This may be re-looked at, since the system memory only needs to cover what miners will use (not total available VRAM). For now if you have a card with a lot of VRAM you can ignore this message.

**Comment by billmcilhargey** [comment]
ok! thanks!  Yes 11 GB RAM each   8GB total system RAM so then paging would take care of the rest

Out of curiosity, would more than 8GB of System RAM help in this case or not really?

**Comment by DillonN** [comment]
I'm not an expert on CUDA/OpenCL, but from my understanding more system RAM won't help if you have available VRAM. The idea is that the miner keeps a large chunk of memory on the GPU (e.g. in ethereum, it is nearing 4GB), and the OS needs to keep a chunk of that mirrored in system RAM. Since the GPU is *required* to hold the whole chunk on its own VRAM, it won't be asking the OS for bits and pieces of it off system RAM. Windows however will complain if it can't allocate space for this in its memory pool (which consists of physical RAM + virtual RAM). 

In something like a game you would certainly notice problems, since a game is constantly streaming from the mirrored RAM pool when it runs out of memory (obviously streaming data from physical RAM is much faster). There may be some algorithms that would stream when the GPU VRAM is full, but as long as your GPU has available memory it shouldn't be an issue.

**Comment by billmcilhargey** [comment]
wow! ok, thanks for the great explanation!

**Comment by DillonN** [comment]
No problem! Just for some info on what would happen should you run out of memory, look at this:

![image](https://user-images.githubusercontent.com/5328577/28145251-cd31428a-673e-11e7-94be-fb7492e8b15d.png)

This is ClaymoreDual running on just one GPU. The committed column is almost 2.5GB but it's only working with less than 130MB. Despite not using the spare ~2.4GB, Windows reserves it for ClaymoreDual and it goes against the total used virtual memory (physical + page file). If you get to 100% usage of virtual memory, Windows will start to close programs on its own, even if only 10% of that is actually being worked with and the other 90 is empty.

**Comment by billmcilhargey** [comment]
Aww makes sense then.  I have the extra space so dont mind providing a little more

Ohh one more item for the feature request bucket regarding this

Add an option in the config to skip memory test

Right now you mentioned to skip it (I increased it) but if I have a script that automatically launches this on restart or something its going to hang on the dialog at this time mentioning you need a larger page file.

**Comment by fefsf** [comment]
32GB min/max for VM is enough for 6 GPU rig. The only algo that needs that much VM is X11

**Comment by JerryC564** [comment]
You can add an option "don't ask me again", DillonN

**Comment by nivong** [comment]
@DillonN it will be awesome if you could remove that warning or do an opt out or something. Now when the miner crashes and nicehash is being started automaticlly after power failer, it hangs on this message and you have to click to OK to start mining

**Comment by DillonN** [comment]
The threshold for the warning has been made much more reasonable, and it can be disabled by unchecking "show driver version warning" in settings

**Comment by krugm0f0** [comment]
Is this fixed? I am getting the same message on both 1.8.1.10 and 1.8.2.0-pre2.

My setup is 2x 1080Ti, 2x 1060 6GB and 6x 1070. Total of 10 gpu's. Combined they have 11+11+6+6+7+7+7+7+7+7 GB VRAM = 82 GB. After first having a pagefile of 60% of my total vram, I now have my pagefile set to 82000 MB, but I am still told to increase it.

**Comment by krugm0f0** [comment]
And my problem is back again on 1.9.0.21 + .22. -.-
