### ISSUE TITLE
NiceHashMinerLegacy 1.8.1.5 does not benchmark

### ISSUE THREAD

**Issue by BigRunner37** [nicehash/NiceHashMiner#603]
I have spent hours and hours benchmarking trying to get algorithms to work.  

I read the wiki guide and tried standard, precise, and manual entry of each. 
I run the miners manually, but they do not work. 
I try reinstalling different versions of legacy miner (bc I have amd card). 
Only about 3 of the 18-20 miners work. 
I upgraded to Windows 10 - 64 bit (from Windows 7), upgraded my video card to a Vega 56 flashed the bios to 64 and installed the block chain driver. 
I tried an older AMD card prior to this one, and the same problem. 

Most miners say Failed - try Precise Mode (even though that is what I did) or Terminated.  
I don't know what I am missing or doing wrong...only 3 miners work. 

I search online and through posts, but all I can find is folks saying theirs works or an unrelated problem. This is getting frustrating. Please help.

Do I need to go into a folder and find a configuration file somewhere to get this to work?

**Comment by Paapo** [comment]
It looks like, the AMD Driver are not working well, with the newer versions. There must be some important changes, perthaps another openGL Version ore something like that, from VErsion 1.8.1.3 to Version 1.8.1.4/1.8.1.5 and 1.8.2.0, i´ve also tried. All newer Versions are not running well with AMD Cards (me:RX470 and RX580) and Claymore CryptoNight. Neither with the old Claymore version, nor with version 10.2..

I know, this don´t help, to fix your issue. I just wanted to say, you are not the only one, having these issues. But, although i´ve opend a semilar Ticket#431 for VErsion 1.8.1.4pre3, nothing has changed. Perhaps for the developers, this is not a real issue?

Kind Regards,
Paapo

**Comment by mifurman** [comment]
I agree. There is a problem with 1.8.1.5 and Vega (especially 64). I am describing problems with CryptoNight in case 602

**Comment by mifurman** [comment]
I am having problems with Vega 64 when NiceHash Legacy 1.8.1.5 is used.  It does not work well with Win10-64Bit-Crimson-ReLive-Beta-Blockchain-Workloads-Aug23 when Memory is overclocked (up to 1100 Mhz). I tried this GPU (with 1.8.1.50 in numerous configurations and two different computers. It seems to me that 1.8.1.5 was not tested properly. I do hope to hear some comments about it. I actually lost half a day (or more) of mining trying to figure out the problem.

**Comment by BigRunner37** [comment]
I really appreciate your comments Paapo and mifurman. At least I am not alone, and you gave me some ideas to try older legacy versions and benchmarking at lower freq.  Even so, I had similar problems benchmarking using my older graphics card. I even did the manual route.

**Comment by DillonN** [comment]
The blockchain drivers seem to be unstable with many of the existing miners bundled in NHML. For these kind of incompatibilities, there is not much to do but wait until the miner developers come up with versions that work better. We are currently waiting on the new xmr-stak which should provide the best performance for Vega mining. 

If you are having problems with manually running miners then the problem is deeper than benchmarking, again this kind of incompatibility is not up to NHML (which only can make sure the proper miners are used for the proper card). If you want help you need to describe the actual issues you are getting when trying to run specific miners. 

As it stands the Claymore miners currently have the best support for Vega
