### ISSUE TITLE
Automatic dropped to 0 while mining

### ISSUE THREAD

**Issue by Jpolola** [nicehash/NiceHashMiner#616]
I am having problem with nice hash miner legacy 1.8.1.5. It always automatically close and open and dropped to "0" hashrate per day.
Version of mining software : 1.8.1.5 ( I also used 1.8.1.3 but same thing)
CPU : Intel Core i3 7100
GPU : NVidia GTX1060 6GB ( 8 GPUs in 1 Rig ) all same model
OS version: Windows 10 Pro (64Bit) 
it will drooped to 0 and automatically start and gradually up hashrate per day and after a minutes it will dropped again. But because it is fast I cannot get timing of 0 at screenshot. I also see BTC donation address on top or the beginning after automatic restart. I really appreciate any comments with solution because I am newbie.
![1](https://user-images.githubusercontent.com/33750486/32944323-8217cf3c-cbd2-11e7-9d13-7965fc12d564.PNG)

**Comment by Jpolola** [comment]
I disabled lyra2v2 algo in miner setting and start again but the same thing. mostly every 10 minutes it automatically close and open window and hash rate per day down to 0 and gradually up then restart again and again.

**Comment by DillonN** [comment]
Is it changing algorithms when it starts a new window? The profit switching feature of NHML requires closing and reopening the windows. You will see the intro text to the miner software (for the case of this one, it shows the BTC donation address for the miner developers). Profits will drop to 0 temporarily as there is a delay from when a new miner opens and when it starts producing numbers NHML can read. You can extend the time for profit checking in the settings, which will make the times between switching longer (note the switching only happens if another algorithm is paying better, so generally it is a good thing). 

If it is restarting the same algorithm something else is wrong, in that case could you please post your logs/log.txt file

**Comment by Jpolola** [comment]
Thank you to your reply DillonN, Yes it was changing algorithms whet it starts a new window. I will try your advice extend the time. Thank you.
