### ISSUE TITLE
Good day I have a startup NiceHash error while retrieving information SMA . Error : nicehash miner legacy asks for Internet connection to work. Make sure that you are connected to Internet before you run. Would you like to continue... the Internet is ! the location change didn't help. What could be the problem ?

### ISSUE THREAD

**Issue by QWer6qed** [nicehash/NiceHashMiner#618]
To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- Relevant log files are included (generally `\logs\log.txt`).
- The issue is with NHML and not inherent of miner executables. This can be verified by launching the miner manually and looking for the error.
- The issue is relevant to NHML specifically and not to the NiceHash service.
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

> [**_`#[](url)`_**](

- url

)

**Comment by BARUCHER777** [comment]
I have the exact same problem last for a month in a row .... but if a day leave miner running, the balance will be displayed as the position, but I think that this is a serious defect of the software, or super bug!
-----------------------------------------------------------------------------------------------------------
У меня таже проблема длиться уже месяц подряд....но если на сутки оставить майнер запущенным, баланс отобразится как положенно, но считаю, что это серьезная недоработка софта, или супер глюк!

**Comment by Sav87** [comment]
add Pull request #625

**Comment by techman05** [comment]
Just for thought but when the popup shows to asks how to let the miner connect to your network do you allow it. My thought is I had to do this for a few miners since I've got it set for profitabilty. You might have to close the whole program if  you haven't already and see if it asks you again or find your way to your filter settings and see if its blocks there or your antivirus.  

Mine I had to set exceptions and clear the log in the log file to redownload the miners then benchmark and go.

Hope that helps.

**Comment by xtrime-ru** [comment]
Ive made a repo with fixed exe (fixes from @Sav87):
https://github.com/xtrime-ru/NiceHashMinerLegacy-SMA-FIX/releases

**Comment by ekadanthcomputers** [comment]
I have 5 rigs and I was faced with this issue too. I deleted nicehash, cleared cache and had to benchmark one of my rigs all again but this did not resolve the issue. I tried the step with disabling IPv6 to no avail. I turned off all my rigs. Switched on one and changed the 'Service Location' and 'Currency' (in settings) on  the NiceHash Miner. This resolved the issue for me. All my rigs are working again.
Please let me know if this works for you.

**Comment by xtrime-ru** [comment]
@ekadanthcomputers sma issue is caused by cloudflare (ddos protiction service), blocking connections in new protocol. You can solve this in two ways: change your ip (vpn, or switch to another version of ipv4/ipv6) or use old protocol (old versions of Nicehash, or fixed exe).

Changing location and currency cant solve blocking your ip in cloudflare. 

But switching all your rigs can, because number of network requests Will drop. Also cloudflare could just remive your ip from black list while you performing all actions with rigs...
