### ISSUE TITLE
Config option to skip miners files check after inital startup (1.8.1.5)

### ISSUE THREAD

**Issue by HaTaX2** [nicehash/NiceHashMiner#619]
Currently NHML checks all the miners files at startup and if any of them have been modified or are not present the user is presented with an error dialog and can have NHML re-download all of the miners.

Some users might change out the downloaded miners and this prevents NHML from being able to auto start mining.  Not a big deal if you're there when it opens up, but NHML can be started automatically without a user present and in this case it will stick at the dialog and not start mining. 

In my particular case I changed the included ccminer_cryptonight miner to the 2.06beta x64 release and placed the old files in a backup folder named 'OLD'.  (I got better performance and system responsiveness with this release on my system)  Now every time I start up NHML I have to click 'No' on the warning before it will do anything else.

My proposal, and something I have added to my fork of NHML is a general config option of 'SkipMinersFilesCheck' which is set to false by default.  In Form_Main.cs I changed the if statement that displays the warning to:
`if ((!ConfigManager.GeneralConfig.SkipMinerFilesCheck) && (!MinersExistanceChecker.IsMinersBinsInit()))`

This works as expected and allows NHML to start up with modified miner files, and no warning dialogs.  Another solution could be to check and see if 'AutoStartMining' is set to true at startup, and if so skip the warning dialog.  This way if NHML does something like running the script when a CUDA GPU is lost, that it will resume mining automatically when it is restarted.

I'll include the changes I made in my 'Window_Manager' branch that I have out there as a pull request at some point if there's any interest in this change.

**Comment by DillonN** [comment]
The existence checker is generally a good thing for everyone to have, many miner files can be flagged by antivirus and then removed. If NHML tries to launch a miner and it is missing it will cause it to not mine

You can workaround this by making sure all the bin files are still in the folder. You said you unpacked the new version for a ccminer, however it is likely that there are some .dll files in the old folder that aren't located in the new folder. Even if these .dll's aren't required to run, you can just copy them into your new folder since NHML looks for them as well as the exe's. I don't believe this applies to ccminer but if there are .bin files also copy them over. As long as the complement of .exe, .dll, and .bin files are the same then NHML won't complain.

**Comment by HaTaX2** [comment]
Worked for me! There was a 32 bit DLL that wasn't included with the version I downloaded so I just copied over the one from the old version and I don't get any complaints anymore.
Closing this issue.
