### ISSUE TITLE
NHML Freezes 

### ISSUE THREAD

**Issue by Filipmycup** [nicehash/NiceHashMiner#626]
Hardware;
4 RX580s
1 1000watt PSU

Background;
The system was working 99% of the time, sometimes restarted for no reason. Thought I could fix this by activating "Open when windows start" and "Auto mine". After these were activated stability decreased, and now started freezing. System usually runs 2-5 min before the system freezes and a hard restart must be used. Log files don't reveal anything too big, but I posted one to see if someone else could find something I couldn't. Using latest software (1.8.1.5) and most up to date windows and drivers. I've exhausted all my options and hoping this could work

[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1485077/log.txt)

**Comment by DillonN** [comment]
@Filipmycup do you notice crashing on specific algorithms while crashing? In your logs it looks like you are mining sgminer cryptonight mostly, you can try disabling that to rule out a problem being caused by it. You can also try activating claymore_cryptonight to use instead if it turns out sgminer was not playing well

Unfortunately the auto mine and auto start with windows options have almost no effect on NHML after initial bootup, so I cannot infer some problem happening after enabling them. Of course I can't be certain, but if I had to guess it would be these options are not causing the crashes and it is another thing that happened around the same time that is making your system unstable (e.g., cryptonight price rising and causing it to mine more).
