### ISSUE TITLE
Still an issue with Cryptonote 10.2

### ISSUE THREAD

**Issue by imrecsoka** [nicehash/NiceHashMiner#627]
Hi, i still have an issue with Cryptonote miner 10.2
I notice SGminer is the same, i dont get full hate rate on my 3rd GPU.
If i use an older version of NHMiner it is fine.
This is weird.
I also do not see any new feature or something that i should be noticing which is worth the download?
No rip off or offensiveness, but i just used precious cell phone data to download this and i still feel sad.
Agg, anyways, ill wait more i guess.
No sure what is causing that speed bug ? and or what else will be new or improved in a next version

**Comment by DillonN** [comment]
You can use the old Claymore cryptonote version instead of 10.2, by disabling "Claymore_cryptonote" and enabling "Claymore_cryptonote_old". 10.2 was included since it provides some slight speed bumps on some cards, but the old version was left as a separate option since 10.2 does not play well with all cards.
