### ISSUE TITLE
Include mkxminer: Lyra2rev2 miner for AMD GPUs?

### ISSUE THREAD

**Issue by PrEzi3** [nicehash/NiceHashMiner#632]
Not a real issue, however it has come to my attention, that a new, optimized miner is there for AMD cards, that matches (or surpasses) NV-cards.
Can mine Vertcoin, Monacoin, XVG. 
Hashrates look impressive:

=== Speeds (no overclocking)
Radeon Pro Duo: 84.8MHs (42.4 + 42.4)
Fury X: 55MHs
Vega56: 47MHs (can be optimised further, just need some time and incentive)
RX 580: 39MHs
RX 480: 36MHs
R9 390: 32MHs
R9 380X: 26MHs
R9 280X: 26MHs

Would it be possible to include this into NiceHash Miner Legacy?

Link:
https://bitcointalk.org/index.php?topic=2360168.0

**Comment by BARUCHER777** [comment]
The same question, why so slowly add new miners and new algoritny for AMD !!!

**Comment by DillonN** [comment]
@PrEzi3 thanks for the heads up, I will look into it

@BARUCHER777 we do try to keep an eye out for new and upcoming miners, but posts like this help us to see them and implement them. As it stands we usually only include miners that have a proper HTTP API (so that NHML can communicate with them properly), have a way to be benchmarked, and properly support the NH protocol. For AMD there are some not implemented that many have requested: Cast XMR (which does not have an API) and XMR-Stak-AMD (which does not support NH protocol, but update for it is coming).

**Comment by PrEzi3** [comment]
If we are already talking about adding some nice new miners with OpenCL/AMD and NiceHash support (and I am very surprised about the positive response from DillonN -- thanks mate!) then also this one can be checked:
High performance Monero (XMR) OpenCL miner with NH support-->>
https://github.com/xmrig/xmrig-amd

**Comment by DillonN** [comment]
@PrEzi3 thanks for that suggestion as well, since Xmrig for CPU is already implemented it should not be overly difficult to add the AMD version. Xmr-stak is released now so will look into this if it outperforms that

**Comment by PrEzi3** [comment]
Xmr-stak-amd is not outperforming other algorythms for me (but this was expected).
Hopefully you'll be able to implement mkxminer (first post) into NHML.

**Comment by winmkx** [comment]
Hello DillonN!

I can add benchmarking and api capabilities to my mkxminer. Do you have a requirements documents with details on what API calls are necessary?

Also, since version 2.0, mkxminer works only with TLS pools. Could you add a TLS lyra2rev2 port please?

Thanks
WinMKX

**Comment by JCarangoH** [comment]
@DillonN @winmkx  This could be a nice moment to check this miner... Lyra2rev2 is getting very profitable!

**Comment by mvrak** [comment]
Windows has deleted all my mkxminer.exe files citing a Fuery something virus.  I suggest nicehash sticks to open source miners and figures out whats going on here.

**Comment by PrEzi3** [comment]
I suggest you get a better AV.

**Comment by bucence** [comment]
@winmkx , could you please optimize your miner for zpool to mine VERGE ? Or idcray.com pool.
Please, kind regards Ivo Icevski

**Comment by winmkx** [comment]
@bucence - all pools are supported since version 3.0.0. zpool should work as well. PS: Linux version will be released in a few days.

**Comment by bucence** [comment]
Yeah. I get that, but it dissconects from the pool once in couple of hours, but does not recconect, its idle

**Comment by PrEzi3** [comment]
@winmkx - I can confirm that what bucence says --- using 3.0.0 now and it disconnects (sometimes after 2-3 hours, sometimes after 5). Afterwards tries to reconnect but fails. E.g. throwing 301 error....  (suprnova pool).
As a workaround I have a script that restarts it every hour.... but this sis a dirty workaround....
Check post 301 on bitcointalk.

**Comment by DillonN** [comment]
@winmkx thanks for reaching out, I'm currently working on getting mkxminer included. There is a wiki page for miner criteria [here](https://github.com/nicehash/NiceHashMinerLegacy/wiki/Miner-request-criteria). 

The only API call necessary is polling hashrates. That way NHML GUI can show users the hashrates and current profitability. With most miners NHML opens a TCP connection to the API port (defined by a command line option) and the miner sends some JSON data back. You can either report total hashrate or per-GPU hashrate, per-GPU would be preferable because per-GPU profits *might* be supported in NHML down the line.

I haven't gotten into benchmark implementation yet, it may work with current version. However adding an ability to log hashrates (e.g. a log that writes a line with current hashrates frequently) and a benchmark timeout option (e.g. command line option like `-b 60` that automatically closes the miner after 60s) certainly would make this better. A log option would be necessary if mkxminer doesn't play well when standard output is forwarded to another program (again haven't tried yet, but other miners have this problem)

Overall this would be a great fit for NHML, especially with no current Lyra2REv2 AMD support!

Edit: if anyone wants to track current mkxminer support in NHML it's on the [`mkxminer`](https://github.com/nicehash/NiceHashMinerLegacy/tree/mkxminer) branch

**Comment by JCarangoH** [comment]
Any news about this miner? i'm using it standalone and works flawlessly with R9 270x at 17.8 MH/s and with RX 470 at 27.8 MH/s

**Comment by olodar** [comment]
It's sgminer based? Then where's sources?

**Comment by winmkx** [comment]
Hello!
mkxminer version 4 dropped support for Lyra2rev2 (because of ASICs out there) but added support for Lyra2Z. Which is the best for AMD cards:
Vega64: 7.4MHs
RX 580: 3.7MHs
RX 480: 3.5MHs
R9 390: 1.8MHs

Please add mkxminer V4 with Lyra2Z.
Any questions / requirements - please let me know.

PS: mkxminer also has API support now.
Thanks

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

This is added teamredminer as of today
