### ISSUE TITLE
Devfee: Connection lost , retry in 20 sec...

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner#637]
Hello i have one problem..i use NiceHash miner legacy v1.8.1.5 
Mining Cryptonight: xmrig and Claymore_cryptonight_old.
The problem is every 10 min i get Devfee: Connection lost , retry in 20 sec... and every 20 min on xmrig
Can u help me to fix it? 
Thanks and sorry for my english.

**Comment by BARUCHER777** [comment]
Same problems!

**Comment by DillonN** [comment]
Can you try adding the `-allpools` option for Claymore_cryptonight_old extra launch parameters?

**Comment by ghost** [comment]
i will try that what about xmrig??
Also what will happend if i use -nofee 1 
claymore devfee is 2% right? or its zero cuz nicehash?

**Comment by ghost** [comment]
??

**Comment by Paapo** [comment]
This will fix your issue. I´m using this command also, because of exactly the same issue, reported in a few other threads. That´s really bad, because i don´t want zo take away developers fee.-( 

Regards,
Marcus

**Comment by ghost** [comment]
hello Marcus
What command u use the -allpools or -nofee 1?
Thanks for your help :)

**Comment by Paapo** [comment]
To fix the diconnection issue, i´m using the -nofee 1 command. But, you should be aware, that there is might be some performance lost, with thr nofee option enabled. I don´t know exactly how much, because, claymore doesn´t show any difference, but i´ve read of this in some discussions.  But, the disonnections are gone and i can´t life with this ongoing disconnections. So, i´m hoping Dillon will have a look at this issue. I know, this might be is not a nhml issue, but, I can mine monero, with the same miner Claymore CryptoNight 9.7, on minergate, without the need, to use the nofee option and without these disconnections. I´m nearly sure, this happens, because we are only mining for the dev for 72sek, or 90sek and then for hours nothing. And because there is no traffic over a long period, on the devfee line. provider might disconnect after 10 minutes without traffic. For me that is the reason, why this happens exactly every 10 minutes.. I think, if they could implement a keep alive point, for the devfee line, the issue might be fixed. But that´s really my own thought. What i know is, this happens, till version 1.8.1.3. Previous versions didn´t had this issue.

Regards,
Marcus

**Comment by niztheboss** [comment]
what is nofee 1 command and how do i do it

**Comment by DillonN** [comment]
nofee parameter tells Claymore to not attempt to mine the devfee. It lowers performance by about 5% 

If you don't set this parameter then there is a 2% devfee (1% if you're not dual mining)

To set it add `-nofee 1` to the ClaymoreDual extra launch parameters

This disconnection may also be solved by setting `-allpools 1` which tells Claymore to try different servers for the devfee connection
