### ISSUE TITLE
Daggerhashimoto Speed drop

### ISSUE THREAD

**Issue by ferdienortje** [nicehash/NiceHashMiner#644]
I have a problem where I start mining dagger at 170GH/s and then after a couple of minutes it drops down to 140GH/s
I am using NiceHash Miner Legacy v1.8.1.5 (v1.8.1.3 did the same thing)
I am running 6x AMD RX580 cards on WIN10 Pro.
The problem is only there when mining DaggerHashimoto
I want to mine Ethash as it is currently more profitable but when the speed drops like this I have to go to Cryptonight as it is more profitable.
My friend has the same problem when mining Dagger. He runs 4x AMD RX480 on Win8.
Strange thing I noticed last nigh the speed dropped to 140GH/s and a minute later jumped back to 170GH/s. Can it be a temperature setting on you software maybe? I have noticed on your settings there is a box to disable AMD temperature control but it says (except daggerhashimoto algorithm). Maybe this is a known issue or is there a way to disable this.

**Comment by BARUCHER777** [comment]
Такая же проблема на Радике 580 МСИ

**Comment by DillonN** [comment]
@ferdienortje which miner are you using? ClaymoreDual does have a temperature limit setting but it is not used by default (and ignored if you have that checkbox checked). You can see if this is the cause by looking at the miner window, there will be lines something like "GPU0 intensity -20% due to temperature". 

Dagger mining can also drop if the CPU is at high utilization, or if memory is. 

There may also be temperature or power based throttling happening at the driver level, which is out of NHML control. 

After those I suggest checking the miner window to see if specific GPUs are dropping

**Comment by Simaex** [comment]
Same problem with GTX970. No thermal throttling, core and memory speed remain the same. When high performance temperatures are higer. I've reported the issue in separate thread already. I've run single GPU .

**Comment by Paapo** [comment]
What Crimson Driver Version are you using? Try to use the crimson blockchain driver:
win10-64bit-crimson-relive-beta-blockchain-workloads-aug11, if you don´t do already.

Regards,
Marcus

**Comment by ferdienortje** [comment]
Hi Marcus. I will try that. I am still using old version drivers. The reason why I use it is that there was a problem with the RX580 on Win10 if you have more that 5 cards. It only detects 5 cards. So I had to mix the version 16 and 17 drivers to get windows to detect 6 cards. Hopefully this problem is solved with newer version drivers.
