### ISSUE TITLE
Mining Disconnection

### ISSUE THREAD

**Issue by AE001** [nicehash/NiceHashMiner#645]
APU: AMD A8 5500 with AMD 7000D Series Built in GPU.

While mining via Nice Hash Miner Legacy, the connection suddenly drops and hash rates drops to 0.
Following message is displayed:
"Pool connection lost. waiting 10 s before retrying (attempt 1)" 

The problem resolves temporarily when I restart my internet modem and resumes after 30 to 45 minutes.

Please guide as to what might be the problem.

Snapshots of the error are also attached.

![cpu](https://user-images.githubusercontent.com/33860753/33063606-c1e08c5e-cec4-11e7-854b-d2d1d79ece40.PNG)
![gpu](https://user-images.githubusercontent.com/33860753/33063607-c211c38c-cec4-11e7-8b49-93f6343539c3.PNG)

**Comment by Jpolola** [comment]
I also experienced this. My solution is Reset Overclocking to Derfault. Adjust Fan to 70 and touch nothing. Then it work properly. Maybe because of overclockling.

**Comment by DillonN** [comment]
Devices that are older and have very low hashrates in CryptoNight will not work properly with NH, as they do not submit shares quickly enough to keep the connection alive. Unstable devices will also have this problem due to high invalid share count. This is not an issue with NHML, and even so it is likely you would lose money mining on those devices after taking electricity costs into consideration.

**Comment by AE001** [comment]
@DillonN.
Thank you for your response.  What are the minimum PC requirements for stable mining?
Please elaborate "unstable  devices". 
My AMD GPU also show connection lost. Does it have to do anything with internet connection settings?
