### ISSUE TITLE
1.8.x.x writes that there is no Internet, thus no profitability

### ISSUE THREAD

**Issue by EVGENY1777** [nicehash/NiceHashMiner#651]
had to run on version 1.7.1.13
version 1.7.x.x shows the profitability of version 1.8.x.x writes that there is no Internet, thus no profitability
Blocking the window "no Internet connection... it is impossible to obtain data on the profitability of the..."
Changed servers, ran with Administrator rights, and removed IPv6 to no avail.
All servers are normally pinouts.
Antivirus and firewall disabled.
![22 11 2017](https://user-images.githubusercontent.com/23138776/33106237-3accee28-cf42-11e7-8490-8f8c4d67fd00.jpg)
![22 11 2017_1](https://user-images.githubusercontent.com/23138776/33106353-b2d60f44-cf42-11e7-8e4e-fcfc722b4347.jpg)
[log — копия.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1493658/log.txt)

**Comment by BARUCHER777** [comment]
Такая же проблема уже три недели пролжается...
![1 8 1 1 5_nicehash-error](https://user-images.githubusercontent.com/18327150/33114659-eb78329c-cf6e-11e7-8c36-1ebd6e010233.jpg)

**Comment by EVGENY1777** [comment]
Already created a lot of topics on this question, and the answer is no!!!
https://github.com/nicehash/NiceHashMinerLegacy/issues/481
https://github.com/nicehash/NiceHashMinerLegacy/issues/529
https://github.com/nicehash/NiceHashMinerLegacy/issues/563
https://github.com/nicehash/NiceHashMinerLegacy/issues/604
https://github.com/nicehash/NiceHashMinerLegacy/issues/612
https://github.com/nicehash/NiceHashMinerLegacy/issues/617
https://github.com/nicehash/NiceHashMinerLegacy/issues/618
https://github.com/nicehash/NiceHashMinerLegacy/issues/648
https://github.com/nicehash/NiceHashMinerLegacy/issues/667

**Comment by VadimEv** [comment]
Did some playing with one of my rigs, pretty strange(wrong word tbh) things happening. 
Observation 1:
 NHM 2.0.x.x works with no prob, but lets be honest here: less transparency, less profit, less settings, less versatility. For casual miners with 1-3 cards running it in-between DOTA (or w/e) marathons it may be ok; but it light years away from being a tool for dedicated mining rigs.
Observation 2: I have rigs connected via local server running kerio software router. another rigs connected via 4g cellular router. Guess what they share in common? both groups have the same IP for multiple rigs. In each of the group there is 1 rig perfectly working with NHML. And as soon as I pull one rig for another IP, using my cellphone as a modem for example, it connects with no prob.

So yep, first guess was right: cloudflare is the culprit. 1 ip 1 miner is pure BS, since there are ISP subnets in which thousands of endpoints can share same ip.

**Comment by ForeverRED66** [comment]
#466 
Only VPN help with Russia users...
ставим впн и все проблемы с прибыльностью или отсутсвием интернета исчезнут,но это ппц товарищи(((

**Comment by ArtAnts1986** [comment]
Only VPN help with Russia users... 
oh... Facepalm

**Comment by tobeaver** [comment]
Tambourine dance:
1. Download and setup NiceHash Miner 2.0 https://miner.nicehash.com/
2. Run NiceHash Miner 2.0
3. Start mining/benchmarking
4. Run NiceHashMinerLegacy
5. ???
6. Stop NiceHash Miner 2.0
7. Continue to sharpen your dancing skills
