### ISSUE TITLE
"Shareabovetarget."

### ISSUE THREAD

**Issue by Simaex** [nicehash/NiceHashMiner#658]
Hi!
 I started to receive {"id":4,"jsonrpc":"2.0","error":{"code":1,"message":"Shareabovetarget."}} error while using Claymore 9.7 AMD GPU miner for NiceHash. I reported the problem to Nicehash online help and they recommended to report the bug here. The issue is NOT associated with NHML, it is associated with Nicehash service. Windows 10 Pro 1709, 8xHD6990 GPU, latest 15.7 AMD driver. While trying to fix I found that it occur during difficulty change. As for now the problem stop to occur without any changes from my side. Please advice how to troubleshoot.

**Comment by JBSpice** [comment]
Hey, I have read some other forums, and I have too been experiencing the same problem, what I have noticed that you, me, and some other people with this problem is that we all have been using the Catalyst 15.7.1 driver from AMD, I haven't tried it yet, but there is a beta version of Crimson available for the HD 5000 series and up. I will try it soon to see if this works. Hope this helps!

**Comment by abbaselmas** [comment]
@JBSpice nope its not about driver. I also had this issue too. Reinstall legacy and zip files and restart your computer has resolved my problem.
PS: I have 11August blockchain driver installed
