### ISSUE TITLE
How to mine with out benchmarking again

### ISSUE THREAD

**Issue by imrecsoka** [nicehash/NiceHashMiner#660]
Hi, how can i upgrade say from version NiceHashMiner1.7.5.16-DillonN to NHML-1.8.1.5 without benchmarking again, its a real pain. It takes ages, and i only have 3 GPUs
And sometimes i need to retry some benchmarks because they fail, The beauty of information technology.

**Comment by HaTaX2** [comment]
You can copy over all the files in the 'Config' folder, your benchmark files are in there.  That will bring over all your settings and previous benchmarks.  

Since you're making such a big jump in versions however there's a good chance benchmark speeds have changed and there might be some new algos in the new version, as well as some algos that are no longer in there.  In that case, you can just re-benchmark the new algos to get things moving along, but until you re-bench them all your profitability calculations might be off, leading you to be less profitable.

**Comment by Simaex** [comment]
Please note that benchmarking is generating payment. It is not a complete waist of time. At least if you properly specify you mining addres. If you have identical cards you can benchmark just one card and manually copy benchmark results to other cards.

**Comment by imrecsoka** [comment]
Okay, so you guys just re-benchmark everything again? really?
Must take ages, especially guys that have 6 cards and up.
Thats like 10 cups of coffee before you can start mining.

Simaex ; HaTaX2; awesome tips and thanks for feedback and stuff

**Comment by Simaex** [comment]
I do agree that benchmarking need optimization. Ongoing discussion you can find here: requested feature #611. As for now I prefer to re-run optimization with each miner version, 8-GPU system.

**Comment by DillonN** [comment]
@imrecsoka you should still be able to copy over the files from the config folder still and they will work. It is a big jump in versions but not many things were changed in those files

@Simaex getting paid for benchmarks is true for some miners, however many run in offline benchmark mode
