### ISSUE TITLE
[feature] bitcoin gold mining

### ISSUE THREAD

**Issue by maxgamurar** [nicehash/NiceHashMiner#666]
Hello!
It would be nice to have bitcoin gold available in NHML.
Please vote!

**Comment by JCarangoH** [comment]
You can mine Bitcoin Gold with Equihash already, maybe is just that there is few people ordering hash power to mine it.

**Comment by maxgamurar** [comment]
Is there any proof ?

**Comment by Paapo** [comment]
Yes, would be great to have BTG included, with Benchmark etc.

Kind Rrgards,
Marcus

**Comment by luongk** [comment]
JCarangoH is correct, BTG uses the Equihash algorithm  - there is nothing that needs to be added to Nicehash.

**Comment by HaTaX2** [comment]
Remember with NiceHash you're not mining coins with your hardware, you're a seller of hashing power.  Buyers purchase hashing power for a particular algorithm and pay for it with BTC.  So in the case of BTG since it uses Equihash, nothing needed to be changed or added as buyers could purchase Equihash hashing power and use it to obtain BTG.  For the sellers (people running the client software), they were already mining Equihash and were ready to go before BTG launched.  Two weeks ago when BTG launched there was a big spike in Equihash profitability, there was a bunch of happy chatter on Reddit as a result.

You can see that BTG uses Equihash at their website: https://bitcoingold.org/

**Comment by Paapo** [comment]
OK, i understand. But can you also explain the difficulty difference between ZEC and BTG? I mean, i´ve mined BTG allready and i was always connected to a Stratum BTG Server: Right now, the diff of BTG is much lower then of ZEC. If i understand right, yes, you are right. We can offer Equihashpower, but only with a much higher diff, then we could have, if we could connect to a BTG Server. Or am i talking bullshit?
Example BTG Server: stratum+tcp://eu.btgpool.pro:3857

Kind Regards,
Marcus

**Comment by luongk** [comment]
@paapo You're not understanding how Nicehash works. The buyers determine what to do with your hashing power, it's up to them whether they point it at a ZEC or BTG pool. There is no facility to only sell hashing power for a particular coin, nor would you want to as it would restrict the market

**Comment by Paapo** [comment]
In Parts you are right. I really don´t 100% understand how it works, but i´m trying to understand. 
But, just tell me. Can i mine with nhml equihash, with the current difficulty of BTG? If yes, can you tell me how?
And, is it wrong? Mining equihash with a difficulty of 7.0M will result in less income for me, then mining equihash with a difficulty of 5.0M?

Many thanks,
Marcus

**Comment by luongk** [comment]
@paapo Maybe I can clarify a bit for you

Let's say you produce equihash at 340Sols/s.  A buyer who is mining BTG might yield 0.2mBTC/day, while a buyer who is mining ZEC might yield 0.15mBTC/day, due to the difference in difficulty and/or the difference in the value of the coin that they are mining.

All of that doesn't matter, because you are selling EQUIHASH, not BTG or ZEC.  You mine equihash, the buyers determine whether they point your hashing power at a BTG or ZEC or other pool.  What you get paid is determined by what the buyers feel like a 'fair' or market price is.  For example, someone who really wants to mine ZEC might pay a price that is higher than the current value of the coins mined.

If you are looking to mine BTG for yourself, then you need to look at a different product as Nicehash doesn't work that way.  You sell hashing power, not coins, and get paid in BTC.

There is nothing to change, this is not an issue - please close this thread.

**Comment by HaTaX2** [comment]
Difficulty is determined by how many workers are in a particular pool, and the hash rates of the workers.  There's some complicated math that goes into it all, but suffice to say that every pool will have a different difficulty. Most mining pools now use dynamic difficulty values so it will change as more people enter / exit the pool, and the overall hashrate of the pool.

EDIT:  I took too long between starting and finishing this comment, there are far better answers than mine in this thread at this point.

**Comment by luongk** [comment]
Here's an analogy:

You are a farmer.  On your field you can grow many types of different grains - wheat, rye, barley, spelt. Bakers want to buy your wheat to make crossaints.  One day someone develops a new recipe for baguettes which is much easier to bake than crossaints, and wants to buy your wheat to do so.

Do you keep selling your wheat to all the bakers, or do you only sell to the baker who is baking baguettes?  The rate at which you produce wheat hasn't changed, and the addition of a new baker means that there is more demand for your product and the price they are willing to pay increases.  Why would you restrict your market and only sell to the baguette baker?

**Comment by Paapo** [comment]
OK, thank you all very much. really good explanations. I understand much better now.

Greats,
Marcus

**Comment by Paapo** [comment]
BTW. I know how to mine BTG for myself... First, i try to get it to run and second i try to understand the background...:-)
I agree with luongk. This is not an issue..

Greats,
Marcus

**Comment by maxgamurar** [comment]
Thanks for explanation. We can close this issue.
