### ISSUE TITLE
Good afternoon, I have a problem : amd 64 rx vega does not give the stated performance in NiceHash, for example cryptonight gives 700.0000 H\s meanwhile, the benchmark shows 900.0000 H\s NiceHashMinerLegacy. Sometimes starts on the 1000.0000 H\s and if the card in overclocking it 1100.0000 ! but then is reduced by 700.0000 ! On the blockchain driver is doing better but does not always help. Further equihash benchmark shows 480.000 Sols\s but in the end gives 164.000 Sols\s! Sometimes starts on 480.000 Sols\s if the card in overclocking then 520.000 Sols\s but then decreases on 164.000 Sols\s. And here blockchain driver surprises and helps always gives 480.000 Sols\s-500.000 Sols\s ! Previously, such problems were not observed.For other algorithms, too, everything is fine. What could it be ? Or who have Vega ? and how many issues the hashes ? Temperature the video card is normal.

### ISSUE THREAD

**Issue by QWer6qed** [nicehash/NiceHashMiner#668]
To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- Relevant log files are included (generally `\logs\log.txt`).
- The issue is with NHML and not inherent of miner executables. This can be verified by launching the miner manually and looking for the error.
- The issue is relevant to NHML specifically and not to the NiceHash service.
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by AdriaanVisser** [comment]
The same happens for me. I emailed the NH support team, but was redirected here. I am using NHML v1.8.1.5, and just checked the same in 1.8.1.3 and 1.8.1.1. All three have the same problem: initial speed is sort-of correct, then quickly drops off to the 20% lower than maximum mentioned below.

This is the content I emailed them:

Dear NiceHash team,

lately I noticed the DaggerDecred and DaggerLbry speeds of my card (RX 470) being down significantly with respect to previously. Nowadays they barely get above 18MH/s and 0.51MH/s, whereas this used to be 22MH/s and 0.60MH/s. Even benchmarking anew is not improving this speed, and I'm fairly certain it is not my card, since when it switches to a Dagger algorithm, it starts off at the old values, but quickly drops to the new ones, costing me a lot of hashing power.
The same happens with CryptoNight, which runs nominal on 560-570H/s, whereas on startup it easily does 630H/s.

So why are my speeds 10 to 20% lower nowadays than what they were last month?

**Comment by uaktags** [comment]
Have you checked what the output looks like in the miner itself using Exavator or EBWF? NHML from what I've seen in the code isn't doing ANYTHING to the miners, but just executing them in "autopilot".

Anyways, this is still needing the aforementioned logs and follows the 4th point for the streamlined reporting, but I'd say your issues are with the miner not with NHML. (IMHO)

**Comment by PrEzi3** [comment]
The noticeable performance boost will be first there once Dillon implements the new mkxminer with lyrarev2 optimized for AMD cards/Vega.
This 1.8.2.0-pre2 implements "just" the new xmr-stak-amd which is nice, but doesn't really make a difference.

**Comment by AdriaanVisser** [comment]
[log.1.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1508928/log.1.txt)

There's the log. The Miner windows (the terminal-looking ones right?) look exactly the same as they used to last month, just with the speeds 10-20% lower. It starts off at full speed, then within a few seconds looses that 10-20% speed and stays constant on that ever after.

Running claymore cryptonight directly gives me the same 573H/s as NHML does.

The performance boost PrEzi3 mentioned is rather irrelevant here, I'd say, as I experienced a performance drop over the past month, as has QWer6qed apparently.

**Comment by AdriaanVisser** [comment]
I checked the DaggerDecred mining window, and apparently I'm mining very slowly on high DAG, but fast on low DAG. Resetting to the AMD crypto specific driver, 17.11.1, did not resolve this. So I guess the question then becomes: how to maintain mining speed at high DAG?

**Comment by DillonN** [comment]
This is an issue with the miner programs and not NHML. Please keep issues related to NHML
