### ISSUE TITLE
NHML 1.8.2 crashes during benchmark and reinstalls

### ISSUE THREAD

**Issue by dkrav97** [nicehash/NiceHashMiner#681]
every time i open up the miner, it needs to reinstall all the miners, i start benchmark-crashes after 1 or 2 benchmarks complete, repeat-
running i7-4770k gpu + xfx radeon Vega 64 gpu
all antivirus is disabled

**Comment by DillonN** [comment]
Sounds like some miner programs are being deleted/corrupted when run. You said you disabled AV but please make sure since this very much sounds like an AV issue

It could be related to instability corrupting the programs when they are run

Either way it is not an issue with NHML and can't be fixed here
