### ISSUE TITLE
Cannot get SMA info after restart

### ISSUE THREAD

**Issue by rjkMiner** [nicehash/NiceHashMiner#697]
When I close NiceHashMiner and start it again it fails to mine since it cannot get SMA info from your servers. It reports that can not get profitable data and dont mine at all. Its very annoying problem, could you fix it ASAP?

**Comment by FoxProBTG** [comment]
эта проблема  в sma он не дает данный для оброботки

**Comment by FoxProBTG** [comment]
<?xml version="1.0"?>

-<doc>


-<assembly>

<name>log4net</name>

</assembly>


-<members>


-<member name="T:log4net.Appender.AdoNetAppender">

<summary> Appender that logs to a database. </summary>


-<remarks>


-<para>

<see cref="T:log4net.Appender.AdoNetAppender"/>
appends logging events to a table within a database. The appender can be configured to specify the connection string by setting the 
<see cref="P:log4net.Appender.AdoNetAppender.ConnectionString"/>
property. The connection type (provider) can be specified by setting the 
<see cref="P:log4net.Appender.AdoNetAppender.ConnectionType"/>
property. For more information on database connection strings for your specific database see 
<a href="http://www.connectionstrings.com/">http://www.connectionstrings.com/</a>
. 
</para>


-<para>
Records are written into the database either using a prepared statement or a stored procedure. The 
<see cref="P:log4net.Appender.AdoNetAppender.CommandType"/>
property is set to 
<see cref="F:System.Data.CommandType.Text"/>
(
<c>System.Data.CommandType.Text</c>
) to specify a prepared statement or to 
<see cref="F:System.Data.CommandType.StoredProcedure"/>
(
<c>System.Data.CommandType.StoredProcedure</c>
) to specify a stored procedure. 
</para>


-<para>
The prepared statement text or the name of the stored procedure must be set in the 
<see cref="P:log4net.Appender.AdoNetAppender.CommandText"/>
property. 
</para>


-<para>
The prepared statement or stored procedure can take a number of parameters. Parameters are added using the 
<see cref="M:log4net.Appender.AdoNetAppender.AddParameter(log4net.Appender.AdoNetAppenderParameter)"/>
method. This adds a single 
<see cref="T:log4net.Appender.AdoNetAppenderParameter"/>
to the ordered list of parameters. The 
<see cref="T:log4net.Appender.AdoNetAppenderParameter"/>
type may be subclassed if required to provide database specific functionality. The 
<see cref="T:log4net.Appender.AdoNetAppenderParameter"/>
specifies the parameter name, database type, size, and how the value should be generated using a 
<see cref="T:log4net.Layout.ILayout"/>
. 
</para>

</remarks>


-<example>
An example of a SQL Server table that could be logged to: 
<code lang="SQL"> CREATE TABLE [dbo].[Log] ( [ID] [int] IDENTITY (1, 1) NOT NULL , [Date] [datetime] NOT NULL , [Thread] [varchar] (255) NOT NULL , [Level] [varchar] (20) NOT NULL , [Logger] [varchar] (255) NOT NULL , [Message] [varchar] (4000) NOT NULL ) ON [PRIMARY] </code>

</example>


-<example>
An example configuration to log to the above table: 

-<code lang="XML" escaped="true">


-<appender name="AdoNetAppender_SqlServer" type="log4net.Appender.AdoNetAppender">

<connectionType value="System.Data.SqlClient.SqlConnection, System.Data, Version=1.0.3300.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"/>

<connectionString value="data source=SQLSVR;initial catalog=test_log4net;integrated security=false;persist security info=True;User ID=sa;Password=sa"/>

<commandText value="INSERT INTO Log ([Date],[Thread],[Level],[Logger],[Message]) VALUES (@log_date, @thread, @log_level, @logger, @message)"/>


-<parameter>

<parameterName value="@log_date"/>

<dbType value="DateTime"/>

<layout type="log4net.Layout.PatternLayout" value="%date{yyyy'-'MM'-'dd HH':'mm':'ss'.'fff}"/>

</parameter>


-<parameter>

<parameterName value="@thread"/>

<dbType value="String"/>

<size value="255"/>

<layout type="log4net.Layout.PatternLayout" value="%thread"/>

</parameter>


-<parameter>

<parameterName value="@log_level"/>

<dbType value="String"/>

<size value="50"/>

<layout type="log4net.Layout.PatternLayout" value="%level"/>

</parameter>


-<parameter>

<parameterName value="@logger"/>

<dbType value="String"/>

<size value="255"/>

<layout type="log4net.Layout.PatternLayout" value="%logger"/>

</parameter>


-<parameter>

<parameterName value="@message"/>

<dbType value="String"/>

<size value="4000"/>

<layout type="log4net.Layout.PatternLayout" value="%message"/>

</parameter>

</appender>

</code>

</example>

<author>Julian Biddle</author>

<author>Nicko Cadell</author>

<author>Gert Driesen</author>

<author>Lance Nehring</author>

</member>


-<member name="T:log4net.Appender.BufferingAppenderSkeleton">


-<summary>
Abstract base class implementation of 
<see cref="T:log4net.Appender.IAppender"/>
that buffers events in a fixed size buffer. 
</summary>


-<remarks>


-<para>
This base class should be used by appenders that need to buffer a number of events before logging them. For example the 
<see cref="T:log4net.Appender.AdoNetAppender"/>
buffers events and then submits the entire contents of the buffer to the underlying database in one go. 
</para>


-<para>
Subclasses should override the 
<see cref="M:SendBuffer(LoggingEvent[])"/>
method to deliver the buffered events. 
</para>


-<para>
The BufferingAppenderSkeleton maintains a fixed size cyclic buffer of events. The size of the buffer is set using the 
<see cref="P:log4net.Appender.BufferingAppenderSkeleton.BufferSize"/>
property. 
</para>


-<para>
A 
<see cref="T:log4net.Core.ITriggeringEventEvaluator"/>
is used to inspect each event as it arrives in the appender. If the 
<see cref="P:log4net.Appender.BufferingAppenderSkeleton.Evaluator"/>
triggers, then the current buffer is sent immediately (see 
<see cref="M:SendBuffer(LoggingEvent[])"/>
). Otherwise the event is stored in the buffer. For example, an evaluator can be used to deliver the events immediately when an ERROR event arrives. 
</para>


-<para>
The buffering appender can be configured in a 
<see cref="P:log4net.Appender.BufferingAppenderSkeleton.Lossy"/>
mode. By default the appender is NOT lossy. When the buffer is full all the buffered events are sent with 
<see cref="M:SendBuffer(LoggingEvent[])"/>
. If the 
<see cref="P:log4net.Appender.BufferingAppenderSkeleton.Lossy"/>
property is set to 
<c>true</c>
then the buffer will not be sent when it is full, and new events arriving in the appender will overwrite the oldest event in the buffer. In lossy mode the buffer will only be sent when the 
<see cref="P:log4net.Appender.BufferingAppenderSkeleton.Evaluator"/>
triggers. This can be useful behavior when you need to know about ERROR events but not about events with a lower level, configure an evaluator that will trigger when an ERROR event arrives, the whole buffer will be sent which gives a history of events leading up to the ERROR event. 
</para>

</remarks>

<author>Nicko Cadell</author>

<author>Gert Driesen</author>

</member>


-<member name="T:log4net.Appender.AppenderSkeleton">


-<summary>
Abstract base class implementation of 
<see cref="T:log4net.Appender.IAppender"/>
. 
</summary>


-<remarks>

<para> This class provides the code for common functionality, such as support for threshold filtering and support for general filters. </para>


-<para>
Appenders can also implement the 
<see cref="T:log4net.Core.IOptionHandler"/>
interface. Therefore they would require that the 
<see cref="M:IOptionHandler.ActivateOptions()"/>
method be called after the appenders properties have been configured. 
</para>

</remarks>

<author>Nicko Cadell</author>

<author>Gert Driesen</author>

</member>


-<member name="T:log4net.Appender.IAppender">

<summary> Implement this interface for your own strategies for printing log statements. </summary>


-<remarks>


-<para>
Implementors should consider extending the 
<see cref="T:log4net.Appender.AppenderSkeleton"/>
class which provides a default implementation of this interface. 
</para>


-<para>
Appenders can also implement the 
<see cref="T:log4net.Core.IOptionHandler"/>
interface. Therefore they would require that the 
<see cref="M:IOptionHandler.ActivateOptions()"/>
method be called after the appenders properties have been configured. 
</para>

</remarks>

<author>Nicko Cadell</author>

<author>Gert Driesen</author>

</member>


-<member name="M:log4net.Appender.IAppender.Close">

<summary> Closes the appender and releases resources. </summary>


-<remarks>

<para> Releases any resources allocated within the appender such as file handles, network connections, etc. </para>

<para> It is a programming error to append to a closed appender. </para>

</remarks>

</member>


-<member name="M:log4net.Appender.IAppender.DoAppend(log4net.Core.LoggingEvent)">

<summary> Log the logging event in Appender specific way. </summary>

<param name="loggingEvent">The event to log</param>


-<remarks>

<para> This method is called to log a message into this appender. </para>

</remarks>

</member>


-<member name="P:log4net.Appender.IAppender.Name">

<summary> Gets or sets the name of this appender. </summary>

<value>The name of the appender.</value>


-<remarks>

<para>The name uniquely identifies the appender.</para>

</remarks>

</member>


-<member name="T:log4net.Appender.IBulkAppender">

<summary> Interface for appenders that support bulk logging. </summary>


-<remarks>


-<para>
This interface extends the 
<see cref="T:log4net.Appender.IAppender"/>
interface to support bulk logging of 
<see cref="T:log4net.Core.LoggingEvent"/>
objects. Appenders should only implement this interface if they can bulk log efficiently. 
</para>

</remarks>

<author>Nicko Cadell</author>

</member>


-<member name="M:log4net.Appender.IBulkAppender.DoAppend(log4net.Core.LoggingEvent[])">

<summary> Log the array of logging events in Appender specific way. </summary>

<param name="loggingEvents">The events to log</param>


-<remarks>

<para> This method is called to log an array of events into this appender. </para>

</remarks>

</member>


-<member name="T:log4net.Core.IOptionHandler">

<summary> Interface used to delay activate a configured object. </summary>


-<remarks>

<para> This allows an object to defer activation of its options until all options have been set. This is required for components which have related options that remain ambiguous until all are set. </para>


-<para>
If a component implements this interface then the 
<see cref="M:log4net.Core.IOptionHandler.ActivateOptions"/>
method must be called by the container after its all the configured properties have been set and before the component can be used. 
</para>

</remarks>

<author>Nicko Cadell</author>

</member>


-<member name="M:log4net.Core.IOptionHandler.ActivateOptions">

<summary> Activate the options that were previously set with calls to properties. </summary>


-<remarks>

<para> This allows an object to defer activation of its options until all options have been set. This is required for components which have related options that remain ambiguous until all are set. </para>

<para> If a component implements this interface then this method must be called after its properties have been set before the component can be used. </para>

</remarks>

</member>


-<member name="F:log4net.Appender.AppenderSkeleton.c_renderBufferSize">

<summary> Initial buffer size </summary>

</member>


-<member name="F:log4net.Appender.AppenderSkeleton.c_renderBufferMaxCapacity">

<summary> Maximum buffer size before it is recycled </summary>

</member>


-<member name="M:log4net.Appender.AppenderSkeleton.#ctor">

<summary> Default constructor </summary>


-<remarks>

<para>Empty default constructor</para>

</remarks>

</member>


-<member name="M:log4net.Appender.AppenderSkeleton.Finalize">


-<summary>
Finalizes this appender by calling the implementation's 
<see cref="M:log4net.Appender.AppenderSkeleton.Close"/>
method. 
</summary>


-<remarks>


-<para>
If this appender has not been closed then the 
<c>Finalize</c>
method will call 
<see cref="M:log4net.Appender.AppenderSkeleton.Close"/>
. 
</para>

</remarks>

</member>


-<member name="M:log4net.Appender.AppenderSkeleton.ActivateOptions">

<summary> Initialize the appender based on the options set </summary>


-<remarks>


-<para>
This is part of the 
<see cref="T:log4net.Core.IOptionHandler"/>
delayed object activation scheme. The 
<see cref="M:log4net.Appender.AppenderSkeleton.ActivateOptions"/>
method must be called on this object after the configuration properties have been set. Until 
<see cref="M:log4net.Appender.AppenderSkeleton.ActivateOptions"/>
is called this object is in an undefined state and must not be used. 
</para>


-<para>
If any of the configuration properties are modified then 
<see cref="M:log4net.Appender.AppenderSkeleton.ActivateOptions"/>
must be called again. 
</para>

</remarks>

</member>


-<member name="M:log4net.Appender.AppenderSkeleton.Close">

<summary> Closes the appender and release resources. </summary>


-<remarks>

<para> Release any resources allocated within the appender such as file handles, network connections, etc. </para>

<para> It is a programming error to append to a closed appender. </para>


-<para>
This method cannot be overridden by subclasses. This method delegates the closing of the appender to the 
<see cref="M:log4net.Appender.AppenderSkeleton.OnClose"/>
method which must be overridden in the subclass. 
</para>

</remarks>

</member>


-<member name="M:log4net.Appender.AppenderSkeleton.DoAppend(log4net.Core.LoggingEvent)">


-<summary>
Performs threshold checks and invokes filters before delegating actual logging to the subclasses specific 
<see cref="M:Append(LoggingEvent)"/>
method. 
</summary>

<param name="loggingEvent">The event to log.</param>


-<remarks>


-<para>
This method cannot be overridden by derived classes. A derived class should override the 
<see cref="M:Append(LoggingEvent)"/>
method which is called by this method. 
</para>

<para> The implementation of this method is as follows: </para>


-<para>


-<list type="bullet">


-<item>


-<description>
Checks that the severity of the 
<paramref name="loggingEvent"/>
is greater than or equal to the 
<see cref="P:log4net.Appender.AppenderSkeleton.Threshold"/>
of this appender.
</description>

</item>


-<item>


-<description>
Checks that the 
<see cref="T:log4net.Filter.IFilter"/>
chain accepts the 
<paramref name="loggingEvent"/>
. 
</description>

</item>


-<item>


-<description>
Calls 
<see cref="M:PreAppendCheck()"/>
and checks that it returns 
<c>true</c>
.
</description>

</item>

</list>

</para>


-<para>
If all of the above steps succeed then the 
<paramref name="loggingEvent"/>
will be passed to the abstract 
<see cref="M:Append(LoggingEvent)"/>
method. 
</para>

</remarks>

</member>


-<member name="M:log4net.Appender.AppenderSkeleton.DoAppend(log4net.Core.LoggingEvent[])">


-<summary>
Performs threshold checks and invokes filters before delegating actual logging to the subclasses specific 
<see cref="M:Append(LoggingEvent[])"/>
method. 
</summary>

<param name="loggingEvents">The array of events to log.</param>


-<remarks>


-<para>
This method cannot be overridden by derived classes. A derived class should override the 
<see cref="M:Append(LoggingEvent[])"/>
method which is called by this method. 
</para>

<para> The implementation of this method is as follows: </para>


-<para>


-<list type="bullet">


-<item>


-<description>
Checks that the severity of the 
<paramref name="loggingEvents"/>
is greater than or equal to the 
<see cref="P:log4net.Appender.AppenderSkeleton.Threshold"/>
of this appender.
</description>

</item>


-<item>


-<description>
Checks that the 
<see cref="T:log4net.Filter.IFilter"/>
chain accepts the 
<paramref name="loggingEvents"/>
. 
</description>

</item>


-<item>


-<description>
Calls 
<see cref="M:PreAppendCheck()"/>
and checks that it returns 
<c>true</c>
.
</description>

</item>

</list>

</para>


-<para>
If all of the above steps succeed then the 
<paramref name="loggingEvents"/>
will be passed to the 
<see cref="M:Append(LoggingEvent[])"/>
method. 
</para>

</remarks>

</member>


-<member name="M:log4net.Appender.AppenderSkeleton.FilterEvent(log4net.Core.LoggingEvent)">

<summary> Test if the logging event should we output by this appender </summary>

<param name="loggingEvent">the event to test</param>


-<returns>

<c>true</c>
if the event should be output, 
<c>false</c>
if the event should be ignored
</returns>


-<remarks>

<para> This method checks the logging event against the threshold level set on this appender and also against the filters specified on this appender. </para>

<para> The implementation of this method is as follows: </para>


-<para>


-<list type="bullet">


-<item>


-<description>
Checks that the severity of the 
<paramref name="loggingEvent"/>
is greater than or equal to the 
<see cref="P:log4net.Appender.AppenderSkeleton.Threshold"/>
of this appender.
</description>

</item>


-<item>


-<description>
Checks that the 
<see cref="T:log4net.Filter.IFilter"/>
chain accepts the 
<paramref name="loggingEvent"/>
. 
</description>

</item>

</list>

</para>

</remarks>

</member>


-<member name="M:log4net.Appender.AppenderSkeleton.AddFilter(log4net.Filter.IFilter)">

<summary> Adds a filter to the end of the filter chain. </summary>

<param name="filter">the filter to add to this appender</param>


-<remarks>

<para> The Filters are organized in a linked list. </para>

<para> Setting this property causes the new filter to be pushed onto the back of the filter chain. </para>

</remarks>

</member>


-<member name="M:log4net.Appender.AppenderSkeleton.ClearFilters">

<summary> Clears the filter list for this appender. </summary>


-<remarks>

<para> Clears the filter list for this appender. </para>

</remarks>

</member>


-<member name="M:log4net.Appender.AppenderSkeleton.IsAsSevereAsThreshold(log4net.Core.Level)">

<summary> Checks if the message level is below this appender's threshold. </summary>


-<param name="level">

<see cref="T:log4net.Core.Level"/>
to test against.
</param>


-<remarks>


-<para>
If there is no threshold set, then the return value is always 
<c>true</c>
. 
</para>

</remarks>


-<returns>

<c>true</c>
if the 
<paramref name="level"/>
meets the 
<see cref="P:log4net.Appender.AppenderSkeleton.Threshold"/>
requirements of this appender. 
</returns>

</member>


-<member name="M:log4net.Appender.AppenderSkeleton.OnClose">

<summary> Is called when the appender is closed. Derived classes should override this method if resources need to be released. </summary>


-<remarks>

<para> Releases any resources allocated within the appender such as file handles, network connections, etc. </para>

<para> It is a programming error to append to a closed appender. </para>

</remarks>

</member>


-<member name="M:log4net.Appender.AppenderSkeleton.Append(log4net.Core.LoggingEvent)">


-<summary>
Subclasses of 
<see cref="T:log4net.Appender.AppenderSkeleton"/>
should implement this method to perform actual logging. 
</summary>

<param name="loggingEvent">The event to append.</param>


-<remarks>


-<para>
A subclass must implement this method to perform logging of the 
<paramref name="loggingEvent"/>
. 
</para>


-<para>
This method will be called by 
<see cref="M:DoAppend(LoggingEvent)"/>
if all the conditions listed for that method are met. 
</para>


-<para>
To restrict the logging of events in the appender override the 
<see cref="M:PreAppendCheck()"/>
method. 
</para>

</remarks>

</member>


-<member name="M:log4net.Appender.AppenderSkeleton.Append(log4net.Core.LoggingEvent[])">

<summary> Append a bulk array of logging events. </summary>

<param name="loggingEvents">the array of logging events</param>


-<remarks>


-<para>
This base class implementation calls the 
<see cref="M:Append(LoggingEvent)"/>
method for each element in the bulk array. 
</para>


-<para>
A sub class that can better process a bulk array of events should override this method in addition to 
<see cref="M:Append(LoggingEvent)"/>
. 
</para>

</remarks>

</member>


-<member name="M:log4net.Appender.AppenderSkeleton.PreAppendCheck">


-<summary>
Called before 
<see cref="M:Append(LoggingEvent)"/>
as a precondition. 
</summary>


-<remarks>


-<para>
This method is called by 
<see cref="M:DoAppend(LoggingEvent)"/>
before the call to the abstract 
<see cref="M:Append(LoggingEvent)"/>
method. 
</para>


-<para>
This method can be overridden in a subclass to extend the checks made before the event is passed to the 
<see cref="M:Append(LoggingEvent)"/>
method. 
</para>

<para> A subclass should ensure that they delegate this call to this base class if it is overridden. </para>

</remarks>


-<returns>

<c>true</c>
if the call to 
<see cref="M:Append(LoggingEvent)"/>
should proceed.
</returns>

</member>


-<member name="M:log4net.Appender.AppenderSkeleton.RenderLoggingEvent(log4net.Core.LoggingEvent)">


-<summary>
Renders the 
<see cref="T:log4net.Core.LoggingEvent"/>
to a string. 
</summary>

<param name="loggingEvent">The event to render.</param>

<returns>The event rendered as a string.</returns>


-<remarks>


-<para>
Helper method to render a 
<see cref="T:log4net.Core.LoggingEvent"/>
to a string. This appender must have a 
<see cref="P:log4net.Appender.AppenderSkeleton.Layout"/>
set to render the 
<paramref name="loggingEvent"/>
to a string. 
</para>

<para>If there is exception data in the logging event and the layout does not process the exception, this method will append the exception text to the rendered string. </para>


-<para>
Where possible use the alternative version of this method 
<see cref="M:RenderLoggingEvent(TextWriter,LoggingEvent)"/>
. That method streams the rendering onto an existing Writer which can give better performance if the caller already has a 
<see cref="T:System.IO.TextWriter"/>
open and ready for writing. 
</para>

</remarks>

</member>


-<member name="M:log4net.Appender.AppenderSkeleton.RenderLoggingEvent(System.IO.TextWriter,log4net.Core.LoggingEvent)">


-<summary>
Renders the 
<see cref="T:log4net.Core.LoggingEvent"/>
to a string. 
</summary>

<param name="loggingEvent">The event to render.</param>

<param name="writer">The TextWriter to write the formatted event to</param>


-<remarks>


-<para>
Helper method to render a 
<see cref="T:log4net.Core.LoggingEvent"/>
to a string. This appender must have a 
<see cref="P:log4net.Appender.AppenderSkeleton.Layout"/>
set to render the 
<paramref name="loggingEvent"/>
to a string. 
</para>

<para>If there is exception data in the logging event and the layout does not process the exception, this method will append the exception text to the rendered string. </para>


-<para>
Use this method in preference to 
<see cref="M:RenderLoggingEvent(LoggingEvent)"/>
where possible. If, however, the caller needs to render the event to a string then 
<see cref="M:RenderLoggingEvent(LoggingEvent)"/>
does provide an efficient mechanism for doing so. 
</para>

</remarks>

</member>


-<member name="F:log4net.Appender.AppenderSkeleton.m_layout">

<summary> The layout of this appender. </summary>


-<remarks>
See 
<see cref="P:log4net.Appender.AppenderSkeleton.Layout"/>
for more information. 
</remarks>

</member>


-<member name="F:log4net.Appender.AppenderSkeleton.m_name">

<summary> The name of this appender. </summary>


-<remarks>
See 
<see cref="P:log4net.Appender.AppenderSkeleton.Name"/>
for more information. 
</remarks>

</member>


-<member name="F:log4net.Appender.AppenderSkeleton.m_threshold">

<summary> The level threshold of this appender. </summary>


-<remarks>

<para> There is no level threshold filtering by default. </para>


-<para>
See 
<see cref="P:log4net.Appender.AppenderSkeleton.Threshold"/>
for more information. 
</para>

</remarks>

</member>


-<member name="F:log4net.Appender.AppenderSkeleton.m_errorHandler">

<summary> It is assumed and enforced that errorHandler is never null. </summary>


-<remarks>

<para> It is assumed and enforced that errorHandler is never null. </para>


-<para>
See 
<see cref="P:log4net.Appender.AppenderSkeleton.ErrorHandler"/>
for more information. 
</para>

</remarks>

</member>


-<member name="F:log4net.Appender.AppenderSkeleton.m_headFilter">

<summary> The first filter in the filter chain. </summary>


-<remarks>


-<para>

**Comment by TomKein** [comment]
Проблема в SMA? А чья это служба? не ваша ли? Не можете наладить службу, сохраняйте ее данные между перезагрузками, сделайте значения по умолчанию, сделайте хоть что нибудь! Полезность продукта при невозможности его автоматического запуска - НОЛЬ!!!

**Comment by rjkMiner** [comment]
И что делать? Программа банально не работает.

**Comment by rjkMiner** [comment]
Есть хоть какойто способ запустить NiceHashMinerLegacy?

**Comment by FoxProBTG** [comment]
ЕСТЬ


2017-12-03 2:57 GMT+04:00 rjkMiner <notifications@github.com>:

**Comment by FoxProBTG** [comment]
ПРОСТО В НОВОЙ ВЕРФИ НЕ ПРАВИЛЬНО НАПИСАН КОД И ДОБАВЛЕНЫ МНОГО ГОРНЫХ УСТРОЙСТВ КОНФЛИКТ ПРОИСХОДИТ С СЕРВЕРОМ Я НЕ ЯВЛЯЮСЬ СОТРУДНИКОМ НАЙСА Я САМ ПО СЕБЕ НО Я ЗДЕЛАЛ ПРОГУ НАЙСА
