### ISSUE TITLE
Memory Alloc Failed: VirtualAlloc Failed. Starting Single Thread, No Affinity.

### ISSUE THREAD

**Issue by fugzibogs** [nicehash/NiceHashMiner#703]
Hi,

I recently set up a new computer with three EVGA GEFORCE GTX 1080 Ti hybrids (which give me around $14.00-15.00 USD a day and runs at 1900-2000 MHz) and an AMD Ryzen Threadripper 1950x. 

Unfortunately, the Threadripper is not working properly as you can see from the title of the post: Memory Alloc Failed: VirtualAlloc Failed. Starting Single Thread, No Affinity. This processor has a constant clock speed running at 4000MHz even while nothing running. But when I try to use it for mining on NiceHash Miner 2 it gives me that error (Memory Alloc Failed: VirtualAlloc Failed. Starting Single Thread, No Affinity) and barely runs at 200 H/s.  Even during the mining it has a constant clock speed of 4000 MHz but only uses around 37% of its capability (or Load). 

I tried downloading NHML but it still came up with the same error and my GPUs actually didn't produce as much on this program as opposed to NiceHash Miner v2.0.1.5.  

I saw the other post kind of similar to this one but it did not help so I am posting again.

Can someone help me?

**Comment by DillonN** [comment]
You need to enable locked pages

https://github.com/nicehash/NiceHashMinerLegacy/wiki/CPU-Mining-Optimization#lockedhuge-pages

**Comment by fugzibogs** [comment]
Thank you for responding but I really have no idea how to do either of those options I tried opening my command prompt and typing in bin"\xmrig\xmrig.exe". But nothing worked. I am looking online for better instructions but am not having any luck. Would it be possible for you to tell me exactly what to do?

**Comment by fugzibogs** [comment]
@DillonN is this what needs to be done? https://blog.sqlauthority.com/2017/06/15/sql-server-enable-lock-pages-memory/

**Comment by fugzibogs** [comment]
Thank you DillonN that seemed to make it work a bit. I had to enable gpedit.msc on my windows 10 home edition and worked from there.

The "2" cpus are running at maybe 700 H/s. But unfortunately, it is not very stable. They never run for more than 10 seconds or so before going straight back to 0.000.

Is there a way to make it more stable? 
And is there a way to increase it so I am able to use more than 36% of my processor? I saw somewhere that they were able to get 1.3KHs. Is that possible for me?

**Comment by DillonN** [comment]
There was an error in speed reporting in NHML for xmr-stak-cpu that is fixed now

If you are still seeing a problem you can try using the other CPU miner (e.g. xmrig if you are using xmr-stak)

Optimal performance for CPU mining is to not use 100% of the CPU, because mining is highly dependent on cache space. Generally you need 2MB of cache per mining thread, so with a 1950x that would be around half the available threads. You can try increasing the thread count by lowering "Less Threads" for xmr-stak-cpu, but you should notice that after a certain "sweet-spot" performance will start going down (and CPU usage will unnecessarily go up)
