### ISSUE TITLE
Nicehash theif my BTC.

### ISSUE THREAD

**Issue by baqradze1** [nicehash/NiceHashMiner#715]
Very big difference, All time. In Nicehash legacy software i receiving ~10$ on the website i received not more 8$, Where is my 2$?
Please don't tell me about this: https://www.nicehash.com/help/why-is-your-profitability-online-different-than-in-nicehash-miner
![nicehash](https://user-images.githubusercontent.com/25580135/33547219-d3496aaa-d8fc-11e7-8d07-89a9a70f4dc1.jpg)
![nicehash1](https://user-images.githubusercontent.com/25580135/33547221-d367d968-d8fc-11e7-8b7e-16568bb27fbb.jpg)

**Comment by maxgamurar** [comment]
Yes, I can confirm I observe such behavior.  I plan to log local mined btc vs what I am getting paid for from Nicehash.
I do regularly compare local profit vs what NH website shows, in 50% of cases it does not match..
What u posted here is not enough but I do confirm I suspect something is getting stolen.

**Comment by baqradze1** [comment]
If i found Nicehash cheating facts, It would be very good, But i can't ( i don't know how.) :(

**Comment by kuzotronic** [comment]
Agreed, smth is wrong. Using Monitor for NH from google store still gives the same result. Around 10-20% off from what NH shows for each individual rig. 

What's weird, that at the end of the day I get the the amount of cash according to monitor program not NH in windows tab.

Thanks

**Comment by RealityRipple** [comment]
In the link at the top of the page you said not to tell you about, where it says "Please read this first". Read that page. 
Essentially, you are not being paid for the rate your mining works at, but for the shares you find. It's up to chance whether you make more or less than what the NiceHash application says you should be making.

**Comment by baqradze1** [comment]
I was mining 1 year on Nicehash and i have not problems like this.

**Comment by kuzotronic** [comment]
It seems that this profit miscalculation is somewhat connected to cryptonight AMD mining. Last hour I got more with monero on my amd cards but I force switched to dagger/lbry that shows less in NH window but my income increased in monitor for NH google play program.

So that's weird. The thing is, that my 13xRX 570 rig pulls 2000w from the wall mining dual coins and only 1200w mining monero, also the temps are 10-15C lower with the latter. But the profit is just not stable((

**Comment by maxgamurar** [comment]
Please check my screenshots.
My rig with 5 1080ti running for 1 hour with X11 ghots - approx rat 3.9 mBTC per day.
Webpage shows 0.0004/day, during that hour. 
Any comments on that?


![nhm_screen_miner](https://user-images.githubusercontent.com/3941277/33586317-73b7574c-d99b-11e7-9b3f-940d64ca7e08.png)

![nhm_screen_webstats](https://user-images.githubusercontent.com/3941277/33586318-73f51992-d99b-11e7-8bc7-6e1540169a96.PNG)

![nhm_screen_webstats_chart](https://user-images.githubusercontent.com/3941277/33586319-7432c2ec-d99b-11e7-8239-2923bf871524.png)

**Comment by giordanbetat** [comment]
Mine is the same problem of maxgamurar, I took the X11Ghost by guarantee

**Comment by nerdatwork** [comment]
Its a known issue of software and web stats not matching. You still get the right amount of BTC you mined.

**Comment by maxgamurar** [comment]
If its a known issue then the source of wrong info should be fixed or removed.
Also, how do I track what I've actually mined?

**Comment by maxgamurar** [comment]
As I can see the amount to be paid is calculated from web stats, not from what I see on NHML app log....

**Comment by maxgamurar** [comment]
So I presume area marked in red - 3.9mBTC per hour - everything what was mined is stolen
![nhm_screen_webstats_chart2](https://user-images.githubusercontent.com/3941277/33590021-1890d4a6-d9af-11e7-8543-18a3c049e9ce.png)

**Comment by ecionis** [comment]
Same problem (as maxgamurar) at 04:00-06:00 (UTC+3)

Interest picture:
![nh_fail](https://user-images.githubusercontent.com/26205885/33609998-32a3eae6-d9db-11e7-9510-b64724c79433.png)

All miners did 554GH/s on X11Gost, but got 0.0033 BTC/GH/day

**Comment by craxis** [comment]
I saw the exact same results with X11GOST yesterday, high hash rate shown in the miner, but the payout does not match.

**Comment by Jakobhoss** [comment]
This happens for every algorithm. And that´s why I´m not providing hashing power to Nicehash anymore. Same thing every time... algo price goes up, my rigs swith and immidiatelly the price drops, then hashing for a shitty price. Then another algo rises, and again rigs switch. And a few minutes later the price drops again. Nicehash is a pain in the ass for providers of hashing power. Unstable prices, the client once works then again has problems (as example, when using the NH client GPU 0 shows half of the time 0 MH, without client mining works fine), and the worst... it´s more profitable to mine on an pool than on Nicehash. Why provide hashing power when the result is a loss?
Get rid of the client and write at least your own batch files. You´ll get much better results than with the client. 
I´m writing a programm that will ask the api on nh for prices and compare them the with pool profitability, so when on NH the price for an algo is high my rigs mine on NH, otherwise they mine on my pools directly for the chosen coins (ETH, Monero, Zcash).
Don´t waste yout time with NH, it´s much more prifitable to mine coins for yourself, especially when the block reward is high, for example HUSH with BR of 12.5.

**Comment by baqradze1** [comment]
![cry](https://user-images.githubusercontent.com/25580135/33642151-0e4b677e-da52-11e7-954d-09538fd62db4.JPG)
![nh](https://user-images.githubusercontent.com/25580135/33642152-0e6a4b26-da52-11e7-835b-7ceb5bc2ed76.JPG)
![nh1](https://user-images.githubusercontent.com/25580135/33642153-0e865faa-da52-11e7-89f5-936d1e5cc36b.JPG)
![nhm1](https://user-images.githubusercontent.com/25580135/33642154-0ea3f718-da52-11e7-9f5b-518038d5e6e7.JPG)
![nhm2](https://user-images.githubusercontent.com/25580135/33642156-0ec8aa68-da52-11e7-85b6-092b828d4ebe.jpg)
![nhm3](https://user-images.githubusercontent.com/25580135/33642157-0ee67fde-da52-11e7-8c43-36cc88cb7fd0.jpg)

**Comment by utc99** [comment]
I believe most of problems are because local miner does not get the right profitability data, if miner gets high profitability, it starts mining, and if it drops a bit and miner does not get a new data in time, then you see differences in local and web stats. This profitability issue is really big problem for Nicehash team, cause its on a rampage now, so many miners cannot mine or have bad profitability, and i cannot restart them, because they will not event start mining again because of this bug of probably NH DoS service provider or whats blocking those miners.

**Comment by Jakobhoss** [comment]
It doesn´t matter what who believes, I see the facts. I´ve been mining before Nicehash began and it´s simple as that... Nicehash has much to many users and as I mentioned in a post earlier, since July this year the massive user count makes profitability a joke. Unexperiecend users try to squeeze out some bucks before they sell their gaming hardware they got for christmas and nicehash helped to make mining a joke. Compare mining before July and now. Stable prices, when diff got up you got better rewards for a long time, much less job switches, and you had not to rewrite your batch files daily because of some problem with any client. 
**I don´t believe they stale shares, I simply think the server infrastructure is made for a quarter of the user count they have now.**
And now they have massive problems with hundereds of hardware combinations that try somehow to be compatible with their client... a selfmade problem. Don´t write programs for professional purposes when you want to make it to work with non professionals. Nicehash has made it too easy to provide hashing power and now pandoras box is open. Let´s see how they try to close it...

**Comment by AngryOverlord** [comment]
I think you guys are confusing how much profit you can get from mining a coin with how nicehash works. Nicehash works on a bidding system where other people pay for your hashing, you are paid based on how much the bids are paying per share. what you are seeing with those long dips is that that is the highest bid for that type of algorithm at the time for your hashrate. Note this is not the same as how much you would get in a pool where you only mine specific coins.
