### ISSUE TITLE
NiceHash 1.8.0.2 issues

### ISSUE THREAD

**Issue by NameUnavailable** [nicehash/NiceHashMiner#73]
So we used nicehash until today without any problems.. now we have some issues ; we're running 5x gtx 1070 oc and 1x gtx 1080 a8c. This morning, nicehash crashed and our computer rebooted. On reboot nicehash offered to upgrade to the new version, so we downloaded the update. Now we have to redo all benchmarks but running the benchmark, it crashes. It's impossible to do the benchmarks even algorithms one at a time and gpus one at a time. (we're running them on precise) Nicehash offered us to boost virtual memory and since we want to run it with windows upon launch... well the virtual memory pops up everytime so we boost the virtual memory at 48000... still the benchmarks wont complete and crash and we're stuck there. Tried running NiceHash without benchmarking and only the 1080 will mine. We're wondering if it's a problem that affects more people since the new update. Should we go back to the 1.8.0.1 since it worked stable or should we switch to claymore or better?
Thanks

**Comment by DillonN** [comment]
Hello @NameUnavailable, sorry you're having issues with NHML. 

Instead of rebenchmarking all your algorithms, you can copy the `configs` folder from your old NHML 1.8.0.1 folder into the new one. That will retain almost all of your settings. 

If when you have your benchmark info back you still get errors on launching algorithms, please post back here with the log file found in the `logs` folder.

**Comment by NameUnavailable** [comment]
![untitled](https://user-images.githubusercontent.com/30479416/28642345-1d469acc-7220-11e7-9408-9a47ccf5bf0c.jpg)

**Comment by DillonN** [comment]
That notice is standard when copying over your configs. The previous configs will be set that miners have downloaded, but the new folder won't have them downloaded. You can just hit Yes and it will download automatically still.
