### ISSUE TITLE
Rx 580 drivers

### ISSUE THREAD

**Issue by Beginnero1** [nicehash/NiceHashMiner#767]
So after nicehash came back I got a new card rx 580 nitro+ sapphire 8gb, however it's not recognized in nicehash application, does anyone know how to downgrade to crimson drivers ?
Thanks !

**Comment by darkstalker85** [comment]
For win10 x64 install crimson relive blockchain beta drivers...It will work!

**Comment by Beginnero1** [comment]
thank you !

**Comment by baqradze1** [comment]
it is not solution. I don't want install blockchain beta driver for fix this issue. Last adrenalin drivers does not recognized by nicehash miner

**Comment by ghcoin** [comment]
17.11.4 driver detects. Latest driver doesn't detect GPU

**Comment by dadoremix** [comment]
yep .. same here
17.12.1 and 172.12.2 not working
rx580 8gb

**Comment by vladikt** [comment]
Mates, 

I got a RX580 and GPU utilization is 16% according to afterburner 0-1% according to Task Manger and memory utilization is 1.5gb our of 8. Is this normal? I feel like it should be working a bit harder. Any help would be greatly appreciated.

Using Nicehash 1.8.2.0 and Win10-64Bit-Crimson-ReLive-Beta-Blockchain-Workloads video driver
Old dell desktop with Xeon CPU PCIe 2.0 X16 
The card has 8 pin power plug, but I'm using a 6pin since my powersupply doesn't have 8, could this cause any issues?

Thanks

Vlad

**Comment by dadoremix** [comment]
very likely
it is best to have 8 + 6 or 8 pin as main

**Comment by vladikt** [comment]
thanks I'll give it a try

**Comment by Beginnero1** [comment]
Does anyone know why is my card getting to 65C with 80% + fan speed on dual mining ethereum + lbry ?
Im getting around 24,3 Mh/s ethereum + 70Mh/s lbry without modded bios.

**Comment by darkstalker85** [comment]
Dual mining mode very strong! I have 70-71 on dual with 70% fan speed and the card eat about 160-170 watts!!! But i mod the bios and have 29 MHash... Try only dagger hashimoto(i have 60-65 temp.)

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
