### ISSUE TITLE
Unpaid balance is going down

### ISSUE THREAD

**Issue by maxgamurar** [nicehash/NiceHashMiner#772]
Hello there!
I was checking my rig with NHM legacy and noticed that balance was decreased!!
When I've checked once - it was 0.098, after 5 mins 0.093, how is that possible?

**Comment by adem4ik** [comment]
In what currency? BTC, USD or something else?

**Comment by maxgamurar** [comment]
its in BTC

**Comment by brecko1** [comment]
the same thing here

**Comment by adem4ik** [comment]
NHML gets balance info from nicehash.com, so it is case for https://www.nicehash.com/support

anyway you should provide some proofs for them:
1) 2 screenshots of NHML with the time and date where balance goes down
2) 2 screenshots from https://www.nicehash.com/miner/<your_wallet> where balance goes down

**Comment by cea4** [comment]
same thing here where i noticed yesterday unpaid balance reaches a certain amount and when i refresh it, it goes down like $10.  What is going on here?  That should not be possible and makes very suspicious.

**Comment by cea4** [comment]
i thought it was just yesterday but today the same thing is happening again.

**Comment by cea4** [comment]
I realized it's the price of bitcoin that's fluctuating.  the amount of BTC goes up, but the dollar amount fluctuates because of BTC going up and down.  Makes sense now :)    I hope this helps anyone else.  I looked at the BTC amount and that amount was going up, but the Dollar amount went down slightly because BTC is going up and down like crazy.       Again i hope this helped anyone else

**Comment by jimmyhackers** [comment]
either that or nicehash has adjusted things ever so slightly so they have a little more income to pay off all that money they had stolen.

i always find it dubious how im told i should be getting between 6 - 7 gbp a day but usually end up with around 5-6pound.

**Comment by S74nk0** [comment]
Not related to nhm client
