### ISSUE TITLE
Parallel benchmarking gone, resizable benchmark window gone

### ISSUE THREAD

**Issue by gulo-gulo** [nicehash/NiceHashMiner#848]
I noticed that parallel benchmarking is gone in this newest version posted a couple days ago.

I also can't expand the benchmark window anymore, which makes it more difficult for me to read and compare the results.

Are there good reasons for removing parallel benchmarking and resizing the benchmark window?

**Comment by luongk** [comment]
They haven't been removed, they're 1.8.2 features.  The latest release is still 1.8.1.x

**Comment by mibtc** [comment]
Which server is best for nice hash

**Comment by peteraclausen** [comment]
Yeah, hopefully 1.8.2.0 Pre3 will be out soon (or 1.8.2.0 full release).

I can't loose neither of those 2 features, so I'll stick with Pre2 for now.

I agree that DSTM 0.5.8 should be added, and the issue with ccminer-alexis being real slow to spin up Nist5 on all cards on a large rig.

**Comment by kaos-1** [comment]
[DSTM 0.5.8](https://bitcointalk.org/index.php?topic=2021765.0)  is a must, I would also like to mention new version of [8.18 Klaust ](https://github.com/KlausT/ccminer/releases)2018 miner that is currently the fastest Neoscript miner on the market. (1100 KH/s on a regular 1070 amazing!). This will yield additional 600-700 KH/s per 6x rig. (*cuda 9.1 use the latest nvidia driver)
Nist5 slow spin could be due to variable difficulty on NH, currently i am back to using palginmod_1.1_Bulwark instead of the default in NHML until its fixed.
Also notable mention is the latest tpruvot 2.2.4 that has significant Lyra2v2 improvments.

Overall miners need a good update across the board. @DillonN

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
