### ISSUE TITLE
The program does not monitor the Internet connection

### ISSUE THREAD

**Issue by Lorise** [nicehash/NiceHashMiner#866]
If the rig can not connect to the wi-fi network at the time the program is started, such a message hangs. Even if the connection to the network occurs in a minute nothing will change and the mining will not start. It would be desirable that the program would monitor when there will be a connection to the Internet and begin its work.

<a href="https://imgbb.com/"><img src="https://image.ibb.co/dzcgRm/image.png" alt="image" border="0"></a>

**Comment by dadoremix** [comment]
wtf?
for serious

**Comment by Lorise** [comment]
If the rig can not connect to the wi-fi network at the time the program is started, such a message hangs. Even if the connection to the network occurs in a minute nothing will change and the mining will not start. It would be desirable that the program would monitor when there will be a connection to the Internet and begin its work.

<a href="https://imgbb.com/"><img src="https://image.ibb.co/dzcgRm/image.png" alt="image" border="0"></a>

**Comment by Lyz1052** [comment]
I've got the same problem...it's really frustrating

**Comment by sebeksd** [comment]
Yes it is frustrating especially when I restart NHML often (because GPU "connection" is lost) and this message occur in middle of the night (and internet connection is fine). It seems that 1.8.1.8 work a little better but still not perfect. After a while I made an workaround for myself, you can pull it and compile by yourself 99fb598672c992e9bb562f0d58e1ab640ca082ea
This workaround will restart NHML if this message is displayed for more then 30s (and auto start mining is enabled).

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
