### ISSUE TITLE
Less perfomance XmrStackCPU on all versions above 1.7.5.13

### ISSUE THREAD

**Issue by rakanishu82** [nicehash/NiceHashMiner#87]
For i7 2600k CryptoNight(XmrStackCPU (v140)) with 4 less threads option shows around 325Kh/s with 1.7.5.13 miner.  All versions of miner above shows ~210-250 KH/s at the same settings and reports memory alloc failed in prompt.
2600k 4.9GHz (stable), 16Gb RAM, swap-file is unlimited, win 10
![1 7 5 13](https://user-images.githubusercontent.com/30497578/28669278-4e287edc-72dc-11e7-8b76-5691bb06c082.PNG)
![1 8 0 2](https://user-images.githubusercontent.com/30497578/28669277-4e2683de-72dc-11e7-8cca-e3d7fb918353.PNG)
![settings](https://user-images.githubusercontent.com/30497578/28669276-4e2472a6-72dc-11e7-89f2-d73c907143e0.PNG)

**Comment by DillonN** [comment]
Interesting, there haven't been any changes to XmrStackCPU. It would seem the issue stems from the memory alloc failed, there are [some suggestions](https://github.com/nicehash/NiceHashMiner/issues/652) on the old repo you can try

**Comment by rakanishu82** [comment]
Already got all suggestions on from old repo - nothing changed for me.
Noticed that NH 1.7.5.13 run as administrator by default and 1.8.0.2 isn't.
Tried to run newer versions as admin and the problem is gone, just that simple.

**Comment by NoSubstitute** [comment]
NHM 2.0.0.12 suffers from this too.
Running as admin does nothing. Setting 16 GB swap does nothing.
Win10 Home doesn't have "Lock pages in memory", since no gpedit.
I did notice that I get an initial error message not included in your screenshot.

_MEMORY INIT ERROR: Obtaining SeLockMemoryPrivilege failied._

![20170812-0840-xmr_fails_memory_alloc](https://user-images.githubusercontent.com/12572734/29238683-8108fdee-7f3a-11e7-8ce0-ff0914de0f04.png)

Do note that I haven't touched the advanced config settings of NHM2. Just running it as is.
i7-6700K, 32 GB RAM, Nvidia 1070.
