### ISSUE TITLE
Why i cant set Extra Launch Parameters ?

### ISSUE THREAD

**Issue by zihyi** [nicehash/NiceHashMiner#886]
https://i.imgur.com/zOyePgn.jpg
with v1.8.1.6 ,R9-270
How can I set Extra Launch Parameters ?

**Comment by matmanmining** [comment]
I am having trouble with extralaunch parameters too.  I am trying to set -dcri for Claymore Dual.  Which parameter are you trying to set?  I require a different -dcri for each card that I have since they are all different.  I put in the value in extralaunch but it does not seem to stick, only goes to default.  If I change the actual start.bat file it works for a manual launch of Claymore, but it does not apply when I run NHLM.

**Comment by S74nk0** [comment]
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.
