### ISSUE TITLE
Miner has dropped rate of hashing significantly.

### ISSUE THREAD

**Issue by JS-88** [nicehash/NiceHashMiner#893]
Hello,

Over the past 4-5 days I have noticed a significant decrease in the has rate being generated by the miner. Currently it is reporting 100-158.00 Sols Equihash (see attachment). Normally this is at 25 to 27 Mh. The GPU is not as full load. On occasion is does return to full function at the hashrate of 25+ but sometimes for more more than an hour before dropping back down to the above mentioned figures. 

I cannot explain why this is happening, there is no defect as far as hardware is concerned as I have tested the GPU at full load with no issues. I have also attached a screenshot where I've captured it working as expected.
![capture](https://user-images.githubusercontent.com/35684089/35211784-d49e2692-ff4f-11e7-9ca8-00448e214f8a.PNG)

This concerns me not only due to the loss being made on this machine I am reporting this for, but also because I have built a multiple GPU system I'd like to use with NiceHash. Naturally, if the miner cannot fully draw hashrate from the card the operation becomes unfeasible. 

Please let me know the outcome of your investigation and how I can resolve this matter.

Thanks
![63972-167518-e0502c66bc736cf560a8496b9d818b61](https://user-images.githubusercontent.com/35684089/35211758-bbcdde00-ff4f-11e7-8f54-17e6e8194bf6.png)

**Comment by xiaoyaoyang** [comment]
I also noticed that sometime NiceHash won’t start all your graphic cards. E.g. when switch to Nist5 algorithm, despite the miners says start 3 miners, only 2 graphic cards are at full load, the other one is on a totally idle mode...

**Comment by vit078** [comment]
I have a similar problem!
There are several farms (1060, 1070,1070ti, 1080) have been working for a long time. Somewhere two or three weeks ago I began to notice that on all the cards speed fell and, as a consequence, profitability - for example 1080 on EQUIHESH EWBF gives a speed of about 280-300 salts (instead of the put 500! The same story with other cards / farms!

It was done the following, perezalit miner of different versions of Nisehash Miner Legasy 1.3 ...... 1.8.2. Updated firewood on maps to the latest version on the site nvidia. Reinstalled the system into a clean one with all the software-Win7-64. Result- after reinstalling the drivers and system, the mining starts at normal speed, after a short time about an hour, the speed again drops by 30-50%. Also tried to change the Internet connection from the 4G modem to the optics, the hub itself to which the equipment is connected.

**Comment by JS-88** [comment]
Must be quite a blow to your profits with this drop all of a sudden. As I'm writing this now I'm still have this issue over a week after I first noticed it. 

Have you found any solutions yet?

**Comment by isubh** [comment]
I am having the same problem. What is going on? Is that legal for nicehash? Is it time to close my account? I made the big investment to get bigger returns, I can't understand why my card starting to slow down when I haven't chang anything. Crazy

**Comment by JS-88** [comment]
I'm selling up my gear. Earnings have dropped 75% for me even after going into the settings and selecting the most profitable alg for me. Either selling hashing power is really becoming less profitable or Nicehash is eating so much of the profit that it's no longer feasible to sell hashing power anymore. When I first started out I was getting $4.5 per card, now I'm on less than .80 cent.

**Comment by isubh** [comment]
If anyone with more experience can tell us of a giid solutions, please do so. I feel about to shut down too.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
