### ISSUE TITLE
Reboot rig if no mining detected 

### ISSUE THREAD

**Issue by p1r473** [nicehash/NiceHashMiner#98]
Would love an option to reboot rig if no mining is detected. Being caused by gfx driver crashes or Ethernet adapter problems for me. Reset fixes it.

**Comment by kenman345** [comment]
I think an option like this should only be able to be enabled when the option to start on boot is selected so that we avoid unintentional behavior.

**Comment by p1r473** [comment]
I'm using a different method to start on boot so I would not like these 2 settings tied to each other. I am using a third party program called startup delayer but I also know some people are using task scheduler. The advantage of these programs is you can select a startup delay time instead of right at boot. I wait till all startup programs are loaded (I wait 45 seconds) before launching NHML, so please don't limit us to only when start on boot is checked

**Comment by DillonN** [comment]
Thanks for the suggestion, I'll look into implementing this in the future

**Comment by shadyjk** [comment]
Please do implement this, ive had so much wasted time due to gpu crashes. Im not home every day till really late and sometimes one of my cards will crash and there is no way for me to reset the rig. I cant remote in with teamviewer to reset it because it locks up and i have to physically reset the rig. Claymores dual miner has a feature to reboot the rig after a crash so for me it makes it more worth it to just use that instead which sucks because i really prefer nicehash miner. Plz implement this feature, or provide us with some sort of workaround till it is implemented. Would really appreciate it thx.

**Comment by DillonN** [comment]
This can be done with the "run script on CUDA crash" feature
